export interface KanjiData {
  kanji: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
}

export const N1_KANJI: KanjiData[] = [
  { kanji: "丁", onyomi: "ちょう、てい", kunyomi: "", meaning: "street, ward, town, counter for guns, tools, leaves" },
  { kanji: "丈", onyomi: "じょう", kunyomi: "たけ", meaning: "length, ten shaku, measure, Mr., Ms., height, stature" },
  { kanji: "丑", onyomi: "ちゅう", kunyomi: "うし", meaning: "sign of the ox or cow, 1-3AM, second sign of Chinese zodiac" },
  { kanji: "且", onyomi: "しょ、そ", kunyomi: "か（つ）", meaning: "moreover, also, furthermore" },
  { kanji: "丙", onyomi: "へい", kunyomi: "", meaning: "third class, 3rd, 3rd calendar sign" },
  { kanji: "丞", onyomi: "じょう", kunyomi: "", meaning: "help" },
  { kanji: "乃", onyomi: "だい、ない、の", kunyomi: "すなわ（ち）、なんじ", meaning: "from, possessive particle, whereupon, accordingly" },
  { kanji: "之", onyomi: "し", kunyomi: "これ、の、ゆ（く）", meaning: "of, this" },
  { kanji: "乏", onyomi: "ぼう", kunyomi: "とぼ（しい）", meaning: "scanty, fold, gap, fail, thin" },
  { kanji: "乙", onyomi: "おつ、いつ", kunyomi: "おと", meaning: "the latter, duplicate, strange, witty, fishhook radical" },
  { kanji: "也", onyomi: "や", kunyomi: "なり、か", meaning: "to be (archaic), classical final particle" },
  { kanji: "亘", onyomi: "こう、せん", kunyomi: "わた（る）", meaning: "span, range, extend over" },
  { kanji: "亜", onyomi: "あ", kunyomi: "つ（ぐ）", meaning: "Asia, rank next, come after, -ous" },
  { kanji: "亥", onyomi: "がい", kunyomi: "い", meaning: "sign of the hog, 9-11PM, twelfth sign of the Chinese zodiac" },
  { kanji: "亦", onyomi: "えき", kunyomi: "また", meaning: "also, again" },
  { kanji: "亨", onyomi: "こう", kunyomi: "", meaning: "pass through, go smoothly" },
  { kanji: "享", onyomi: "きょう", kunyomi: "う（ける）", meaning: "receive, undergo, answer (phone), take, get, catch" },
  { kanji: "亭", onyomi: "てい", kunyomi: "", meaning: "pavilion, restaurant, mansion, arbor, cottage, vaudeville, music hall, stage name" },
  { kanji: "亮", onyomi: "りょう", kunyomi: "あき（らか）", meaning: "clear, help" },
  { kanji: "仁", onyomi: "じん、に", kunyomi: "", meaning: "humanity, virtue, benevolence, mercy, kernel" },
  { kanji: "仙", onyomi: "せん", kunyomi: "", meaning: "hermit, wizard" },
  { kanji: "仰", onyomi: "ぎょう", kunyomi: "あお（ぐ）、おお（せ）", meaning: "face-up, look up, depend, seek, respect, rever, drink, take" },
  { kanji: "伊", onyomi: "い", kunyomi: "これ", meaning: "Italy, that one" },
  { kanji: "伍", onyomi: "ご", kunyomi: "", meaning: "five, 5, five-man squad, file, line" },
  { kanji: "伎", onyomi: "ぎ、き", kunyomi: "", meaning: "performing artist, actor" },
  { kanji: "伏", onyomi: "ふく", kunyomi: "ふ（せる）", meaning: "prostrated, bend down, bow, cover, lay (pipes)" },
  { kanji: "伐", onyomi: "ばつ", kunyomi: "き（る）", meaning: "fell, strike, attack, punish" },
  { kanji: "伯", onyomi: "はく", kunyomi: "", meaning: "chief, count, earl, uncle, brazil" },
  { kanji: "伴", onyomi: "はん、ばん", kunyomi: "ともな（う）", meaning: "consort, accompany, bring with, companion" },
  { kanji: "伶", onyomi: "れい", kunyomi: "", meaning: "actor" },
  { kanji: "伽", onyomi: "が、か", kunyomi: "とぎ", meaning: "nursing, attending, entertainer" },
  { kanji: "但", onyomi: "たん", kunyomi: "ただ（し）", meaning: "however, but" },
  { kanji: "佐", onyomi: "さ", kunyomi: "", meaning: "assistant, help" },
  { kanji: "佑", onyomi: "ゆう", kunyomi: "たす（ける）", meaning: "help, assist" },
  { kanji: "佳", onyomi: "か", kunyomi: "", meaning: "excellent, beautiful, good, pleasing, skilled" },
  { kanji: "併", onyomi: "へい", kunyomi: "あわ（せる）", meaning: "join, get together, unite, collective" },
  { kanji: "侃", onyomi: "かん", kunyomi: "", meaning: "strong, just, righteous, peace-loving" },
  { kanji: "侍", onyomi: "じ", kunyomi: "さむらい", meaning: "samurai, wait upon, serve" },
  { kanji: "侑", onyomi: "ゆう", kunyomi: "すす（める）", meaning: "urge to eat" },
  { kanji: "侮", onyomi: "ぶ", kunyomi: "あなど（る）", meaning: "scorn, despise, make light of, contempt" },
  { kanji: "侯", onyomi: "こう", kunyomi: "", meaning: "marquis, lord, daimyo" },
  { kanji: "侵", onyomi: "しん", kunyomi: "おか（す）", meaning: "encroach, invade, raid, trespass, violate" },
  { kanji: "俊", onyomi: "しゅん", kunyomi: "", meaning: "sagacious, genius, excellence" },
  { kanji: "俗", onyomi: "ぞく", kunyomi: "", meaning: "vulgar, customs, manners, worldliness, mundane things" },
  { kanji: "俳", onyomi: "はい", kunyomi: "", meaning: "haiku, actor" },
  { kanji: "俵", onyomi: "ひょう", kunyomi: "たわら", meaning: "bag, bale, sack, counter for bags" },
  { kanji: "俸", onyomi: "ほう", kunyomi: "", meaning: "stipend, salary" },
  { kanji: "倉", onyomi: "そう", kunyomi: "くら", meaning: "godown, warehouse, storehouse, cellar, treasury" },
  { kanji: "倖", onyomi: "こう", kunyomi: "", meaning: "happiness, luck" },
  { kanji: "倣", onyomi: "ほう", kunyomi: "なら（う）", meaning: "emulate, imitate" },
  { kanji: "倫", onyomi: "りん", kunyomi: "", meaning: "ethics, companion" },
  { kanji: "倭", onyomi: "わ", kunyomi: "", meaning: "Yamato, ancient Japan" },
  { kanji: "倹", onyomi: "けん", kunyomi: "", meaning: "frugal, economy, thrifty" },
  { kanji: "偏", onyomi: "へん", kunyomi: "かたよ（る）", meaning: "partial, side, left-side radical, inclining, biased" },
  { kanji: "偲", onyomi: "し", kunyomi: "しの（ぶ）", meaning: "recollect, remember" },
  { kanji: "偵", onyomi: "てい", kunyomi: "", meaning: "spy, detective" },
  { kanji: "偽", onyomi: "ぎ", kunyomi: "いつわ（る）、にせ", meaning: "falsehood, lie, deceive, pretend, counterfeit, forgery" },
  { kanji: "傍", onyomi: "ぼう", kunyomi: "かたわ（ら）、そば", meaning: "bystander, side, besides, while, nearby, 3rd person" },
  { kanji: "傑", onyomi: "けつ", kunyomi: "", meaning: "greatness, excellence" },
  { kanji: "傘", onyomi: "さん", kunyomi: "かさ", meaning: "umbrella" },
  { kanji: "催", onyomi: "さい", kunyomi: "もよお（す）", meaning: "sponsor, hold (a meeting), give (a dinner)" },
  { kanji: "傷", onyomi: "しょう", kunyomi: "きず、いた（む）", meaning: "wound, hurt, injure, impair, pain, injury, cut, gash" },
  { kanji: "僕", onyomi: "ぼく", kunyomi: "しもべ", meaning: "me, I (male), servant, manservant" },
  { kanji: "僚", onyomi: "りょう", kunyomi: "", meaning: "colleague, official, companion" },
  { kanji: "僧", onyomi: "そう", kunyomi: "", meaning: "Buddhist priest, monk" },
  { kanji: "儀", onyomi: "ぎ", kunyomi: "", meaning: "ceremony, rule, affair, case, a matter" },
  { kanji: "儒", onyomi: "じゅ", kunyomi: "", meaning: "Confucian" },
  { kanji: "償", onyomi: "しょう", kunyomi: "つぐな（う）", meaning: "reparation, make up for, recompense, redeem" },
  { kanji: "允", onyomi: "いん", kunyomi: "ゆる（す）", meaning: "license, sincerity, permit" },
  { kanji: "充", onyomi: "じゅう", kunyomi: "あ（てる）", meaning: "allot, fill" },
  { kanji: "克", onyomi: "こく", kunyomi: "か（つ）", meaning: "overcome, kindly, skillfully" },
  { kanji: "免", onyomi: "めん", kunyomi: "まぬか（れる）", meaning: "excuse, dismissal" },
  { kanji: "冗", onyomi: "じょう", kunyomi: "", meaning: "superfluous, uselessness" },
  { kanji: "冠", onyomi: "かん", kunyomi: "かんむり", meaning: "crown, best, peerless" },
  { kanji: "冴", onyomi: "ご", kunyomi: "さ（える）", meaning: "be clear, serene, cold, skillful" },
  { kanji: "冶", onyomi: "や", kunyomi: "", meaning: "melting, smelting" },
  { kanji: "准", onyomi: "じゅん", kunyomi: "", meaning: "quasi-, semi-, associate" },
  { kanji: "凌", onyomi: "りょう", kunyomi: "しの（ぐ）", meaning: "endure, keep (rain)out, stave off, tide over, defy" },
  { kanji: "凜", onyomi: "りん", kunyomi: "", meaning: "cold, strict, severe" },
  { kanji: "凝", onyomi: "ぎょう", kunyomi: "こ（る）", meaning: "congeal, freeze, stiff, be absorbed in" },
  { kanji: "凡", onyomi: "ぼん、はん", kunyomi: "おおよ（そ）、すべ（て）", meaning: "mediocre, ordinary, commonplace" },
  { kanji: "凪", onyomi: "", kunyomi: "なぎ", meaning: "lull, calm" },
  { kanji: "凱", onyomi: "がい", kunyomi: "", meaning: "triumph, victory" },
  { kanji: "凶", onyomi: "きょう", kunyomi: "", meaning: "villain, evil, bad luck, disaster" },
  { kanji: "凸", onyomi: "とつ", kunyomi: "でこ", meaning: "convex, beetle brow, uneven" },
  { kanji: "凹", onyomi: "おう", kunyomi: "くぼ（む）、へこ（む）", meaning: "concave, hollow, sunken" },
  { kanji: "刈", onyomi: "がい、かい", kunyomi: "か（る）", meaning: "reap, cut, clip, trim, prune" },
  { kanji: "刑", onyomi: "けい", kunyomi: "", meaning: "punish, penalty, sentence, punishment" },
  { kanji: "削", onyomi: "さく", kunyomi: "けず（る）", meaning: "plane, sharpen, whittle, pare" },
  { kanji: "剖", onyomi: "ぼう", kunyomi: "", meaning: "divide" },
  { kanji: "剛", onyomi: "ごう", kunyomi: "", meaning: "sturdy, strength" },
  { kanji: "剣", onyomi: "けん", kunyomi: "つるぎ", meaning: "sabre, sword, blade, clock hand" },
  { kanji: "剤", onyomi: "ざい", kunyomi: "", meaning: "dose, medicine, drug" },
  { kanji: "剰", onyomi: "じょう", kunyomi: "", meaning: "surplus, remainder" },
  { kanji: "創", onyomi: "そう", kunyomi: "つく（る）、きず", meaning: "genesis, wound, injury, hurt, start, originate" },
  { kanji: "功", onyomi: "こう、く", kunyomi: "いさお", meaning: "achievement, merits, success, honor, credit" },
  { kanji: "劣", onyomi: "れつ", kunyomi: "おと（る）", meaning: "inferiority, be inferior to, be worse" },
  { kanji: "励", onyomi: "れい", kunyomi: "はげ（む）", meaning: "encourage, be diligent, inspire" },
  { kanji: "劾", onyomi: "がい", kunyomi: "", meaning: "censure, criminal investigation" },
  { kanji: "勁", onyomi: "けい", kunyomi: "", meaning: "strong" },
  { kanji: "勅", onyomi: "ちょく", kunyomi: "", meaning: "imperial decree" },
  { kanji: "勘", onyomi: "かん", kunyomi: "", meaning: "intuition, perception" },
  { kanji: "勧", onyomi: "かん", kunyomi: "すす（める）", meaning: "persuade, recommend, advise, encourage, offer" },
  { kanji: "勲", onyomi: "くん", kunyomi: "いさお", meaning: "meritorious deed, merit" },
  { kanji: "勺", onyomi: "しゃく", kunyomi: "", meaning: "ladle, one tenth of a go, dip" },
  { kanji: "匁", onyomi: "もんめ", kunyomi: "", meaning: "monme, 3.75 grams, drm" },
  { kanji: "匠", onyomi: "しょう", kunyomi: "たくみ", meaning: "artisan, workman, carpenter" },
  { kanji: "匡", onyomi: "きょう", kunyomi: "ただ（す）", meaning: "correct, save, assist" },
  { kanji: "匿", onyomi: "とく", kunyomi: "かくま（う）", meaning: "hide, shelter, shield" },
  { kanji: "升", onyomi: "しょう", kunyomi: "ます", meaning: "measuring box, 1.8 liter" },
  { kanji: "卑", onyomi: "ひ", kunyomi: "いや（しい）", meaning: "lowly, base, vile, vulgar" },
  { kanji: "卓", onyomi: "たく", kunyomi: "", meaning: "eminent, table, desk, high" },
  { kanji: "博", onyomi: "はく、ばく", kunyomi: "", meaning: "Dr., command, esteem, win acclaim, Ph.D., exposition, fair" },
  { kanji: "卯", onyomi: "ぼう", kunyomi: "う", meaning: "sign of the hare or rabbit, 5-7AM, fourth sign of Chinese zodiac, east" },
  { kanji: "即", onyomi: "そく", kunyomi: "つ（く）", meaning: "instant, namely, as is, conform, agree, adapt" },
  { kanji: "却", onyomi: "きゃく", kunyomi: "かえ（って）", meaning: "instead, on the contrary, rather" },
  { kanji: "卸", onyomi: "ろ", kunyomi: "おろ（す）", meaning: "wholesale" },
  { kanji: "厄", onyomi: "やく", kunyomi: "", meaning: "unlucky, misfortune, bad luck, disaster" },
  { kanji: "厘", onyomi: "りん", kunyomi: "", meaning: "rin, 1/10 sen, 1/10 bu" },
  { kanji: "厳", onyomi: "げん、ごん", kunyomi: "きび（しい）、いか（めしい）", meaning: "stern, strictness, severity, rigidity" },
  { kanji: "又", onyomi: "ゆう", kunyomi: "また", meaning: "or again, furthermore, on the other hand" },
  { kanji: "及", onyomi: "きゅう", kunyomi: "およ（ぶ）、およ（び）", meaning: "reach out, exert, exercise, cause" },
  { kanji: "叔", onyomi: "しゅく", kunyomi: "", meaning: "uncle, youth" },
  { kanji: "叙", onyomi: "じょ", kunyomi: "つい（ず）", meaning: "confer, relate, narrate, describe" },
  { kanji: "叡", onyomi: "えい", kunyomi: "", meaning: "intelligence, imperial" },
  { kanji: "句", onyomi: "く", kunyomi: "", meaning: "phrase, clause, sentence, passage, paragraph" },
  { kanji: "只", onyomi: "し", kunyomi: "ただ", meaning: "only, free, in addition" },
  { kanji: "叶", onyomi: "きょう", kunyomi: "かな（う）", meaning: "grant, answer" },
  { kanji: "吉", onyomi: "きつ、きち", kunyomi: "よし", meaning: "good luck, joy, congratulations" },
  { kanji: "后", onyomi: "こう、ごう", kunyomi: "きさき", meaning: "empress, queen, after, behind, back, later" },
  { kanji: "吏", onyomi: "り", kunyomi: "", meaning: "officer, an official" },
  { kanji: "吐", onyomi: "と", kunyomi: "は（く）、つ（く）", meaning: "spit, vomit, belch, confess, tell (lies)" },
  { kanji: "吟", onyomi: "ぎん", kunyomi: "", meaning: "versify, singing, recital" },
  { kanji: "吾", onyomi: "ご", kunyomi: "われ、わ", meaning: "I, my, our, one's own" },
  { kanji: "呂", onyomi: "りょ、ろ", kunyomi: "", meaning: "spine, backbone" },
  { kanji: "呈", onyomi: "てい", kunyomi: "", meaning: "display, offer, present, send, exhibit" },
  { kanji: "呉", onyomi: "ご、く", kunyomi: "く（れる）", meaning: "give, do something for" },
  { kanji: "哀", onyomi: "あい", kunyomi: "あわ（れ）", meaning: "pathetic, grief, sorrow, pathos, pity, sympathize" },
  { kanji: "哉", onyomi: "さい", kunyomi: "かな、や", meaning: "how, what, alas, question mark, exclamation mark" },
  { kanji: "哲", onyomi: "てつ", kunyomi: "", meaning: "philosophy, clear" },
  { kanji: "唄", onyomi: "ばい", kunyomi: "うた", meaning: "song, ballad" },
  { kanji: "唆", onyomi: "さ", kunyomi: "そそのか（す）", meaning: "tempt, seduce, instigate, promote" },
  { kanji: "唇", onyomi: "しん", kunyomi: "くちびる", meaning: "lips" },
  { kanji: "唐", onyomi: "とう", kunyomi: "から", meaning: "T'ang, China" },
  { kanji: "唯", onyomi: "ゆい", kunyomi: "ただ", meaning: "solely, only, merely, simply" },
  { kanji: "啄", onyomi: "たく", kunyomi: "ついば（む）", meaning: "peck, pick up" },
  { kanji: "啓", onyomi: "けい", kunyomi: "ひら（く）", meaning: "disclose, open, say" },
  { kanji: "喚", onyomi: "かん", kunyomi: "", meaning: "yell, cry, call, scream, summon" },
  { kanji: "喝", onyomi: "かつ", kunyomi: "", meaning: "hoarse, scold" },
  { kanji: "喪", onyomi: "そう", kunyomi: "も", meaning: "miss, mourning" },
  { kanji: "喬", onyomi: "きょう", kunyomi: "", meaning: "high, boasting" },
  { kanji: "嗣", onyomi: "し", kunyomi: "", meaning: "heir, succeed" },
  { kanji: "嘆", onyomi: "たん", kunyomi: "なげ（く）", meaning: "sigh, lament, moan, grief" },
  { kanji: "嘉", onyomi: "か", kunyomi: "よみ（する）", meaning: "applaud, praise, esteem, happy, auspicious" },
  { kanji: "嘱", onyomi: "しょく", kunyomi: "", meaning: "entrust, request, send a message" },
  { kanji: "噴", onyomi: "ふん", kunyomi: "ふ（く）", meaning: "erupt, spout, emit, flush" },
  { kanji: "嚇", onyomi: "かく", kunyomi: "おど（す）", meaning: "menace, dignity, majesty, threaten" },
  { kanji: "囚", onyomi: "しゅう", kunyomi: "とら（われる）", meaning: "captured, criminal, arrest, catch" },
  { kanji: "圭", onyomi: "けい", kunyomi: "", meaning: "square jewel, corner, angle, edge" },
  { kanji: "坪", onyomi: "つぼ", kunyomi: "", meaning: "two-mat area, approx. thirty-six sq ft" },
  { kanji: "垂", onyomi: "すい", kunyomi: "た（れる）、た（らす）", meaning: "droop, suspend, hang, slouch" },
  { kanji: "垣", onyomi: "えん", kunyomi: "かき", meaning: "hedge, fence, wall" },
  { kanji: "執", onyomi: "しつ、しゅう", kunyomi: "と（る）", meaning: "tenacious, take hold, grasp, take to heart" },
  { kanji: "培", onyomi: "ばい", kunyomi: "つちか（う）", meaning: "cultivate, foster" },
  { kanji: "堀", onyomi: "くつ", kunyomi: "ほり", meaning: "ditch, moat, canal" },
  { kanji: "堅", onyomi: "けん", kunyomi: "かた（い）", meaning: "strict, hard, solid, tough, tight, reliable" },
  { kanji: "堕", onyomi: "だ", kunyomi: "お（ちる）", meaning: "degenerate, descend to, lapse into" },
  { kanji: "堤", onyomi: "てい", kunyomi: "つつみ", meaning: "dike, bank, embankment" },
  { kanji: "堪", onyomi: "かん、たん", kunyomi: "た（える）", meaning: "withstand, endure, support, resist" },
  { kanji: "塀", onyomi: "へい", kunyomi: "", meaning: "fence, wall, (kokuji)" },
  { kanji: "塁", onyomi: "るい", kunyomi: "", meaning: "bases, fort, rampart, walls, base(ball)" },
  { kanji: "塊", onyomi: "かい", kunyomi: "かたまり", meaning: "clod, lump, chink, clot, mass" },
  { kanji: "塑", onyomi: "そ", kunyomi: "", meaning: "model, molding" },
  { kanji: "塾", onyomi: "じゅく", kunyomi: "", meaning: "cram school, private school" },
  { kanji: "墓", onyomi: "ぼ", kunyomi: "はか", meaning: "grave, tomb" },
  { kanji: "墜", onyomi: "つい", kunyomi: "お（ちる）", meaning: "crash, fall (down)" },
  { kanji: "墳", onyomi: "ふん", kunyomi: "", meaning: "tomb, mound" },
  { kanji: "墾", onyomi: "こん", kunyomi: "は（る）", meaning: "groundbreaking, open up farmland" },
  { kanji: "壇", onyomi: "だん、たん", kunyomi: "", meaning: "podium, stage, rostrum, terrace" },
  { kanji: "壊", onyomi: "かい、え", kunyomi: "こわ（す）", meaning: "demolition, break, destroy" },
  { kanji: "壌", onyomi: "じょう", kunyomi: "", meaning: "soil, loam, earth, rich" },
  { kanji: "壮", onyomi: "そう", kunyomi: "", meaning: "robust, manhood, prosperity" },
  { kanji: "壱", onyomi: "いち", kunyomi: "", meaning: "one (in documents)" },
  { kanji: "奇", onyomi: "き", kunyomi: "く（しき）、あや（しい）", meaning: "strange, strangeness, curiosity" },
  { kanji: "奈", onyomi: "な、だ", kunyomi: "いかん", meaning: "Nara, what?" },
  { kanji: "奉", onyomi: "ほう、ぶ", kunyomi: "たてまつ（る）", meaning: "dedicate, offer, present, give" },
  { kanji: "奔", onyomi: "ほん", kunyomi: "はし（る）", meaning: "run, bustle" },
  { kanji: "奎", onyomi: "けい", kunyomi: "", meaning: "star, god of literature" },
  { kanji: "奏", onyomi: "そう", kunyomi: "かな（でる）", meaning: "play music, speak to a ruler, complete" },
  { kanji: "奨", onyomi: "しょう", kunyomi: "すす（める）", meaning: "exhort, urge, encourage" },
  { kanji: "奮", onyomi: "ふん", kunyomi: "ふる（う）", meaning: "stirred up, be invigorated, flourish" },
  { kanji: "奴", onyomi: "ど", kunyomi: "やつ、やっこ", meaning: "guy, slave, manservant, fellow" },
  { kanji: "如", onyomi: "じょ、にょ", kunyomi: "ごと（し）", meaning: "likeness, like, such as, as if, better, best, equal" },
  { kanji: "妃", onyomi: "ひ", kunyomi: "", meaning: "queen, princess" },
  { kanji: "妄", onyomi: "もう、ぼう", kunyomi: "みだ（りに）", meaning: "delusion, unnecessarily, without authority, reckless" },
  { kanji: "妊", onyomi: "にん", kunyomi: "はら（む）", meaning: "pregnancy, conceive" },
  { kanji: "妙", onyomi: "みょう", kunyomi: "たえ", meaning: "exquisite, strange, queer, mystery, miracle, excellent, clever, skillful" },
  { kanji: "妥", onyomi: "だ", kunyomi: "", meaning: "gentle, peace, depravity" },
  { kanji: "妨", onyomi: "ぼう", kunyomi: "さまた（げる）", meaning: "disturb, prevent, hamper, obstruct" },
  { kanji: "姫", onyomi: "き", kunyomi: "ひめ", meaning: "princess" },
  { kanji: "姻", onyomi: "いん", kunyomi: "", meaning: "matrimony, marry" },
  { kanji: "威", onyomi: "い", kunyomi: "おど（す）", meaning: "intimidate, dignity, majesty, menace, threaten" },
  { kanji: "娠", onyomi: "しん", kunyomi: "", meaning: "with child, pregnancy" },
  { kanji: "娯", onyomi: "ご", kunyomi: "", meaning: "recreation, pleasure" },
  { kanji: "婆", onyomi: "ば", kunyomi: "ばば", meaning: "old woman, grandma, wet nurse" },
  { kanji: "婿", onyomi: "せい", kunyomi: "むこ", meaning: "bridegroom, son-in-law" },
  { kanji: "媒", onyomi: "ばい", kunyomi: "", meaning: "mediator, go-between" },
  { kanji: "媛", onyomi: "えん", kunyomi: "ひめ", meaning: "beautiful woman, princess" },
  { kanji: "嫁", onyomi: "か", kunyomi: "よめ、とつ（ぐ）", meaning: "marry into, bride" },
  { kanji: "嫌", onyomi: "けん、げん", kunyomi: "きら（う）、いや", meaning: "dislike, detest, hate" },
  { kanji: "嫡", onyomi: "ちゃく", kunyomi: "", meaning: "legitimate wife, direct descent (non-bastard)" },
  { kanji: "嬉", onyomi: "き", kunyomi: "うれ（しい）", meaning: "glad, pleased, rejoice" },
  { kanji: "嬢", onyomi: "じょう", kunyomi: "", meaning: "lass, girl, Miss, daughter" },
  { kanji: "孔", onyomi: "こう", kunyomi: "あな", meaning: "cavity, hole, slit, very, great, exceedingly" },
  { kanji: "孟", onyomi: "もう", kunyomi: "", meaning: "eldest brother, first month of a season" },
  { kanji: "孤", onyomi: "こ", kunyomi: "", meaning: "orphan, alone" },
  { kanji: "宏", onyomi: "こう", kunyomi: "", meaning: "wide, large" },
  { kanji: "宜", onyomi: "ぎ", kunyomi: "よろ（しい）", meaning: "best regards, good" },
  { kanji: "宣", onyomi: "せん", kunyomi: "のたま（う）", meaning: "proclaim, say, announce" },
  { kanji: "宥", onyomi: "ゆう", kunyomi: "なだ（める）", meaning: "soothe, calm, pacify" },
  { kanji: "宰", onyomi: "さい", kunyomi: "", meaning: "superintend, manager, rule" },
  { kanji: "宴", onyomi: "えん", kunyomi: "うたげ", meaning: "banquet, feast, party" },
  { kanji: "宵", onyomi: "しょう", kunyomi: "よい", meaning: "wee hours, evening, early night" },
  { kanji: "寂", onyomi: "じゃく、せき", kunyomi: "さび（しい）", meaning: "loneliness, quietly, mellow, mature, death of a priest" },
  { kanji: "寅", onyomi: "いん", kunyomi: "とら", meaning: "sign of the tiger, 3-5AM, third sign of Chinese zodiac" },
  { kanji: "寛", onyomi: "かん", kunyomi: "くつろ（ぐ）", meaning: "tolerant, leniency, generosity, relax, feel at home" },
  { kanji: "寡", onyomi: "か", kunyomi: "", meaning: "widow, minority, few" },
  { kanji: "寧", onyomi: "ねい", kunyomi: "", meaning: "rather, preferably, peaceful, quiet, tranquility" },
  { kanji: "審", onyomi: "しん", kunyomi: "つまび（らか）", meaning: "hearing, judge, trial" },
  { kanji: "寮", onyomi: "りょう", kunyomi: "", meaning: "dormitory, hostel, villa, tea pavillion" },
  { kanji: "寸", onyomi: "すん", kunyomi: "", meaning: "measurement, foot/10" },
  { kanji: "寿", onyomi: "じゅ、す、しゅう", kunyomi: "ことぶき", meaning: "longevity, congratulations, one's natural life" },
  { kanji: "射", onyomi: "しゃ", kunyomi: "い（る）、さ（す）", meaning: "shoot, shine into, onto, archery" },
  { kanji: "尉", onyomi: "い、じょう", kunyomi: "", meaning: "military officer, jailer, old man, rank" },
  { kanji: "尋", onyomi: "じん", kunyomi: "たず（ねる）、ひろ", meaning: "inquire, fathom, look for" },
  { kanji: "尚", onyomi: "しょう", kunyomi: "なお", meaning: "esteem, furthermore, still, yet" },
  { kanji: "尭", onyomi: "ぎょう", kunyomi: "", meaning: "high, far" },
  { kanji: "就", onyomi: "しゅう、じゅ", kunyomi: "つ（く）、つ（ける）", meaning: "concerning, settle, take position, depart, study, per" },
  { kanji: "尺", onyomi: "しゃく", kunyomi: "", meaning: "shaku, Japanese foot, measure, scale, rule" },
  { kanji: "尼", onyomi: "に", kunyomi: "あま", meaning: "nun" },
  { kanji: "尽", onyomi: "じん", kunyomi: "つ（きる）、つ（かす）", meaning: "exhaust, use up, run out of, deplete, befriend, serve" },
  { kanji: "尾", onyomi: "び", kunyomi: "お", meaning: "tail, end, counter for fish, lower slope of mountain" },
  { kanji: "尿", onyomi: "にょう", kunyomi: "", meaning: "urine" },
  { kanji: "屈", onyomi: "くつ", kunyomi: "かが（む）", meaning: "yield, bend, flinch, submit" },
  { kanji: "履", onyomi: "り", kunyomi: "は（く）", meaning: "perform, complete, footgear, shoes, boots, put on (the feet)" },
  { kanji: "屯", onyomi: "とん", kunyomi: "", meaning: "barracks, police station, camp" },
  { kanji: "岐", onyomi: "き", kunyomi: "", meaning: "branch off, fork in road, scene, arena, theater" },
  { kanji: "岬", onyomi: "こう", kunyomi: "みさき", meaning: "headland, cape, spit, promontory" },
  { kanji: "岳", onyomi: "がく", kunyomi: "たけ", meaning: "point, peak, mountain" },
  { kanji: "峠", onyomi: "", kunyomi: "とうげ", meaning: "mountain peak, mountain pass, climax, crest, (kokuji)" },
  { kanji: "峡", onyomi: "きょう", kunyomi: "", meaning: "gorge, ravine" },
  { kanji: "峻", onyomi: "しゅん", kunyomi: "", meaning: "steep" },
  { kanji: "崇", onyomi: "すう", kunyomi: "あが（める）", meaning: "adore, respect, revere, worship" },
  { kanji: "崎", onyomi: "き", kunyomi: "さき", meaning: "promontory, cape, spit" },
  { kanji: "崚", onyomi: "りょう", kunyomi: "", meaning: "towering in a row" },
  { kanji: "崩", onyomi: "ほう", kunyomi: "くず（れる）", meaning: "crumble, die, demolish, level" },
  { kanji: "嵐", onyomi: "らん", kunyomi: "あらし", meaning: "storm, tempest" },
  { kanji: "嵩", onyomi: "すう", kunyomi: "かさ", meaning: "be aggravated, grow worse, grow bulky, swell" },
  { kanji: "嵯", onyomi: "さ", kunyomi: "", meaning: "steep, craggy, rugged" },
  { kanji: "嶺", onyomi: "れい", kunyomi: "みね", meaning: "peak, summit" },
  { kanji: "巌", onyomi: "がん", kunyomi: "いわお", meaning: "rock, crag, boulder" },
  { kanji: "巧", onyomi: "こう", kunyomi: "たく（み）", meaning: "adroit, skilled, ingenuity" },
  { kanji: "己", onyomi: "こ、き", kunyomi: "おのれ", meaning: "self" },
  { kanji: "巳", onyomi: "し", kunyomi: "み", meaning: "sign of the snake or serpent, 9-11AM, sixth sign of Chinese zodiac" },
  { kanji: "巴", onyomi: "は", kunyomi: "ともえ", meaning: "comma-design" },
  { kanji: "巽", onyomi: "そん", kunyomi: "たつみ", meaning: "southeast" },
  { kanji: "帆", onyomi: "はん", kunyomi: "ほ", meaning: "sail" },
  { kanji: "帝", onyomi: "てい", kunyomi: "みかど", meaning: "sovereign, the emperor, god, creator" },
  { kanji: "帥", onyomi: "すい", kunyomi: "", meaning: "commander, leading troops, governor" },
  { kanji: "帳", onyomi: "ちょう", kunyomi: "", meaning: "notebook, account book, album" },
  { kanji: "幕", onyomi: "まく、ばく", kunyomi: "", meaning: "curtain, bunting, act of play" },
  { kanji: "幣", onyomi: "へい", kunyomi: "ぬさ", meaning: "cash, bad habit, humble prefix, gift, Shinto offerings of cloth, rope, cut paper" },
  { kanji: "幻", onyomi: "げん", kunyomi: "まぼろし", meaning: "phantasm, vision, dream, illusion, apparition" },
  { kanji: "幽", onyomi: "ゆう", kunyomi: "かす（か）", meaning: "seclude, confine to a room, deep, profound, secluded, faint, dark, tranquil, calm" },
  { kanji: "庄", onyomi: "しょう", kunyomi: "", meaning: "level, in the country, manor, village, hamlet" },
  { kanji: "序", onyomi: "じょ", kunyomi: "ついで", meaning: "preface, beginning, order, precedence, occasion, chance, incidentally" },
  { kanji: "庶", onyomi: "しょ", kunyomi: "", meaning: "commoner, all, bastard" },
  { kanji: "庸", onyomi: "よう", kunyomi: "", meaning: "commonplace, ordinary, employment" },
  { kanji: "廃", onyomi: "はい", kunyomi: "すた（れる）", meaning: "abolish, obsolete, cessation, discarding, abandon" },
  { kanji: "廊", onyomi: "ろう", kunyomi: "", meaning: "corridor, hall, tower" },
  { kanji: "廉", onyomi: "れん", kunyomi: "", meaning: "bargain, reason, charge, suspicion, point, account, purity, honest, low price, cheap, rested, contented, peaceful" },
  { kanji: "廷", onyomi: "てい", kunyomi: "", meaning: "courts, imperial court, government office" },
  { kanji: "弁", onyomi: "べん、へん", kunyomi: "わきま（える）", meaning: "valve, petal, braid, speech, dialect, discrimination, dispose of, distinguish" },
  { kanji: "弊", onyomi: "へい", kunyomi: "", meaning: "abuse, evil, vice, breakage" },
  { kanji: "弐", onyomi: "に、じ", kunyomi: "", meaning: "two, two radical (no. 7)" },
  { kanji: "弓", onyomi: "きゅう", kunyomi: "ゆみ", meaning: "bow, bow (archery, violin)" },
  { kanji: "弔", onyomi: "ちょう", kunyomi: "とむら（う）", meaning: "condolences, mourning, regret" },
  { kanji: "弘", onyomi: "こう", kunyomi: "ひろ（い）", meaning: "vast, broad, wide" },
  { kanji: "弥", onyomi: "み、び", kunyomi: "や、いや、いよいよ", meaning: "all the more, increasingly" },
  { kanji: "弦", onyomi: "げん", kunyomi: "つる", meaning: "bowstring, chord, hypotenuse" },
  { kanji: "弧", onyomi: "こ", kunyomi: "", meaning: "arc, arch, bow" },
  { kanji: "彗", onyomi: "すい", kunyomi: "", meaning: "comet" },
  { kanji: "彦", onyomi: "げん", kunyomi: "ひこ", meaning: "boy, prince" },
  { kanji: "彩", onyomi: "さい", kunyomi: "いろど（る）", meaning: "coloring, paint, makeup" },
  { kanji: "彫", onyomi: "ちょう", kunyomi: "ほ（る）", meaning: "carve, engrave, chisel" },
  { kanji: "彬", onyomi: "ひん", kunyomi: "", meaning: "refined, gentle" },
  { kanji: "彰", onyomi: "しょう", kunyomi: "", meaning: "patent, clear" },
  { kanji: "影", onyomi: "えい", kunyomi: "かげ", meaning: "shadow, silhouette, phantom" },
  { kanji: "往", onyomi: "おう", kunyomi: "い（く）、いにしえ", meaning: "journey, chase away, let go, going, travel" },
  { kanji: "征", onyomi: "せい", kunyomi: "", meaning: "subjugate, attack the rebellious, collect taxes" },
  { kanji: "徐", onyomi: "じょ", kunyomi: "おもむ（ろに）", meaning: "gradually, slowly, deliberately, gently" },
  { kanji: "従", onyomi: "じゅう、しょう、じゅ", kunyomi: "したが（う）", meaning: "accompany, obey, submit to, comply, follow, secondary, incidental, subordinate" },
  { kanji: "循", onyomi: "じゅん", kunyomi: "", meaning: "sequential, follow" },
  { kanji: "微", onyomi: "び", kunyomi: "かす（か）", meaning: "delicate, minuteness, insignificance" },
  { kanji: "徴", onyomi: "ちょう", kunyomi: "しるし", meaning: "indications, sign, omen, symptom, collect, seek, refer to, question" },
  { kanji: "徹", onyomi: "てつ", kunyomi: "", meaning: "penetrate, clear, pierce, strike home, sit up (all night)" },
  { kanji: "忌", onyomi: "き", kunyomi: "い（む）、い（まわしい）", meaning: "mourning, abhor, detestable, death anniversary" },
  { kanji: "忍", onyomi: "にん", kunyomi: "しの（ぶ）", meaning: "endure, bear, put up with, conceal, secrete, spy, sneak" },
  { kanji: "忠", onyomi: "ちゅう", kunyomi: "", meaning: "loyalty, fidelity, faithfulness" },
  { kanji: "怜", onyomi: "れい", kunyomi: "", meaning: "wise" },
  { kanji: "怠", onyomi: "たい", kunyomi: "おこた（る）、なま（ける）", meaning: "neglect, laziness" },
  { kanji: "怪", onyomi: "かい", kunyomi: "あや（しい）", meaning: "suspicious, mystery, apparition" },
  { kanji: "恒", onyomi: "こう", kunyomi: "", meaning: "constancy, always" },
  { kanji: "恕", onyomi: "じょ", kunyomi: "", meaning: "forgive, pardon" },
  { kanji: "恨", onyomi: "こん", kunyomi: "うら（む）", meaning: "regret, bear a grudge, resentment, malice, hatred" },
  { kanji: "恭", onyomi: "きょう", kunyomi: "うやうや（しい）", meaning: "respect, reverent" },
  { kanji: "悌", onyomi: "てい", kunyomi: "", meaning: "brotherly, respectful" },
  { kanji: "悔", onyomi: "かい", kunyomi: "く（いる）、く（やむ）", meaning: "repent, regret" },
  { kanji: "悟", onyomi: "ご", kunyomi: "さと（る）", meaning: "enlightenment, perceive, discern, realize, understand" },
  { kanji: "悠", onyomi: "ゆう", kunyomi: "", meaning: "permanence, distant, long time, leisure" },
  { kanji: "患", onyomi: "かん", kunyomi: "わずら（う）", meaning: "afflicted, disease, suffer from, be ill" },
  { kanji: "悦", onyomi: "えつ", kunyomi: "よろこ（ぶ）", meaning: "ecstasy, joy, rapture" },
  { kanji: "悼", onyomi: "とう", kunyomi: "いた（む）", meaning: "lament, grieve over" },
  { kanji: "惇", onyomi: "じゅん、とん", kunyomi: "あつ（い）", meaning: "sincere, kind, considerate" },
  { kanji: "惑", onyomi: "わく", kunyomi: "まど（う）", meaning: "beguile, delusion, perplexity" },
  { kanji: "惟", onyomi: "い、ゆい", kunyomi: "おも（う）、これ", meaning: "consider, reflect, think" },
  { kanji: "惣", onyomi: "そう", kunyomi: "", meaning: "general, overall, total" },
  { kanji: "惨", onyomi: "さん、ざん", kunyomi: "みじ（め）", meaning: "wretched, disaster, cruelty, harsh" },
  { kanji: "惰", onyomi: "だ", kunyomi: "", meaning: "lazy, laziness" },
  { kanji: "愁", onyomi: "しゅう", kunyomi: "うれ（える）", meaning: "distress, grieve, lament, be anxious" },
  { kanji: "愚", onyomi: "ぐ", kunyomi: "おろ（か）", meaning: "foolish, folly, absurdity, stupid" },
  { kanji: "慨", onyomi: "がい", kunyomi: "", meaning: "rue, be sad, sigh, lament" },
  { kanji: "慈", onyomi: "じ", kunyomi: "いつく（しむ）", meaning: "mercy" },
  { kanji: "態", onyomi: "たい", kunyomi: "わざ（と）", meaning: "attitude, condition, figure, appearance, voice (of verbs)" },
  { kanji: "慌", onyomi: "こう", kunyomi: "あわ（てる）", meaning: "disconcerted, be confused, lose one's head" },
  { kanji: "慕", onyomi: "ぼ", kunyomi: "した（う）", meaning: "pining, yearn for, love dearly, adore" },
  { kanji: "慢", onyomi: "まん", kunyomi: "", meaning: "ridicule, laziness" },
  { kanji: "慧", onyomi: "え、けい", kunyomi: "", meaning: "wise" },
  { kanji: "慮", onyomi: "りょ", kunyomi: "おもんぱか（る）", meaning: "prudence, thought, concern, consider, deliberate, fear" },
  { kanji: "慶", onyomi: "けい", kunyomi: "よろこ（び）", meaning: "jubilation, congratulate, rejoice, be happy" },
  { kanji: "憂", onyomi: "ゆう", kunyomi: "うれ（える）", meaning: "melancholy, grieve, lament, be anxious, sad, unhappy" },
  { kanji: "憤", onyomi: "ふん", kunyomi: "いきどお（る）", meaning: "aroused, resent, be indignant, anger" },
  { kanji: "憧", onyomi: "しょう、どう", kunyomi: "あこが（れる）", meaning: "yearn, long for, aspire to, admire, adore" },
  { kanji: "憩", onyomi: "けい", kunyomi: "いこ（い）", meaning: "repose, rest, relax, recess" },
  { kanji: "健", onyomi: "けん", kunyomi: "すこ（やか）", meaning: "healthy, health, strength, persistence" },
  { kanji: "憲", onyomi: "けん", kunyomi: "", meaning: "constitution, law" },
  { kanji: "憶", onyomi: "おく", kunyomi: "", meaning: "recollection, think, remember" },
  { kanji: "憾", onyomi: "かん", kunyomi: "", meaning: "remorse, regret, be sorry" },
  { kanji: "懇", onyomi: "こん", kunyomi: "ねんご（ろ）", meaning: "sociable, kind, courteous, hospitable, cordial" },
  { kanji: "懐", onyomi: "かい", kunyomi: "ふところ、なつ（かしい）", meaning: "pocket, feelings, heart, yearn, miss someone, become attached to, bosom, breast" },
  { kanji: "懲", onyomi: "ちょう", kunyomi: "こ（りる）", meaning: "penal, chastise, punish, discipline" },
  { kanji: "懸", onyomi: "けん、け", kunyomi: "か（ける）、か（かる）", meaning: "state of suspension, hang, depend, consult, distant, far apart" },
  { kanji: "我", onyomi: "が", kunyomi: "われ、わ", meaning: "ego, I, selfish, our, oneself" },
  { kanji: "戒", onyomi: "かい", kunyomi: "いまし（める）", meaning: "commandment, precept, prohibition, discipline, banning" },
  { kanji: "戯", onyomi: "ぎ", kunyomi: "たわむ（れる）", meaning: "frolic, play, sport" },
  { kanji: "扇", onyomi: "せん", kunyomi: "おうぎ、あお（ぐ）", meaning: "fan, folding fan" },
  { kanji: "扉", onyomi: "ひ", kunyomi: "とびら", meaning: "front door, title page, front page" },
  { kanji: "扶", onyomi: "ふ", kunyomi: "たす（ける）", meaning: "aid, help, assist" },
  { kanji: "抄", onyomi: "しょう", kunyomi: "", meaning: "extract, selection, summary, copy, spread thin" },
  { kanji: "把", onyomi: "は", kunyomi: "", meaning: "grasp, faggot, bunch, counter for bundles" },
  { kanji: "抑", onyomi: "よく", kunyomi: "おさ（える）", meaning: "repress, well, now, in the first place, push, shove, press, seal, do in spite of" },
  { kanji: "抗", onyomi: "こう", kunyomi: "あらが（う）", meaning: "confront, resist, defy, oppose" },
  { kanji: "披", onyomi: "ひ", kunyomi: "", meaning: "expose, open" },
  { kanji: "抵", onyomi: "てい", kunyomi: "", meaning: "resist, reach, touch" },
  { kanji: "抹", onyomi: "まつ", kunyomi: "", meaning: "rub, paint, erase" },
  { kanji: "抽", onyomi: "ちゅう", kunyomi: "", meaning: "pluck, pull, extract, excel" },
  { kanji: "拍", onyomi: "はく", kunyomi: "", meaning: "clap, beat (music)" },
  { kanji: "拐", onyomi: "かい", kunyomi: "", meaning: "kidnap, falsify" },
  { kanji: "拒", onyomi: "きょ", kunyomi: "こば（む）", meaning: "repel, refuse, reject, decline" },
  { kanji: "拓", onyomi: "たく", kunyomi: "", meaning: "clear (the land), open, break up" },
  { kanji: "拘", onyomi: "こう", kunyomi: "かか（わる）", meaning: "arrest, seize, concerned, adhere to, despite" },
  { kanji: "拙", onyomi: "せつ", kunyomi: "つたな（い）", meaning: "bungling, clumsy, unskillful" },
  { kanji: "拠", onyomi: "きょ", kunyomi: "よ（る）", meaning: "foothold, based on, follow, therefore" },
  { kanji: "括", onyomi: "かつ", kunyomi: "くく（る）", meaning: "fasten, tie up, arrest, constrict" },
  { kanji: "拳", onyomi: "けん", kunyomi: "こぶし", meaning: "fist" },
  { kanji: "拷", onyomi: "ごう", kunyomi: "", meaning: "torture, beat" },
  { kanji: "挑", onyomi: "ちょう", kunyomi: "いど（む）", meaning: "challenge, contend for, make love to" },
  { kanji: "振", onyomi: "しん", kunyomi: "ふ（る）", meaning: "shake, wave, wag, swing" },
  { kanji: "挿", onyomi: "そう", kunyomi: "さ（す）", meaning: "insert, put in, graft, wear (sword)" },
  { kanji: "据", onyomi: "きょ", kunyomi: "す（える）", meaning: "set, lay a foundation, install, equip, squat down" },
  { kanji: "捷", onyomi: "しょう", kunyomi: "", meaning: "victory, fast" },
  { kanji: "捺", onyomi: "なつ", kunyomi: "", meaning: "press, print, affix a seal, stamp" },
  { kanji: "掌", onyomi: "しょう", kunyomi: "てのひら", meaning: "manipulate, rule, administer, conduct, palm of hand" },
  { kanji: "排", onyomi: "はい", kunyomi: "", meaning: "repudiate, exclude, expel, reject, line up, arrange" },
  { kanji: "控", onyomi: "こう", kunyomi: "ひか（える）", meaning: "withdraw, draw in, hold back, refrain from, be moderate" },
  { kanji: "措", onyomi: "そ", kunyomi: "", meaning: "set aside, give up, suspend, discontinue, lay aside" },
  { kanji: "掲", onyomi: "けい", kunyomi: "かか（げる）", meaning: "put up (a notice), put up, hoist, display, hang out, publish, describe" },
  { kanji: "提", onyomi: "てい", kunyomi: "さ（げる）", meaning: "propose, take along, carry in hand" },
  { kanji: "揚", onyomi: "よう", kunyomi: "あ（げる）", meaning: "hoist, fry in deep fat" },
  { kanji: "握", onyomi: "あく", kunyomi: "にぎ（る）", meaning: "grip, hold, mould sushi, bribe" },
  { kanji: "援", onyomi: "えん", kunyomi: "", meaning: "abet, help, save" },
  { kanji: "搬", onyomi: "はん", kunyomi: "", meaning: "conveyor, carry, transport" },
  { kanji: "搭", onyomi: "とう", kunyomi: "", meaning: "board, load (a vehicle), ride" },
  { kanji: "携", onyomi: "けい", kunyomi: "たずさ（える）", meaning: "portable, carry (in hand), armed with, bring along" },
  { kanji: "搾", onyomi: "さく", kunyomi: "しぼ（る）", meaning: "squeeze" },
  { kanji: "摂", onyomi: "せつ", kunyomi: "", meaning: "vicarious, surrogate, act in addition to" },
  { kanji: "摘", onyomi: "てき", kunyomi: "つ（む）", meaning: "pinch, pick, pluck, trim, clip, summarize" },
  { kanji: "摩", onyomi: "ま", kunyomi: "ま（する）", meaning: "chafe, rub, polish, grind, scrape" },
  { kanji: "撃", onyomi: "げき", kunyomi: "う（つ）", meaning: "beat, attack, defeat, conquer" },
  { kanji: "撤", onyomi: "てつ", kunyomi: "", meaning: "remove, withdraw, disarm, dismantle, reject, exclude" },
  { kanji: "撮", onyomi: "さつ", kunyomi: "と（る）", meaning: "snapshot, take pictures" },
  { kanji: "撲", onyomi: "ぼく", kunyomi: "", meaning: "slap, strike, hit, beat, tell, speak" },
  { kanji: "擁", onyomi: "よう", kunyomi: "", meaning: "hug, embrace, possess, protect, lead" },
  { kanji: "擦", onyomi: "さつ", kunyomi: "す（る）", meaning: "grate, rub, scratch, scrape, chafe, scour" },
  { kanji: "擬", onyomi: "ぎ", kunyomi: "もど（き）", meaning: "mimic, aim (a gun) at, nominate, imitate" },
  { kanji: "攻", onyomi: "こう", kunyomi: "せ（める）", meaning: "aggression, attack, criticize, polish" },
  { kanji: "敏", onyomi: "びん", kunyomi: "", meaning: "cleverness, agile, alert" },
  { kanji: "敢", onyomi: "かん", kunyomi: "あ（えて）", meaning: "daring, brave, bold, sad, tragic, pitiful" },
  { kanji: "敦", onyomi: "とん", kunyomi: "あつ（い）", meaning: "industry, kindliness" },
  { kanji: "敵", onyomi: "てき", kunyomi: "かたき", meaning: "enemy, foe, opponent" },
  { kanji: "斉", onyomi: "せい", kunyomi: "そろ（う）", meaning: "adjusted, alike, equal, similar variety of" },
  { kanji: "斎", onyomi: "さい", kunyomi: "", meaning: "purification, Buddhist food, room, worship, avoid, alike" },
  { kanji: "斐", onyomi: "ひ", kunyomi: "", meaning: "beautiful, patterned" },
  { kanji: "斗", onyomi: "と、とう", kunyomi: "", meaning: "Big Dipper, ten sho (vol), sake dipper, dots and cross radical (no. 68)" },
  { kanji: "斜", onyomi: "しゃ", kunyomi: "なな（め）", meaning: "diagonal, slanting, oblique" },
  { kanji: "斤", onyomi: "きん", kunyomi: "", meaning: "axe, 1.32 lb, catty, counter for loaves of bread" },
  { kanji: "斥", onyomi: "せき", kunyomi: "", meaning: "reject, retreat, recede, withdraw, repel, repulse" },
  { kanji: "於", onyomi: "お", kunyomi: "おい（て）", meaning: "at, in, on, as for" },
  { kanji: "施", onyomi: "し、せ", kunyomi: "ほどこ（す）", meaning: "give, bestow, perform, alms" },
  { kanji: "旋", onyomi: "せん", kunyomi: "", meaning: "rotation, go around" },
  { kanji: "旗", onyomi: "き", kunyomi: "はた", meaning: "national flag, banner, standard" },
  { kanji: "旦", onyomi: "たん、だん", kunyomi: "", meaning: "daybreak, dawn, morning" },
  { kanji: "旨", onyomi: "し", kunyomi: "むね", meaning: "purport, gist, elegance, interest, proceed to, tend, become" },
  { kanji: "旬", onyomi: "じゅん、しゅん", kunyomi: "", meaning: "decameron, 10-day period, season (for specific products)" },
  { kanji: "旭", onyomi: "きょく", kunyomi: "あさひ", meaning: "rising sun, morning sun" },
  { kanji: "旺", onyomi: "おう", kunyomi: "", meaning: "flourishing, successful, beautiful, vigorous" },
  { kanji: "昂", onyomi: "こう", kunyomi: "", meaning: "rise" },
  { kanji: "昆", onyomi: "こん", kunyomi: "", meaning: "insect, bug" },
  { kanji: "昌", onyomi: "しょう", kunyomi: "", meaning: "prosperous, bright, clear" },
  { kanji: "昭", onyomi: "しょう", kunyomi: "", meaning: "shining, bright" },
  { kanji: "是", onyomi: "ぜ", kunyomi: "これ", meaning: "just so, this, right, justice" },
  { kanji: "昴", onyomi: "ぼう", kunyomi: "", meaning: "the Pleiades (star cluster)" },
  { kanji: "晃", onyomi: "こう", kunyomi: "", meaning: "clear" },
  { kanji: "晋", onyomi: "しん", kunyomi: "", meaning: "advance" },
  { kanji: "晏", onyomi: "あん", kunyomi: "", meaning: "late, quiet" },
  { kanji: "晟", onyomi: "せい", kunyomi: "", meaning: "clear" },
  { kanji: "晨", onyomi: "しん", kunyomi: "", meaning: "morning" },
  { kanji: "晶", onyomi: "しょう", kunyomi: "", meaning: "sparkle, clear, crystal" },
  { kanji: "智", onyomi: "ち", kunyomi: "", meaning: "wisdom, intellect, reason" },
  { kanji: "暁", onyomi: "ぎょう", kunyomi: "あかつき", meaning: "daybreak, dawn, in the event" },
  { kanji: "暇", onyomi: "か", kunyomi: "ひま", meaning: "spare time, rest, leisure, time, leave of absence" },
  { kanji: "暉", onyomi: "き", kunyomi: "", meaning: "shine, light" },
  { kanji: "暢", onyomi: "ちょう", kunyomi: "", meaning: "stretch" },
  { kanji: "暦", onyomi: "れき", kunyomi: "こよみ", meaning: "calendar, almanac" },
  { kanji: "暫", onyomi: "ざん", kunyomi: "しばら（く）", meaning: "temporarily, a while, moment, long time" },
  { kanji: "曙", onyomi: "しょ", kunyomi: "あけぼの", meaning: "dawn, daybreak" },
  { kanji: "曹", onyomi: "そう", kunyomi: "", meaning: "officer, an official" },
  { kanji: "朋", onyomi: "ほう", kunyomi: "とも", meaning: "companion, friend" },
  { kanji: "朔", onyomi: "さく", kunyomi: "", meaning: "conjunction (astronomy), first day of month" },
  { kanji: "朕", onyomi: "ちん", kunyomi: "", meaning: "We, imperial sign" },
  { kanji: "朗", onyomi: "ろう", kunyomi: "ほが（らか）", meaning: "melodious, clear, bright, serene, cheerful" },
  { kanji: "朱", onyomi: "しゅ", kunyomi: "", meaning: "vermilion, cinnabar, scarlet, red, bloody" },
  { kanji: "朴", onyomi: "ぼく", kunyomi: "", meaning: "simple, unadorned, wooden, obedient, be (kindhearted)" },
  { kanji: "朽", onyomi: "きゅう", kunyomi: "く（ちる）", meaning: "decay, rot, remain in seclusion" },
  { kanji: "杉", onyomi: "さん", kunyomi: "すぎ", meaning: "cedar, cryptomeria" },
  { kanji: "李", onyomi: "り", kunyomi: "すもも", meaning: "plum" },
  { kanji: "杏", onyomi: "きょう、あん", kunyomi: "あんず", meaning: "apricot" },
  { kanji: "杜", onyomi: "と、ず", kunyomi: "もり", meaning: "woods, grove" },
  { kanji: "松", onyomi: "しょう", kunyomi: "まつ", meaning: "pine tree" },
  { kanji: "枠", onyomi: "", kunyomi: "わく", meaning: "frame, framework, spindle, spool, bounding-box, (kokuji)" },
  { kanji: "枢", onyomi: "すう", kunyomi: "", meaning: "hinge, pivot, door" },
  { kanji: "架", onyomi: "か", kunyomi: "か（ける）", meaning: "erect, frame, mount, support, shelf, construct" },
  { kanji: "柄", onyomi: "へい", kunyomi: "がら、え", meaning: "design, pattern, build, nature, character, handle, crank, grip, knob, shaft" },
  { kanji: "柊", onyomi: "しゅう", kunyomi: "ひいらぎ", meaning: "holly" },
  { kanji: "某", onyomi: "ぼう", kunyomi: "", meaning: "so-and-so, one, a certain, that person" },
  { kanji: "染", onyomi: "せん", kunyomi: "そ（める）、し（みる）", meaning: "dye, color, paint, stain, print" },
  { kanji: "柚", onyomi: "ゆう、ゆ", kunyomi: "ゆず", meaning: "citron" },
  { kanji: "柳", onyomi: "りゅう", kunyomi: "やなぎ", meaning: "willow" },
  { kanji: "柾", onyomi: "せい", kunyomi: "まさ", meaning: "straight grain, spindle tree, (kokuji)" },
  { kanji: "栓", onyomi: "せん", kunyomi: "", meaning: "plug, bolt, cork, bung, stopper" },
  { kanji: "栗", onyomi: "りつ", kunyomi: "くり", meaning: "chestnut" },
  { kanji: "栞", onyomi: "かん", kunyomi: "しおり", meaning: "bookmark, guidebook" },
  { kanji: "核", onyomi: "かく", kunyomi: "", meaning: "nucleus, core, kernel" },
  { kanji: "栽", onyomi: "さい", kunyomi: "", meaning: "plantation, planting" },
  { kanji: "桂", onyomi: "けい", kunyomi: "かつら", meaning: "Japanese Judas-tree, cinnamon tree" },
  { kanji: "桃", onyomi: "とう", kunyomi: "もも", meaning: "peach" },
  { kanji: "桐", onyomi: "とう、どう", kunyomi: "きり", meaning: "paulownia" },
  { kanji: "桑", onyomi: "そう", kunyomi: "くわ", meaning: "mulberry" },
  { kanji: "桜", onyomi: "おう", kunyomi: "さくら", meaning: "cherry" },
  { kanji: "桟", onyomi: "さん、せん", kunyomi: "", meaning: "scaffold, cleat, frame, jetty, bolt (door)" },
  { kanji: "梅", onyomi: "ばい", kunyomi: "うめ", meaning: "plum" },
  { kanji: "梓", onyomi: "し", kunyomi: "あずさ", meaning: "catalpa tree" },
  { kanji: "梢", onyomi: "しょう", kunyomi: "こずえ", meaning: "treetops, twig" },
  { kanji: "梧", onyomi: "ご", kunyomi: "", meaning: "Chinese parasol tree, phoenix tree" },
  { kanji: "梨", onyomi: "り", kunyomi: "なし", meaning: "pear" },
  { kanji: "棄", onyomi: "き", kunyomi: "す（てる）", meaning: "abandon, throw away, discard, resign, reject, sacrifice" },
  { kanji: "棋", onyomi: "き", kunyomi: "", meaning: "chess piece, Japanese chess, shogi" },
  { kanji: "棚", onyomi: "ほう", kunyomi: "たな", meaning: "shelf, ledge, rack, mount, mantle, trellis" },
  { kanji: "棟", onyomi: "とう", kunyomi: "むね、むな", meaning: "ridgepole, ridge" },
  { kanji: "棺", onyomi: "かん", kunyomi: "", meaning: "coffin, casket" },
  { kanji: "椋", onyomi: "りょう", kunyomi: "むく", meaning: "type of deciduous tree, grey starling" },
  { kanji: "椎", onyomi: "つい", kunyomi: "しい", meaning: "oak, mallet" },
  { kanji: "椰", onyomi: "や", kunyomi: "", meaning: "coconut tree" },
  { kanji: "椿", onyomi: "ちん", kunyomi: "つばき", meaning: "camellia" },
  { kanji: "楊", onyomi: "よう", kunyomi: "", meaning: "willow" },
  { kanji: "楓", onyomi: "ふう", kunyomi: "かえで", meaning: "maple" },
  { kanji: "楠", onyomi: "なん", kunyomi: "くす", meaning: "camphor tree" },
  { kanji: "楼", onyomi: "ろう", kunyomi: "", meaning: "watchtower, lookout, high building" },
  { kanji: "概", onyomi: "がい", kunyomi: "", meaning: "outline, condition, approximation, generally" },
  { kanji: "榛", onyomi: "しん", kunyomi: "はしばみ", meaning: "hazel, filbert" },
  { kanji: "槙", onyomi: "てん", kunyomi: "まき", meaning: "twig, ornamental evergreen" },
  { kanji: "槻", onyomi: "き", kunyomi: "つき", meaning: "Zelkova tree" },
  { kanji: "槽", onyomi: "そう", kunyomi: "", meaning: "vat, tub, tank" },
  { kanji: "模", onyomi: "も、ぼ", kunyomi: "", meaning: "imitation, copy, mock" },
  { kanji: "樹", onyomi: "じゅ", kunyomi: "き", meaning: "timber, trees, wood, establish, set up" },
  { kanji: "樺", onyomi: "か", kunyomi: "かば", meaning: "birch, dark red" },
  { kanji: "橘", onyomi: "きつ", kunyomi: "たちばな", meaning: "mandarin orange" },
  { kanji: "檀", onyomi: "だん、たん", kunyomi: "", meaning: "cedar, sandalwood, spindle tree" },
  { kanji: "欄", onyomi: "らん", kunyomi: "", meaning: "column, handrail, blank, space" },
  { kanji: "欣", onyomi: "きん、ごん", kunyomi: "", meaning: "take pleasure in, rejoice" },
  { kanji: "欺", onyomi: "ぎ", kunyomi: "あざむ（く）", meaning: "deceit, cheat, delude" },
  { kanji: "欽", onyomi: "きん", kunyomi: "", meaning: "respect, revere, long for" },
  { kanji: "款", onyomi: "かん", kunyomi: "", meaning: "goodwill, article, section, friendship, collusion" },
  { kanji: "歓", onyomi: "かん", kunyomi: "よろこ（ぶ）", meaning: "delight, joy" },
  { kanji: "殉", onyomi: "じゅん", kunyomi: "", meaning: "martyrdom, follow by resigning" },
  { kanji: "殊", onyomi: "しゅ", kunyomi: "こと", meaning: "particularly, especially, exceptionally" },
  { kanji: "殖", onyomi: "しょく", kunyomi: "ふ（える）", meaning: "augment, increase, multiply, raise" },
  { kanji: "殴", onyomi: "おう", kunyomi: "なぐ（る）", meaning: "assault, hit, beat, thrash" },
  { kanji: "殻", onyomi: "かく", kunyomi: "から", meaning: "husk, nut shell" },
  { kanji: "毅", onyomi: "き", kunyomi: "", meaning: "strong" },
  { kanji: "毬", onyomi: "きゅう", kunyomi: "いが、まり", meaning: "burr, ball" },
  { kanji: "氏", onyomi: "し", kunyomi: "うじ", meaning: "family name, surname, clan" },
  { kanji: "汀", onyomi: "てい", kunyomi: "みぎわ", meaning: "water's edge, shore, bank" },
  { kanji: "汁", onyomi: "じゅう", kunyomi: "しる", meaning: "soup, juice, broth, sap, gravy, pus" },
  { kanji: "汐", onyomi: "せき", kunyomi: "うしお", meaning: "eventide, tide, salt water, opportunity" },
  { kanji: "汰", onyomi: "た", kunyomi: "", meaning: "luxury, select" },
  { kanji: "汽", onyomi: "き", kunyomi: "", meaning: "steam, vapor" },
  { kanji: "沖", onyomi: "ちゅう", kunyomi: "おき", meaning: "open sea, offing, pelagic" },
  { kanji: "沙", onyomi: "さ、しゃ", kunyomi: "すな", meaning: "sand" },
  { kanji: "没", onyomi: "ぼつ", kunyomi: "", meaning: "drown, sink, hide, fall into, disappear, die" },
  { kanji: "沢", onyomi: "たく", kunyomi: "さわ", meaning: "swamp, marsh, brilliance, grace" },
  { kanji: "沼", onyomi: "しょう", kunyomi: "ぬま", meaning: "marsh, lake, bog, swamp, pond" },
  { kanji: "泌", onyomi: "ひ、ひつ", kunyomi: "", meaning: "ooze, flow, soak through, secrete" },
  { kanji: "泡", onyomi: "ほう", kunyomi: "あわ", meaning: "bubbles, foam, suds, froth" },
  { kanji: "泰", onyomi: "たい", kunyomi: "", meaning: "peaceful, calm, peace, easy, Thailand, extreme, excessive, great" },
  { kanji: "洞", onyomi: "どう", kunyomi: "ほら", meaning: "den, cave, excavation" },
  { kanji: "津", onyomi: "しん", kunyomi: "つ", meaning: "haven, port, harbor, ferry" },
  { kanji: "洪", onyomi: "こう", kunyomi: "", meaning: "deluge, flood, vast" },
  { kanji: "洲", onyomi: "しゅう", kunyomi: "す", meaning: "continent, sandbar, island, country" },
  { kanji: "洵", onyomi: "じゅん", kunyomi: "", meaning: "alike, truth" },
  { kanji: "洸", onyomi: "こう", kunyomi: "", meaning: "sparkling water" },
  { kanji: "浄", onyomi: "じょう", kunyomi: "", meaning: "clean, purify, cleanse, exorcise, Amida Buddha" },
  { kanji: "浜", onyomi: "ひん", kunyomi: "はま", meaning: "seacoast, beach, seashore" },
  { kanji: "浦", onyomi: "ほ", kunyomi: "うら", meaning: "bay, creek, inlet, gulf, beach, seacoast" },
  { kanji: "浩", onyomi: "こう", kunyomi: "", meaning: "wide expanse, abundance, vigorous" },
  { kanji: "浪", onyomi: "ろう", kunyomi: "なみ", meaning: "wandering, waves, billows" },
  { kanji: "浸", onyomi: "しん", kunyomi: "ひた（す）", meaning: "immerse, soak, dip, steep, moisten, wet, dunk" },
  { kanji: "涯", onyomi: "がい", kunyomi: "", meaning: "horizon, shore, limit, bound" },
  { kanji: "淑", onyomi: "しゅく", kunyomi: "", meaning: "graceful, gentle, pure" },
  { kanji: "淡", onyomi: "たん", kunyomi: "あわ（い）", meaning: "thin, faint, pale, fleeting" },
  { kanji: "淳", onyomi: "ジュン", kunyomi: "あつ.い", meaning: "pure, innocent, kind, sincere" },
  { kanji: "添", onyomi: "テン", kunyomi: "そ.える, そ.う", meaning: "annexed, accompany, marry, suit, meet, satisfy, attach, append, garnish, imitate" },
  { kanji: "渇", onyomi: "かつ", kunyomi: "", meaning: "thirst" },
  { kanji: "渉", onyomi: "ショウ", kunyomi: "わた.る", meaning: "ford, go across, transit, ferry, import, involve" },
  { kanji: "渋", onyomi: "しぶ", kunyomi: "", meaning: "kakishibu, astringent persimmon juice used as a dye or to treat wood, paper, etc." },
  { kanji: "渓", onyomi: "たに", kunyomi: "", meaning: "valley, ravine, gorge" },
  { kanji: "渚", onyomi: "なぎさ", kunyomi: "", meaning: "water's edge, beach, shore" },
  { kanji: "渥", onyomi: "アク", kunyomi: "あつ（い）", meaning: "kindness, gracious, cordial" },
  { kanji: "渦", onyomi: "うず", kunyomi: "", meaning: "whirlpool, swirl, eddy" },
  { kanji: "湧", onyomi: "ユウ", kunyomi: "わ.く, わ.かす", meaning: "boil, gush forth, well up, bubble up" },
  { kanji: "滋", onyomi: "ジ", kunyomi: "しげ.る", meaning: "nourishing, nutritious, fertile" },
  { kanji: "滞", onyomi: "タイ", kunyomi: "とどこお.る", meaning: "stagnate, be delayed, overdue, arrears" },
  { kanji: "源", onyomi: "みなもと", kunyomi: "", meaning: "source (of a river), fountainhead, source" },
  { kanji: "溝", onyomi: "みぞ", kunyomi: "", meaning: "ditch, drain, gutter" },
  { kanji: "滅", onyomi: "メツ", kunyomi: "ほろ.びる, ほろ.ぼす", meaning: "destroy, ruin, overthrow, perish" },
  { kanji: "滉", onyomi: "コウ", kunyomi: "", meaning: "deep and broad (of water), vast" },
  { kanji: "滝", onyomi: "たき", kunyomi: "", meaning: "waterfall, rapids, Waterfall" },
  { kanji: "漂", onyomi: "ヒョウ", kunyomi: "ただよ（う）", meaning: "drift, float, waft" },
  { kanji: "漆", onyomi: "しち", kunyomi: "", meaning: "seven" },
  { kanji: "漠", onyomi: "ばく", kunyomi: "", meaning: "vague, obscure, vast" },
  { kanji: "漫", onyomi: "マン、バン", kunyomi: "みだ（りに）、そぞ（ろに）", meaning: "comic, manga, unrestrained, aimless" },
  { kanji: "漱", onyomi: "うがい", kunyomi: "", meaning: "gargling, rinsing one's mouth" },
  { kanji: "漸", onyomi: "やや", kunyomi: "", meaning: "a little, partially, somewhat" },
  { kanji: "潔", onyomi: "ケツ", kunyomi: "いさぎよ（い）", meaning: "purity, cleanliness, honesty, undefiled" },
  { kanji: "潜", onyomi: "セン", kunyomi: "ひそ（む）、もぐ（る）、かく（れる）", meaning: "submerge, conceal, hide, lower" },
  { kanji: "潟", onyomi: "かた", kunyomi: "", meaning: "lagoon, inlet, creek" },
  { kanji: "潤", onyomi: "ジュン", kunyomi: "うるお（う）、うるお（す）", meaning: "moist, wet, profit, favor, charm" },
  { kanji: "潮", onyomi: "しお", kunyomi: "", meaning: "tide, current, sea water" },
  { kanji: "澄", onyomi: "チョウ", kunyomi: "す（む）、す（ます）", meaning: "clear, lucid, serene, transparent" },
  { kanji: "澪", onyomi: "みお", kunyomi: "", meaning: "waterway, channel, wake (of a ship)" },
  { kanji: "激", onyomi: "げき", kunyomi: "", meaning: "extremely, terrifically, super" },
  { kanji: "濁", onyomi: "ダク", kunyomi: "にご.る, にご.す", meaning: "voiced, uncleanness, wrong, nigori, impurity" },
  { kanji: "濫", onyomi: "ラン", kunyomi: "みだ.りに", meaning: "excessive, overflow, spread out" },
  { kanji: "瀬", onyomi: "せ", kunyomi: "", meaning: "shallows, shoal, rapids" },
  { kanji: "炉", onyomi: "ろ", kunyomi: "", meaning: "hearth, fireplace, furnace" },
  { kanji: "炊", onyomi: "スイ", kunyomi: "た（く）", meaning: "cook, boil, steam" },
  { kanji: "炎", onyomi: "ほのお", kunyomi: "", meaning: "flame, blaze, flames (of intense emotion, e.g. love, jealousy, anger)" },
  { kanji: "為", onyomi: "ため", kunyomi: "", meaning: "good, advantage, benefit" },
  { kanji: "烈", onyomi: "レツ", kunyomi: "はげ.しい", meaning: "ardent, violent, vehement, furious, severe, extreme" },
  { kanji: "焦", onyomi: "ショウ", kunyomi: "こ.げる, こ.がす, あせ.る", meaning: "char, hurry, impatient, irritate, burn, scorch, singe" },
  { kanji: "煮", onyomi: "に", kunyomi: "", meaning: "simmered with, cooked with, boiling" },
  { kanji: "煩", onyomi: "はん", kunyomi: "", meaning: "trouble" },
  { kanji: "熊", onyomi: "くま", kunyomi: "", meaning: "bear (any mammal of family Ursidae)" },
  { kanji: "熙", onyomi: "キ", kunyomi: "", meaning: "shine, light, bright, radiance" },
  { kanji: "熟", onyomi: "つくづく", kunyomi: "", meaning: "deeply, keenly, severely" },
  { kanji: "黙", onyomi: "モク", kunyomi: "だま.る", meaning: "silence, become silent, stop speaking, leave as is" },
  { kanji: "燎", onyomi: "リョウ", kunyomi: "かがり", meaning: "burn, blaze" },
  { kanji: "燦", onyomi: "さん", kunyomi: "", meaning: "brilliant, resplendent" },
  { kanji: "燿", onyomi: "ヨウ", kunyomi: "かがや（く）", meaning: "radiance, brilliance, splendor" },
  { kanji: "爵", onyomi: "しゃく", kunyomi: "", meaning: "jue (ancient 3-legged Chinese wine pitcher, usu. made of bronze), peerage (hereditary title bestowed by the emperor)" },
  { kanji: "爽", onyomi: "ソウ", kunyomi: "さわ（やか）、あき（らか）", meaning: "refreshing, exhilarating, clear, fresh" },
  { kanji: "爾", onyomi: "なんじ", kunyomi: "", meaning: "thou, you" },
  { kanji: "牧", onyomi: "まき", kunyomi: "", meaning: "pasture, grazing land" },
  { kanji: "牲", onyomi: "にえ", kunyomi: "", meaning: "offering (to the gods, emperor, etc.), gift, sacrifice" },
  { kanji: "犠", onyomi: "ギ、キ", kunyomi: "いけにえ", meaning: "sacrifice, victim" },
  { kanji: "狂", onyomi: "きょう", kunyomi: "", meaning: "(some type of) enthusiast, someone possessed of a (certain kind of) mental abnormality" },
  { kanji: "狩", onyomi: "シュ", kunyomi: "か（る）、かり", meaning: "hunt, chase, pursue" },
  { kanji: "猛", onyomi: "もう", kunyomi: "", meaning: "greatly energetic, ferocious, extreme" },
  { kanji: "猟", onyomi: "りょう", kunyomi: "", meaning: "hunting, shooting, game" },
  { kanji: "猪", onyomi: "いのしし", kunyomi: "", meaning: "wild boar, wild pig, Wild boar" },
  { kanji: "献", onyomi: "ケン、コン", kunyomi: "たてまつ（る）", meaning: "dedication, offer, contribute, present" },
  { kanji: "猶", onyomi: "なお", kunyomi: "", meaning: "still, yet, more" },
  { kanji: "猿", onyomi: "さる", kunyomi: "", meaning: "monkey (esp. the Japanese macaque, Macaca fuscata), ape, non-human primate" },
  { kanji: "獲", onyomi: "カク", kunyomi: "え（る）", meaning: "acquire, catch, obtain" },
  { kanji: "玄", onyomi: "ゲン", kunyomi: "くろ、つね", meaning: "mysterious, profound, dark" },
  { kanji: "玖", onyomi: "きゅう", kunyomi: "", meaning: "nine, 9" },
  { kanji: "玲", onyomi: "レイ", kunyomi: "", meaning: "sound of jewels, tinkling sound" },
  { kanji: "珠", onyomi: "たま", kunyomi: "", meaning: "ball, sphere, globe" },
  { kanji: "班", onyomi: "はん", kunyomi: "", meaning: "group, party, team" },
  { kanji: "琉", onyomi: "リュウ", kunyomi: "", meaning: "precious stone, gem, lapis lazuli" },
  { kanji: "琢", onyomi: "タク", kunyomi: "みが.く", meaning: "polish, shine, improve, refine" },
  { kanji: "琳", onyomi: "リン", kunyomi: "", meaning: "beautiful gem, beautiful jade" },
  { kanji: "琴", onyomi: "こと", kunyomi: "", meaning: "koto (13-stringed Japanese zither), stringed instrument, zheng (Chinese zither)" },
  { kanji: "瑚", onyomi: "コ、ゴ", kunyomi: "", meaning: "coral" },
  { kanji: "瑛", onyomi: "エイ", kunyomi: "", meaning: "sparkle of jewelry, crystal" },
  { kanji: "瑞", onyomi: "ずい", kunyomi: "", meaning: "Sweden, Switzerland" },
  { kanji: "瑠", onyomi: "ル", kunyomi: "", meaning: "lapis lazuli" },
  { kanji: "瑳", onyomi: "サ", kunyomi: "", meaning: "polish, grind, scour, buff, burnish" },
  { kanji: "瑶", onyomi: "ヨウ", kunyomi: "", meaning: "beautiful jade" },
  { kanji: "璃", onyomi: "リ", kunyomi: "", meaning: "glassy, lapis lazuli" },
  { kanji: "璽", onyomi: "じ", kunyomi: "", meaning: "emperor's seal" },
  { kanji: "甚", onyomi: "ジン", kunyomi: "はなは（だ）", meaning: "very, extremely, greatly" },
  { kanji: "甫", onyomi: "ホ、フ", kunyomi: "はじ（め）", meaning: "beginning, for the first time, just" },
  { kanji: "甲", onyomi: "よろい", kunyomi: "", meaning: "armor, armour, Yoroi" },
  { kanji: "畔", onyomi: "ハン", kunyomi: "あぜ、くろ", meaning: "bank, edge, shore, ridge between fields" },
  { kanji: "畝", onyomi: "うね", kunyomi: "", meaning: "ridge (in field), row of raised earth when planting crops, rib (cloth, mountains, sea)" },
  { kanji: "疎", onyomi: "おろ", kunyomi: "", meaning: "incompletely, insufficiently, partially" },
  { kanji: "疫", onyomi: "エキ、ヤク", kunyomi: "", meaning: "epidemic, plague, pestilence" },
  { kanji: "疾", onyomi: "シツ", kunyomi: "やま（い）、はや（い）", meaning: "disease, swift, fast" },
  { kanji: "症", onyomi: "しょう", kunyomi: "", meaning: "illness, condition, -pathy" },
  { kanji: "痘", onyomi: "いも", kunyomi: "", meaning: "smallpox, pockmark" },
  { kanji: "痢", onyomi: "り", kunyomi: "", meaning: "diarrhea, diarrhoea" },
  { kanji: "痴", onyomi: "おこ", kunyomi: "", meaning: "foolish thing, stupid thing, absurdity" },
  { kanji: "癒", onyomi: "ユ", kunyomi: "い（やす）、い（える）", meaning: "heal, cure, soothe" },
  { kanji: "癖", onyomi: "くせ", kunyomi: "", meaning: "habit (usu. a bad one), tendency, peculiarity" },
  { kanji: "皇", onyomi: "すめ", kunyomi: "", meaning: "divine, imperial" },
  { kanji: "皐", onyomi: "コウ", kunyomi: "", meaning: "swamp, shore" },
  { kanji: "皓", onyomi: "コウ", kunyomi: "しろ.い", meaning: "white, clear" },
  { kanji: "盆", onyomi: "ぼん", kunyomi: "", meaning: "tray, family, household" },
  { kanji: "益", onyomi: "えき", kunyomi: "", meaning: "benefit, use, good" },
  { kanji: "盟", onyomi: "めい", kunyomi: "", meaning: "alliance, aimag, league" },
  { kanji: "監", onyomi: "げん", kunyomi: "", meaning: "special Nara-period administrative division for areas containing a detached palace (Yoshino and Izumi), secretary, third highest-ranking officials in the Dazaifu" },
  { kanji: "盤", onyomi: "さら", kunyomi: "", meaning: "plate, dish, platter" },
  { kanji: "盲", onyomi: "めくら", kunyomi: "", meaning: "blindness, blind person, illiteracy" },
  { kanji: "盾", onyomi: "たて", kunyomi: "", meaning: "shield, buckler, escutcheon" },
  { kanji: "眉", onyomi: "まゆ", kunyomi: "", meaning: "eyebrow, eyebrows" },
  { kanji: "眸", onyomi: "ひとみ", kunyomi: "", meaning: "pupil (of the eye), one's eyes" },
  { kanji: "眺", onyomi: "チョウ", kunyomi: "なが（める）", meaning: "stare, watch, look at, see" },
  { kanji: "眼", onyomi: "め", kunyomi: "", meaning: "eye, eyeball, eyesight" },
  { kanji: "督", onyomi: "トク", kunyomi: "", meaning: "supervise, coach, urge, encourage, command" },
  { kanji: "睦", onyomi: "ボク", kunyomi: "むつ.まじい, むつ.む", meaning: "intimate, friendly, harmonious" },
  { kanji: "睡", onyomi: "スイ", kunyomi: "", meaning: "drowsy, sleep, die" },
  { kanji: "瞬", onyomi: "シュン", kunyomi: "まばた.く", meaning: "wink, blink, twinkle" },
  { kanji: "瞭", onyomi: "リョウ", kunyomi: "", meaning: "clear" },
  { kanji: "瞳", onyomi: "ひとみ", kunyomi: "", meaning: "pupil (of the eye), one's eyes" },
  { kanji: "矛", onyomi: "ほこ", kunyomi: "", meaning: "long-handled Chinese spear, lance, pike" },
  { kanji: "矢", onyomi: "や", kunyomi: "", meaning: "arrow, wedge, chock" },
  { kanji: "矩", onyomi: "ク", kunyomi: "のり, さしがね", meaning: "ruler, carpenter's square" },
  { kanji: "矯", onyomi: "キョウ", kunyomi: "た.める", meaning: "correct, cure, straighten, reform, remedy" },
  { kanji: "砕", onyomi: "サイ", kunyomi: "くだ.く, くだ.ける", meaning: "smash, break, crush, familiar, popular" },
  { kanji: "硝", onyomi: "ショウ", kunyomi: "", meaning: "nitrate" },
  { kanji: "硫", onyomi: "イオウ", kunyomi: "", meaning: "sulfur" },
  { kanji: "碁", onyomi: "ご", kunyomi: "", meaning: "go (board game)" },
  { kanji: "碑", onyomi: "いしぶみ", kunyomi: "", meaning: "stone monument bearing an inscription (esp. memorial for future generations), stele, stela" },
  { kanji: "碧", onyomi: "あお", kunyomi: "", meaning: "blue, azure, green" },
  { kanji: "碩", onyomi: "セキ", kunyomi: "", meaning: "large (stone), doctoral degree" },
  { kanji: "磯", onyomi: "いそ", kunyomi: "", meaning: "(rocky) beach, seashore" },
  { kanji: "礁", onyomi: "しょう", kunyomi: "", meaning: "reef" },
  { kanji: "祉", onyomi: "シ", kunyomi: "", meaning: "welfare, happiness" },
  { kanji: "祐", onyomi: "ユウ", kunyomi: "たす.ける", meaning: "help, assist" },
  { kanji: "祥", onyomi: "しょう", kunyomi: "", meaning: "omen (usu. good), (auspicious) sign, first two anniversaries of a person's death" },
  { kanji: "禄", onyomi: "ろく", kunyomi: "", meaning: "stipend, reward" },
  { kanji: "禅", onyomi: "ぜん", kunyomi: "", meaning: "dhyana (profound meditation), Zen (Buddhism), Zen" },
  { kanji: "禍", onyomi: "わざわい", kunyomi: "", meaning: "disaster, calamity, misfortune" },
  { kanji: "禎", onyomi: "テイ", kunyomi: "さいわ（い）", meaning: "blessed, auspicious, good fortune" },
  { kanji: "秀", onyomi: "しゅう", kunyomi: "", meaning: "preeminence, supremacy, distinction" },
  { kanji: "租", onyomi: "そ", kunyomi: "", meaning: "rice tax (ritsuryō system), rice levy, tax on rice fields" },
  { kanji: "秦", onyomi: "しん", kunyomi: "", meaning: "Qin dynasty (of China; 221-207 BCE), Ch'in dynasty, Qin (state)" },
  { kanji: "秩", onyomi: "チツ", kunyomi: "", meaning: "order, sequence, procedure" },
  { kanji: "称", onyomi: "しょう", kunyomi: "", meaning: "name, title, designation" },
  { kanji: "稀", onyomi: "まれ", kunyomi: "", meaning: "rare, seldom" },
  { kanji: "稔", onyomi: "ネン", kunyomi: "みの.る", meaning: "harvest, ripen" },
  { kanji: "稚", onyomi: "チ", kunyomi: "おち.る, いとけな.い", meaning: "immature, young" },
  { kanji: "稜", onyomi: "りょう", kunyomi: "", meaning: "edge, angle, ridge (e.g. of a mountain)" },
  { kanji: "稲", onyomi: "いね", kunyomi: "", meaning: "rice plant (Oryza sativa)" },
  { kanji: "稼", onyomi: "カ", kunyomi: "かせ.ぐ", meaning: "earnings, work, make money" },
  { kanji: "稿", onyomi: "こう", kunyomi: "", meaning: "manuscript, version, draft" },
  { kanji: "穀", onyomi: "コク", kunyomi: "", meaning: "cereal, grain" },
  { kanji: "穂", onyomi: "ほ", kunyomi: "", meaning: "ear (of a cereal plant), head, spike" },
  { kanji: "穏", onyomi: "オン", kunyomi: "おだ.やか", meaning: "calm, quiet, moderation" },
  { kanji: "穣", onyomi: "じょう", kunyomi: "", meaning: "10^28, ten octillion" },
  { kanji: "穫", onyomi: "カク", kunyomi: "", meaning: "harvest, reap" },
  { kanji: "窃", onyomi: "セツ", kunyomi: "ぬす.む, ひそ.か", meaning: "stealth, steal, secret, private, hushed" },
  { kanji: "窒", onyomi: "チツ", kunyomi: "", meaning: "nitrogen" },
  { kanji: "窮", onyomi: "キュウグ", kunyomi: "きわ.まる, きわ.める", meaning: "hard up, destitute, suffer, perplexed, cornered" },
  { kanji: "窯", onyomi: "かま", kunyomi: "", meaning: "stove, furnace, kiln" },
  { kanji: "竜", onyomi: "リュウ", kunyomi: "たつ", meaning: "dragon, imperial" },
  { kanji: "竣", onyomi: "シュン", kunyomi: "", meaning: "complete, finish" },
  { kanji: "笙", onyomi: "しょう", kunyomi: "", meaning: "traditional Japanese wind instrument resembling panpipes, free-reed instrument used in Japanese court music, Shō (instrument)" },
  { kanji: "笛", onyomi: "ふえ", kunyomi: "", meaning: "flute, fife, pipe" },
  { kanji: "笹", onyomi: "ササ", kunyomi: "", meaning: "bamboo grass" },
  { kanji: "箇", onyomi: "か", kunyomi: "", meaning: "counter used with Sino-Japanese words, Mosquito" },
  { kanji: "篤", onyomi: "トク", kunyomi: "あつ（い）", meaning: "sincerity, seriousness, diligence, devoted" },
  { kanji: "簿", onyomi: "ぼ", kunyomi: "", meaning: "register, record book" },
  { kanji: "籍", onyomi: "せき", kunyomi: "", meaning: "one's family register, one's domicile, nationality" },
  { kanji: "粋", onyomi: "いき", kunyomi: "", meaning: "chic, smart, stylish" },
  { kanji: "粗", onyomi: "ほぼ", kunyomi: "", meaning: "almost, roughly, approximately" },
  { kanji: "粘", onyomi: "ねば", kunyomi: "", meaning: "stickiness, gumminess, sticky material" },
  { kanji: "粛", onyomi: "しゅく", kunyomi: "", meaning: "solemn, respectful, reverent" },
  { kanji: "粧", onyomi: "ショウ", kunyomi: "よそお.う", meaning: "cosmetics, adorn (one's person)" },
  { kanji: "糧", onyomi: "かて", kunyomi: "", meaning: "food, provisions, nourishment (mental, spiritual, etc.)" },
  { kanji: "系", onyomi: "けい", kunyomi: "", meaning: "system, lineage, group" },
  { kanji: "糾", onyomi: "キュウ", kunyomi: "ただ（す）", meaning: "twist, correct, investigate, verify" },
  { kanji: "紋", onyomi: "もん", kunyomi: "", meaning: "(family) crest, coat of arms, pattern" },
  { kanji: "納", onyomi: "ノウ", kunyomi: "おさ.める, おさ.まる", meaning: "settlement, obtain, reap, pay, supply, store" },
  { kanji: "紗", onyomi: "しゃ", kunyomi: "", meaning: "(silk) gauze" },
  { kanji: "紘", onyomi: "コウ", kunyomi: "", meaning: "large" },
  { kanji: "紛", onyomi: "フン", kunyomi: "まぎ.れる, まぎ.らわしい", meaning: "distract, be mistaken for, go astray, divert" },
  { kanji: "素", onyomi: "もと", kunyomi: "", meaning: "origin, source, beginning" },
  { kanji: "紡", onyomi: "ボウ", kunyomi: "つむ（ぐ）", meaning: "spin, spin yarn, make yarn" },
  { kanji: "紫", onyomi: "むらさき", kunyomi: "", meaning: "purple, violet, purple gromwell (Lithospermum erythrorhizon)" },
  { kanji: "紬", onyomi: "つむぎ", kunyomi: "", meaning: "tsumugi, pongee, traditional rough-surfaced cloth woven from raw silk" },
  { kanji: "累", onyomi: "るい", kunyomi: "", meaning: "trouble, harmful effect, evil influence" },
  { kanji: "紳", onyomi: "シン", kunyomi: "", meaning: "gentleman, samurai, samurai radical (no. 125)" },
  { kanji: "紺", onyomi: "こん", kunyomi: "", meaning: "navy blue, deep blue" },
  { kanji: "絃", onyomi: "つる", kunyomi: "", meaning: "bowstring, string (of shamisen, guitar, violin, etc.), bail (arched pot handle)" },
  { kanji: "絞", onyomi: "こう", kunyomi: "", meaning: "death by hanging (punishment in the ritsuryō system)" },
  { kanji: "絢", onyomi: "ケン", kunyomi: "あや", meaning: "gorgeous, brilliant, colorful, beautiful pattern" },
  { kanji: "絹", onyomi: "きぬ", kunyomi: "", meaning: "silk, Silk" },
  { kanji: "綜", onyomi: "あぜ", kunyomi: "", meaning: "warp controller (on a loom)" },
  { kanji: "綱", onyomi: "つな", kunyomi: "", meaning: "rope, cord, line" },
  { kanji: "網", onyomi: "あみ", kunyomi: "", meaning: "net, netting, web" },
  { kanji: "綸", onyomi: "リン", kunyomi: "いと", meaning: "fishing line, silk thread" },
  { kanji: "綺", onyomi: "き", kunyomi: "", meaning: "thin twilled silk fabric" },
  { kanji: "綾", onyomi: "あや", kunyomi: "", meaning: "figure, design, twill weave" },
  { kanji: "緊", onyomi: "キン", kunyomi: "", meaning: "tight, tense, urgent" },
  { kanji: "緋", onyomi: "あか", kunyomi: "", meaning: "red, crimson, scarlet" },
  { kanji: "緩", onyomi: "カン", kunyomi: "ゆる.い, ゆる.やか, ゆる.む, ゆる.める", meaning: "slacken, loosen, relax, lessen, be moderate, ease" },
  { kanji: "緯", onyomi: "よこいと", kunyomi: "", meaning: "weft, woof (crosswise threads on a loom)" },
  { kanji: "縛", onyomi: "ばく", kunyomi: "", meaning: "tying up, restraint, restriction" },
  { kanji: "縦", onyomi: "たて", kunyomi: "", meaning: "the vertical, height, front-to-back" },
  { kanji: "縫", onyomi: "ホウ", kunyomi: "ぬ（う）", meaning: "sew, stitch" },
  { kanji: "繊", onyomi: "せん", kunyomi: "", meaning: "daikon julienne, julienned daikon, one ten-millionth" },
  { kanji: "繕", onyomi: "ゼン", kunyomi: "つくろ.う", meaning: "darning, repair, mend, trim, tidy up, adjust" },
  { kanji: "繭", onyomi: "まゆ", kunyomi: "", meaning: "cocoon" },
  { kanji: "繰", onyomi: "ソウ", kunyomi: "く（る）", meaning: "wind, reel, spin, turn" },
  { kanji: "罰", onyomi: "ばつ", kunyomi: "", meaning: "punishment, penalty" },
  { kanji: "罷", onyomi: "ヒ", kunyomi: "や.める", meaning: "stop, cease, resign, leave, quit" },
  { kanji: "羅", onyomi: "ら", kunyomi: "", meaning: "Latin (language)" },
  { kanji: "羊", onyomi: "ひつじ", kunyomi: "", meaning: "sheep (Ovis aries), Sheep" },
  { kanji: "翁", onyomi: "おきな", kunyomi: "", meaning: "old man, venerable gentleman, venerable" },
  { kanji: "翔", onyomi: "ショウ", kunyomi: "か（ける）、と（ぶ）", meaning: "soar, fly, glide" },
  { kanji: "翠", onyomi: "みどり", kunyomi: "", meaning: "green, greenery, verdure" },
  { kanji: "翼", onyomi: "つばさ", kunyomi: "", meaning: "wing, Chinese " },
  { kanji: "翻", onyomi: "ハン", kunyomi: "", meaning: "han, fan, unit that doubles the score of a hand" },
  { kanji: "耀", onyomi: "ヨウ", kunyomi: "かがや（く）、ひかり", meaning: "radiance, brilliance, shining" },
  { kanji: "耐", onyomi: "たい", kunyomi: "", meaning: "-proof, -resistant" },
  { kanji: "耗", onyomi: "コウ", kunyomi: "", meaning: "decrease" },
  { kanji: "耶", onyomi: "ヤ", kunyomi: "", meaning: "question mark" },
  { kanji: "聖", onyomi: "せい", kunyomi: "", meaning: "Saint, St., S." },
  { kanji: "聡", onyomi: "ソウ", kunyomi: "さと.い", meaning: "wise, fast learner" },
  { kanji: "聴", onyomi: "チョウ", kunyomi: "き.く", meaning: "listen, headstrong, naughty, careful inquiry" },
  { kanji: "肇", onyomi: "チョウ", kunyomi: "はじ.める", meaning: "beginning" },
  { kanji: "肖", onyomi: "ショウ", kunyomi: "あやか.る", meaning: "resemblance" },
  { kanji: "肝", onyomi: "きも", kunyomi: "", meaning: "liver, innards, courage" },
  { kanji: "肢", onyomi: "あし", kunyomi: "", meaning: "foot, paw, arm (of an octopus, squid, etc.)" },
  { kanji: "肥", onyomi: "こえ", kunyomi: "", meaning: "manure, night soil, dung" },
  { kanji: "肪", onyomi: "ボウ", kunyomi: "", meaning: "fat, fatty tissue" },
  { kanji: "胆", onyomi: "い", kunyomi: "", meaning: "gallbladder, liver" },
  { kanji: "胎", onyomi: "たい", kunyomi: "", meaning: "womb" },
  { kanji: "胞", onyomi: "ホウ", kunyomi: "", meaning: "cell, membrane, sac" },
  { kanji: "胡", onyomi: "こ", kunyomi: "", meaning: "barbarian tribes surrounding ancient China, Ethnic groups in Chinese history" },
  { kanji: "胤", onyomi: "たね", kunyomi: "", meaning: "issue, offspring, paternal blood" },
  { kanji: "胴", onyomi: "ドウ", kunyomi: "", meaning: "trunk, torso, hull (ship), hub of wheel" },
  { kanji: "脅", onyomi: "キョウ", kunyomi: "おど.す, おど.かす", meaning: "threaten, coerce" },
  { kanji: "脚", onyomi: "あし", kunyomi: "", meaning: "foot, paw, arm (of an octopus, squid, etc.)" },
  { kanji: "脩", onyomi: "シュウ", kunyomi: "おさ.める", meaning: "discipline, conduct oneself well, study, master" },
  { kanji: "脱", onyomi: "ダツ", kunyomi: "ぬ.ぐ, ぬ.げる", meaning: "undress, removing, escape from, get rid of, be left out, take off" },
  { kanji: "脹", onyomi: "チョウ", kunyomi: "ふく.れる, ふく.らす", meaning: "dilate, distend, bulge, fill out, swell" },
  { kanji: "腐", onyomi: "フ", kunyomi: "くさ.る, くさ.れる", meaning: "rot, decay, sour" },
  { kanji: "腸", onyomi: "ちょう", kunyomi: "", meaning: "intestine, bowel, Intestine" },
  { kanji: "膜", onyomi: "まく", kunyomi: "", meaning: "membrane, film" },
  { kanji: "膨", onyomi: "ボウ", kunyomi: "ふく.らむ, ふく.れる", meaning: "swell, get fat, thick" },
  { kanji: "臨", onyomi: "リン", kunyomi: "のぞ.む", meaning: "look to, face, meet, confront, attend, call on" },
  { kanji: "臭", onyomi: "しゅう", kunyomi: "", meaning: "-smell, stinking of, smacking of" },
  { kanji: "至", onyomi: "し", kunyomi: "", meaning: "to (a place), until (a time)" },
  { kanji: "致", onyomi: "チ", kunyomi: "いた（す）", meaning: "cause, bring about, lead to" },
  { kanji: "興", onyomi: "きょう", kunyomi: "", meaning: "interest, entertainment, pleasure" },
  { kanji: "舌", onyomi: "した", kunyomi: "", meaning: "tongue, tongue-like object, clapper (of a bell)" },
  { kanji: "舗", onyomi: "ほ", kunyomi: "", meaning: "shop, store, counter for foldable things such as maps, etc." },
  { kanji: "舜", onyomi: "", kunyomi: "", meaning: "Shun (Chinese leader)" },
  { kanji: "舶", onyomi: "つむ", kunyomi: "", meaning: "large ship" },
  { kanji: "艇", onyomi: "てい", kunyomi: "", meaning: "(small) boat" },
  { kanji: "艦", onyomi: "カン", kunyomi: "", meaning: "warship, battleship, naval vessel" },
  { kanji: "艶", onyomi: "つや", kunyomi: "", meaning: "gloss, luster, lustre" },
  { kanji: "芋", onyomi: "いも", kunyomi: "", meaning: "tuber, taro, potato" },
  { kanji: "芙", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "芝", onyomi: "しば", kunyomi: "", meaning: "lawn, sod, turf" },
  { kanji: "芳", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "芹", onyomi: "せり", kunyomi: "", meaning: "Java water dropwort (Oenanthe javanica), Japanese parsley, Oenanthe javanica" },
  { kanji: "芽", onyomi: "め", kunyomi: "", meaning: "sprout, shoot, bud" },
  { kanji: "苑", onyomi: "えん", kunyomi: "", meaning: "garden, orchard, park" },
  { kanji: "苗", onyomi: "なえ", kunyomi: "", meaning: "seedling, young plant, rice seedling" },
  { kanji: "茂", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "茄", onyomi: "なす", kunyomi: "", meaning: "eggplant (Solanum melongena), aubergine, Nasubi" },
  { kanji: "茅", onyomi: "かや", kunyomi: "", meaning: "grass used for thatching, sedge used for thatching" },
  { kanji: "茉", onyomi: "マツ", kunyomi: "", meaning: "jasmine" },
  { kanji: "茎", onyomi: "くき", kunyomi: "", meaning: "stalk, stem, Plant stem" },
  { kanji: "茜", onyomi: "あかね", kunyomi: "", meaning: "madder (esp. Japanese madder, Rubia argyi), madder (red color), Rubia" },
  { kanji: "荘", onyomi: "しょう", kunyomi: "", meaning: "manor, villa, Shou" },
  { kanji: "莉", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "莞", onyomi: "ふとい", kunyomi: "", meaning: "softstem bulrush (Scirpus tabernaemontani)" },
  { kanji: "菊", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "菌", onyomi: "きん", kunyomi: "", meaning: "fungus, germ, bacterium" },
  { kanji: "菖", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "菫", onyomi: "すみれ", kunyomi: "", meaning: "violet (any flower of genus Viola, esp. the Fuji dawn, Viola mandshurica)" },
  { kanji: "華", onyomi: "はな", kunyomi: "", meaning: "flower, blossom, bloom" },
  { kanji: "萌", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "萩", onyomi: "はぎ", kunyomi: "", meaning: "bush clover, Japanese clover (any flowering plant of genus Lespedeza), dark red exterior with blue interior (color combination worn in autumn)" },
  { kanji: "葬", onyomi: "そう", kunyomi: "", meaning: "funeral" },
  { kanji: "葵", onyomi: "あおい", kunyomi: "", meaning: "mallow (any plant of family Malvaceae), Asarum caulescens (species of wild ginger), Aoi" },
  { kanji: "蒔", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "蒼", onyomi: "あお", kunyomi: "", meaning: "blue, azure, green" },
  { kanji: "蓄", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "蓉", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "蓮", onyomi: "はす", kunyomi: "", meaning: "sacred lotus (Nelumbo nucifera), Indian lotus, lotus" },
  { kanji: "蔦", onyomi: "つた", kunyomi: "", meaning: "ivy (esp. Boston ivy, Parthenocissus tricuspidata)" },
  { kanji: "蕉", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "蕗", onyomi: "ふき", kunyomi: "", meaning: "giant butterbur (Petasites japonicus), Japanese sweet coltsfoot, Petasites japonicus" },
  { kanji: "薦", onyomi: "こも", kunyomi: "", meaning: "woven straw mat (orig. made of wild rice leaves), beggar, Manchurian wild rice (Zizania latifolia)" },
  { kanji: "薪", onyomi: "まき", kunyomi: "", meaning: "piece(s) of firewood (esp. chopped or split from logs), kindling (twigs, branches, etc.), firewood" },
  { kanji: "薫", onyomi: "くん", kunyomi: "", meaning: "pleasant smell, aroma, fragrance" },
  { kanji: "藍", onyomi: "あい", kunyomi: "", meaning: "dyer's knotweed (Persicaria tinctoria, used to produce indigo dye), indigo (dye), indigo (colour)" },
  { kanji: "藤", onyomi: "ふじ", kunyomi: "", meaning: "wisteria (esp. Japanese wisteria, Wisteria floribunda), wistaria, Fuji" },
  { kanji: "藩", onyomi: "はん", kunyomi: "", meaning: "han (estate of a daimyo in the Edo and early Meiji periods), feudal domain, fief" },
  { kanji: "藻", onyomi: "も", kunyomi: "", meaning: "algae, waterweed, seaweed" },
  { kanji: "蘭", onyomi: "らん", kunyomi: "", meaning: "orchid, Netherlands, Holland" },
  { kanji: "虎", onyomi: "とら", kunyomi: "", meaning: "tiger (Panthera tigris), drunkard, drunk" },
  { kanji: "虐", onyomi: "ギャク", kunyomi: "しいた.げる", meaning: "tyrannize, oppress" },
  { kanji: "彪", onyomi: "ヒョウ", kunyomi: "", meaning: "spotted, mottled, patterned" },
  { kanji: "虚", onyomi: "そら", kunyomi: "", meaning: "sky, the air, the heavens" },
  { kanji: "虜", onyomi: "とりこ", kunyomi: "", meaning: "captive, prisoner, victim (of love, etc.)" },
  { kanji: "虞", onyomi: "おそれ", kunyomi: "", meaning: "fear, horror, anxiety" },
  { kanji: "虹", onyomi: "にじ", kunyomi: "", meaning: "rainbow, Rainbow" },
  { kanji: "蚊", onyomi: "か", kunyomi: "", meaning: "mosquito" },
  { kanji: "蚕", onyomi: "かいこ", kunyomi: "", meaning: "silkworm (Bombyx mori), Bombyx mori" },
  { kanji: "蛇", onyomi: "へび", kunyomi: "", meaning: "snake, serpent, large snake" },
  { kanji: "蛍", onyomi: "ほたる", kunyomi: "", meaning: "firefly (Luciola cruciata), lightning bug, glowworm" },
  { kanji: "蛮", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "蝶", onyomi: "ちょう", kunyomi: "", meaning: "butterfly" },
  { kanji: "融", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "衆", onyomi: "しゅう", kunyomi: "", meaning: "great numbers (of people), numerical superiority, masses" },
  { kanji: "街", onyomi: "まち", kunyomi: "", meaning: "town, block, neighbourhood" },
  { kanji: "衝", onyomi: "しょう", kunyomi: "", meaning: "important point (e.g. on a route), important role (responsibility, etc.), opposition" },
  { kanji: "衡", onyomi: "くびき", kunyomi: "", meaning: "yoke, constraints, oppression" },
  { kanji: "衰", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "衷", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "衿", onyomi: "えり", kunyomi: "", meaning: "collar, lapel, neckband" },
  { kanji: "袈", onyomi: "ケ", kunyomi: "", meaning: "Buddhist surplice" },
  { kanji: "裂", onyomi: "レツ", kunyomi: "さ.く, さ.ける", meaning: "split, rend, tear" },
  { kanji: "裕", onyomi: "ユウ", kunyomi: "ゆた.か", meaning: "abundant, rich, fertile" },
  { kanji: "裟", onyomi: "シャ", kunyomi: "", meaning: "gauze" },
  { kanji: "裸", onyomi: "はだか", kunyomi: "", meaning: "nakedness, nudity, bareness" },
  { kanji: "褐", onyomi: "かち", kunyomi: "", meaning: "dark indigo (almost black), coarse cloth" },
  { kanji: "褒", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "襟", onyomi: "えり", kunyomi: "", meaning: "collar, lapel, neckband" },
  { kanji: "襲", onyomi: "かさね", kunyomi: "", meaning: "pile, heap, layers (e.g. of clothing)" },
  { kanji: "覆", onyomi: "ふく", kunyomi: "", meaning: "concealment (of one's vices), veil, cover" },
  { kanji: "覇", onyomi: "は", kunyomi: "", meaning: "supremacy (over a nation), hegemony, domination" },
  { kanji: "覧", onyomi: "ラン", kunyomi: "み.る", meaning: "perusal, see" },
  { kanji: "訂", onyomi: "テイ", kunyomi: "ただ.す", meaning: "revise, correct, decide" },
  { kanji: "討", onyomi: "トウ", kunyomi: "う.つ", meaning: "chastise, attack, defeat, destroy, conquer" },
  { kanji: "託", onyomi: "タク", kunyomi: "かこつ.ける, かこつ", meaning: "consign, requesting, entrusting with, pretend (to)" },
  { kanji: "訟", onyomi: "ショウ", kunyomi: "", meaning: "sue, accuse" },
  { kanji: "訳", onyomi: "わけ", kunyomi: "", meaning: "reason, cause, grounds" },
  { kanji: "訴", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "診", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "証", onyomi: "あかし", kunyomi: "", meaning: "proof, evidence, sign" },
  { kanji: "詐", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "詔", onyomi: "みことのり", kunyomi: "", meaning: "imperial decree, imperial edict, Command paper" },
  { kanji: "詠", onyomi: "えい", kunyomi: "", meaning: "recitation (of a poem), chanting, singing" },
  { kanji: "詢", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "詩", onyomi: "し", kunyomi: "", meaning: "poem, poetry, verse" },
  { kanji: "該", onyomi: "がい", kunyomi: "", meaning: "said, matter in question" },
  { kanji: "詳", onyomi: "ショウ", kunyomi: "くわし.い", meaning: "detailed, full, minute, accurate, well-informed" },
  { kanji: "誇", onyomi: "コ", kunyomi: "ほこ.る", meaning: "boast, be proud, pride, triumphantly" },
  { kanji: "誉", onyomi: "ヨ", kunyomi: "ほま.れ, ほめ.る", meaning: "reputation, praise, honor, glory" },
  { kanji: "誠", onyomi: "まこと", kunyomi: "", meaning: "truth, reality, fact" },
  { kanji: "誓", onyomi: "せい", kunyomi: "ちか（う）", meaning: "vow, swear, pledge" },
  { kanji: "誕", onyomi: "たん", kunyomi: "", meaning: "birth, nativity, be born" },
  { kanji: "誼", onyomi: "よしみ", kunyomi: "", meaning: "friendship, friendly relations, connection" },
  { kanji: "諄", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "請", onyomi: "しょう", kunyomi: "", meaning: "request, invitation, privilege in criminal law given to nobles of the fifth rank or above (ritsuryō system)" },
  { kanji: "諒", onyomi: "りょう", kunyomi: "", meaning: "fact, truth, understanding" },
  { kanji: "諭", onyomi: "ユ", kunyomi: "さと.す", meaning: "rebuke, admonish, charge, warn, persuade" },
  { kanji: "諮", onyomi: "シ", kunyomi: "はか.る", meaning: "consult with" },
  { kanji: "諾", onyomi: "だく", kunyomi: "", meaning: "agreement, assent, Norway" },
  { kanji: "謀", onyomi: "はかりごと", kunyomi: "", meaning: "plan, scheme, stratagem" },
  { kanji: "謁", onyomi: "えつ", kunyomi: "", meaning: "audience (with a superior, e.g. nobility), visiting card, name card" },
  { kanji: "謄", onyomi: "とう", kunyomi: "", meaning: "copy, duplicate, transcript" },
  { kanji: "謙", onyomi: "けん", kunyomi: "へりくだ（る）", meaning: "humble, modest, self-effacing" },
  { kanji: "謡", onyomi: "うたい", kunyomi: "", meaning: "noh chanting, noh chant" },
  { kanji: "謹", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "譜", onyomi: "ふ", kunyomi: "", meaning: "(sheet) music, (musical) note, (musical) score" },
  { kanji: "譲", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "豚", onyomi: "ぶた", kunyomi: "", meaning: "pig (Sus scrofa domesticus), pork, fatso" },
  { kanji: "豪", onyomi: "ごう", kunyomi: "", meaning: "Australia" },
  { kanji: "貞", onyomi: "てい", kunyomi: "", meaning: "firm adherence to one's principles, chastity (of a woman)" },
  { kanji: "貢", onyomi: "こう", kunyomi: "", meaning: "tribute" },
  { kanji: "貫", onyomi: "かん", kunyomi: "", meaning: "kan (obs. unit of weight, approx. 3.75 kg, 8.3 lb), kan (obs. unit of currency, equiv. to 1000 mon in the Edo period; col. 10 mon in the Meiji period), counter for pieces of sushi" },
  { kanji: "貴", onyomi: "き", kunyomi: "", meaning: "your, indicates high rank or status, indicates love and respect (usu. for an older person)" },
  { kanji: "賀", onyomi: "が", kunyomi: "", meaning: "congratulation, celebration" },
  { kanji: "賄", onyomi: "まいない", kunyomi: "", meaning: "bribe" },
  { kanji: "賊", onyomi: "ぞく", kunyomi: "", meaning: "thief, robber, burglar" },
  { kanji: "賜", onyomi: "たまもの", kunyomi: "", meaning: "gift, boon, godsend" },
  { kanji: "賠", onyomi: "ばい", kunyomi: "つぐな（う）", meaning: "compensate, make up for, indemnify" },
  { kanji: "賦", onyomi: "ふ", kunyomi: "", meaning: "levy, tax, compose, installment" },
  { kanji: "購", onyomi: "こう", kunyomi: "", meaning: "purchase, buy, subscribe" },
  { kanji: "赦", onyomi: "しゃ", kunyomi: "", meaning: "pardon, amnesty" },
  { kanji: "赳", onyomi: "きゅう", kunyomi: "つよ（い）", meaning: "strong, robust, valiant" },
  { kanji: "赴", onyomi: "ふ", kunyomi: "おもむ（く）", meaning: "go, proceed, head for" },
  { kanji: "距", onyomi: "きょ", kunyomi: "", meaning: "tubular nectary, spur" },
  { kanji: "践", onyomi: "せん", kunyomi: "ふ（む）", meaning: "step on, practice, carry out" },
  { kanji: "跳", onyomi: "ちょう", kunyomi: "と（ぶ）、は（ねる）", meaning: "jump, leap, bound" },
  { kanji: "踏", onyomi: "とう", kunyomi: "ふ（む）、ふ（まえる）", meaning: "step, trample, carry through" },
  { kanji: "躍", onyomi: "やく", kunyomi: "おど（る）", meaning: "leap, jump, dance, bound" },
  { kanji: "軌", onyomi: "き", kunyomi: "", meaning: "rut, wheel track, distance between two wheels" },
  { kanji: "載", onyomi: "さい", kunyomi: "", meaning: "10^44, hundred tredecillion" },
  { kanji: "輔", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "輝", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "轄", onyomi: "くさび", kunyomi: "", meaning: "wedge, chock, linchpin" },
  { kanji: "辰", onyomi: "たつ", kunyomi: "", meaning: "the Dragon (fifth sign of the Chinese zodiac), hour of the Dragon (around 8am, 7-9am, or 8-10am), east-southeast" },
  { kanji: "辱", onyomi: "はじ", kunyomi: "", meaning: "shame, embarrassment, disgrace" },
  { kanji: "巡", onyomi: "じゅん", kunyomi: "", meaning: "counter for tours, cycles, rounds, circuits, etc." },
  { kanji: "迅", onyomi: "じん", kunyomi: "はや（い）", meaning: "swift, fast, rapid" },
  { kanji: "迪", onyomi: "てき", kunyomi: "みちび（く）", meaning: "guide, lead, enlighten" },
  { kanji: "迫", onyomi: "せり", kunyomi: "", meaning: "stage elevator, trapdoor" },
  { kanji: "迭", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "透", onyomi: "トウ", kunyomi: "す.く, す.かす, す.ける", meaning: "transparent, permeate, filter, penetrate" },
  { kanji: "逐", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "逓", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "逝", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "逮", onyomi: "タイ", kunyomi: "", meaning: "apprehend, arrest" },
  { kanji: "逸", onyomi: "いち", kunyomi: "", meaning: "very, excellent" },
  { kanji: "遂", onyomi: "つい", kunyomi: "", meaning: "end, final, end of life" },
  { kanji: "遇", onyomi: "ぐう", kunyomi: "あ（う）", meaning: "meet, encounter, treat, receive" },
  { kanji: "遍", onyomi: "へん", kunyomi: "", meaning: "number of times" },
  { kanji: "遣", onyomi: "けん", kunyomi: "つか（う）、や（る）", meaning: "dispatch, send, give, do" },
  { kanji: "遥", onyomi: "よう", kunyomi: "はる（か）", meaning: "far off, distant, long ago" },
  { kanji: "遭", onyomi: "そう", kunyomi: "あ（う）、あ（わせる）", meaning: "encounter, meet, experience" },
  { kanji: "遮", onyomi: "しゃ", kunyomi: "さえぎ（る）", meaning: "interrupt, obstruct, block" },
  { kanji: "遵", onyomi: "じゅん", kunyomi: "したが（う）", meaning: "abide by, follow, obey" },
  { kanji: "遷", onyomi: "せん", kunyomi: "うつ（る）、うつ（す）", meaning: "transition, move, change" },
  { kanji: "遺", onyomi: "い", kunyomi: "のこ（る）、のこ（す）", meaning: "bequeath, leave behind, reserve" },
  { kanji: "遼", onyomi: "りょう", kunyomi: "", meaning: "Liao (Manchurian dynasty; 916-1125 CE), Khitan Empire, Liao Dynasty" },
  { kanji: "還", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "邑", onyomi: "おおざと", kunyomi: "", meaning: "kanji " },
  { kanji: "那", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "邦", onyomi: "くに", kunyomi: "", meaning: "country, state, region" },
  { kanji: "邪", onyomi: "よこしま", kunyomi: "", meaning: "wicked, evil, wrong" },
  { kanji: "邸", onyomi: "やしき", kunyomi: "", meaning: "residence, estate, grounds" },
  { kanji: "郁", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "郎", onyomi: "ろう", kunyomi: "", meaning: "nth son, lang, official title in ancient China" },
  { kanji: "郡", onyomi: "ぐん", kunyomi: "", meaning: "district, county, district (of 2-20 50-home neighbourhoods or townships, in the ritsuryō period)" },
  { kanji: "郭", onyomi: "くるわ", kunyomi: "", meaning: "district, quarter, enclosure" },
  { kanji: "酉", onyomi: "とり", kunyomi: "", meaning: "the Rooster (tenth sign of the Chinese zodiac), the Cock, the Chicken" },
  { kanji: "酌", onyomi: "しゃく", kunyomi: "", meaning: "pouring alcohol, person pouring alcohol (esp. a woman)" },
  { kanji: "酔", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "酢", onyomi: "す", kunyomi: "", meaning: "vinegar, Vinegar" },
  { kanji: "酪", onyomi: "らく", kunyomi: "", meaning: "acidic drink made from fermented milk (cow, sheep, mare; one of the five flavors in Buddhism)" },
  { kanji: "酬", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "酵", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "酷", onyomi: "こく", kunyomi: "", meaning: "severe, harsh, stringent" },
  { kanji: "酸", onyomi: "さん", kunyomi: "", meaning: "acid, sourness, sour taste" },
  { kanji: "醇", onyomi: "じゅん", kunyomi: "", meaning: "pure sake, full-bodied sake, pure" },
  { kanji: "醜", onyomi: "しこ", kunyomi: "", meaning: "ugly, repulsive, detestable" },
  { kanji: "醸", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "采", onyomi: "さい", kunyomi: "", meaning: "dice, die" },
  { kanji: "釈", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "里", onyomi: "り", kunyomi: "", meaning: "Japanese league, ri, old Japanese unit of distance, approx. 3.927 km or 2.44 miles" },
  { kanji: "釣", onyomi: "つり", kunyomi: "", meaning: "fishing, angling, change (for a purchase)" },
  { kanji: "鈴", onyomi: "すず", kunyomi: "", meaning: "bell (often globular)" },
  { kanji: "鉛", onyomi: "なまり", kunyomi: "", meaning: "lead (Pb), Lead" },
  { kanji: "鉢", onyomi: "はち", kunyomi: "", meaning: "bowl, pot, basin" },
  { kanji: "銃", onyomi: "じゅう", kunyomi: "", meaning: "gun, firearm, small arms (e.g. rifle, pistol, etc)" },
  { kanji: "銑", onyomi: "ずく", kunyomi: "", meaning: "pig iron" },
  { kanji: "銘", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "銭", onyomi: "せん", kunyomi: "", meaning: "sen (hundredth of a yen), coin made of non-precious materials, one-thousandth of a kan (as a unit of currency)" },
  { kanji: "鋳", onyomi: "", kunyomi: "", meaning: "" },
  { kanji: "鋼", onyomi: "はがね", kunyomi: "", meaning: "steel, sword steel, sword" },
  { kanji: "錘", onyomi: "おもり", kunyomi: "", meaning: "weight, sinker" }
];