export interface KanjiData {
  kanji: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
}

export const N2_KANJI: KanjiData[] = [
  { kanji: "党", onyomi: "tou", kunyomi: "", meaning: "party, faction, clique" },
  { kanji: "協", onyomi: "kyou", kunyomi: "", meaning: "co-, cooperation" },
  { kanji: "総", onyomi: "sou", kunyomi: "sube(te), fusa", meaning: "general, whole, all, full, total" },
  { kanji: "区", onyomi: "ku", kunyomi: "", meaning: "ward, district" },
  { kanji: "領", onyomi: "ryou", kunyomi: "", meaning: "territory, dominion, province" },
  { kanji: "県", onyomi: "ken", kunyomi: "", meaning: "prefecture" },
  { kanji: "設", onyomi: "setsu", kunyomi: "mou(keru)", meaning: "establishment, provision, prepare" },
  { kanji: "改", onyomi: "kai", kunyomi: "arata(meru), arata(maru)", meaning: "reformation, change, modify, mend, renew, examine, inspect, search" },
  { kanji: "府", onyomi: "fu", kunyomi: "", meaning: "urban prefecture, government office, representative body, storehouse" },
  { kanji: "査", onyomi: "sa", kunyomi: "", meaning: "investigate, examine" },
  { kanji: "委", onyomi: "i", kunyomi: "yuda(neru)", meaning: "committee, entrust to, leave to, devote, discard" },
  { kanji: "軍", onyomi: "gun", kunyomi: "", meaning: "army, force, troops, war, battle" },
  { kanji: "団", onyomi: "dan", kunyomi: "", meaning: "group, association" },
  { kanji: "各", onyomi: "kaku", kunyomi: "onoono", meaning: "each, every, either" },
  { kanji: "島", onyomi: "tou", kunyomi: "shima", meaning: "island" },
  { kanji: "革", onyomi: "kaku", kunyomi: "kawa", meaning: "leather, become serious, hide, pelt" },
  { kanji: "村", onyomi: "son", kunyomi: "mura", meaning: "village, town" },
  { kanji: "勢", onyomi: "sei, zei", kunyomi: "ikio(i)", meaning: "forces, energy, military strength" },
  { kanji: "減", onyomi: "gen", kunyomi: "he(ru), he(rasu)", meaning: "dwindle, decrease, reduce, decline, curtail, get hungry" },
  { kanji: "未", onyomi: "mi, bi", kunyomi: "ma(da)", meaning: "not yet, hitherto, still, even now, sign of the ram" },
  { kanji: "跡", onyomi: "seki", kunyomi: "ato", meaning: "tracks, mark, print, impression" },
  { kanji: "妻", onyomi: "sai", kunyomi: "tsuma", meaning: "wife, spouse" },
  { kanji: "旧", onyomi: "kyuu", kunyomi: "furu(i)", meaning: "old times, old things, old friend, former, ex-" },
  { kanji: "夫", onyomi: "fu, fuu", kunyomi: "otto", meaning: "husband, man" },
  { kanji: "混", onyomi: "kon", kunyomi: "ma(zaru), ko(mu)", meaning: "mix, blend, confuse" },
  { kanji: "雲", onyomi: "un", kunyomi: "kumo", meaning: "cloud" },
  { kanji: "祭", onyomi: "sai", kunyomi: "matsu(ru)", meaning: "ritual, offer prayers, celebrate, deify, enshrine, worship" },
  { kanji: "司", onyomi: "shi", kunyomi: "tsukasa(doru)", meaning: "director, official, govt office, rule, administer" },
  { kanji: "観", onyomi: "kan", kunyomi: "mi(ru)", meaning: "outlook, look, appearance, condition, view" },
  { kanji: "調", onyomi: "chou", kunyomi: "shira(beru), totono(u)", meaning: "tune, tone, meter, key (music), writing style, prepare, exorcise, investigate" },
  { kanji: "都", onyomi: "to, tsu", kunyomi: "miyako", meaning: "metropolis, capital" },
  { kanji: "費", onyomi: "hi", kunyomi: "tsui(yasu)", meaning: "expense, cost, spend, consume, waste" },
  { kanji: "打", onyomi: "da", kunyomi: "u(tsu)", meaning: "strike, hit, knock, pound, dozen" },
  { kanji: "職", onyomi: "shoku", kunyomi: "", meaning: "post, employment, work" },
  { kanji: "築", onyomi: "chiku", kunyomi: "kizu(ku)", meaning: "fabricate, build, construct" },
  { kanji: "居", onyomi: "kyo", kunyomi: "i(ru), o(ru)", meaning: "reside, to be, exist, live with" },
  { kanji: "群", onyomi: "gun", kunyomi: "mu(re), mura(garu)", meaning: "flock, group, crowd, herd, swarm, cluster" },
  { kanji: "録", onyomi: "roku", kunyomi: "", meaning: "record" },
  { kanji: "導", onyomi: "dou", kunyomi: "michibi(ku)", meaning: "guidance, leading, conduct, usher" },
  { kanji: "順", onyomi: "jun", kunyomi: "", meaning: "obey, order, turn, right, docility, occasion" },
  { kanji: "負", onyomi: "fu", kunyomi: "ma(keru), o(u)", meaning: "defeat, negative, minus, bear, owe, assume a responsibility" },
  { kanji: "井", onyomi: "sei, shou", kunyomi: "i", meaning: "well, well crib, town, community" },
  { kanji: "酒", onyomi: "shu", kunyomi: "sake", meaning: "sake, alcohol" },
  { kanji: "落", onyomi: "raku", kunyomi: "o(chiru), o(tosu)", meaning: "fall, drop, come down, village, hamlet" },
  { kanji: "差", onyomi: "sa", kunyomi: "sa(su)", meaning: "distinction, difference, variation, discrepancy, margin, balance" },
  { kanji: "規", onyomi: "ki", kunyomi: "", meaning: "standard, measure" },
  { kanji: "秒", onyomi: "byou", kunyomi: "", meaning: "second, moment" },
  { kanji: "笑", onyomi: "shou", kunyomi: "wara(u), e(mu)", meaning: "laugh" },
  { kanji: "議", onyomi: "gi", kunyomi: "", meaning: "deliberation, consultation, debate, consideration" },
  { kanji: "席", onyomi: "seki", kunyomi: "", meaning: "seat, mat, occasion, place" },
  { kanji: "警", onyomi: "kei", kunyomi: "imashi(meru)", meaning: "admonish, commandment" },
  { kanji: "護", onyomi: "go", kunyomi: "mamo(ru)", meaning: "safeguard, protect" },
  { kanji: "災", onyomi: "sai", kunyomi: "wazawa(i)", meaning: "disaster, calamity, woe, curse, evil" },
  { kanji: "副", onyomi: "fuku", kunyomi: "", meaning: "vice-, assistant, aide, duplicate, copy" },
  { kanji: "唱", onyomi: "shou", kunyomi: "tona(eru)", meaning: "chant, recite, call upon, yell" },
  { kanji: "士", onyomi: "shi", kunyomi: "samurai", meaning: "gentleman, scholar, samurai, samurai radical (no. 33)" },
  { kanji: "治", onyomi: "ji, chi", kunyomi: "osa(meru), nao(ru)", meaning: "reign, be at peace, calm down, subdue, quell, govt, cure, heal, rule, conserve" },
  { kanji: "準", onyomi: "jun", kunyomi: "", meaning: "semi-, correspond to, proportionate to, conform, imitate" },
  { kanji: "賞", onyomi: "shou", kunyomi: "", meaning: "prize, reward, praise" },
  { kanji: "辞", onyomi: "ji", kunyomi: "ya(meru)", meaning: "resign, word, term, expression" },
  { kanji: "乗", onyomi: "jou", kunyomi: "no(ru)", meaning: "ride, power, multiplication, record, counter for vehicles, board, mount, join" },
  { kanji: "満", onyomi: "man", kunyomi: "mi(chiru), mi(tasu)", meaning: "full, fullness, enough, satisfy" },
  { kanji: "率", onyomi: "ritsu, sotsu", kunyomi: "hiki(iru)", meaning: "ratio, rate, proportion, percentage, coefficient, factor" },
  { kanji: "承", onyomi: "shou", kunyomi: "uketamawa(ru)", meaning: "acquiesce, hear, listen to, be informed, receive" },
  { kanji: "角", onyomi: "kaku", kunyomi: "kado, tsuno", meaning: "angle, corner, square, horn, antlers" },
  { kanji: "停", onyomi: "tei", kunyomi: "to(meru)", meaning: "halt, stopping" },
  { kanji: "株", onyomi: "shu", kunyomi: "kabu", meaning: "stocks, stump, shares, stock, counter for small plants" },
  { kanji: "競", onyomi: "kyou, kei", kunyomi: "kiso(u), se(ru)", meaning: "emulate, compete with, bid, sell at auction, bout, contest, race" },
  { kanji: "推", onyomi: "sui", kunyomi: "o(su)", meaning: "conjecture, infer, guess, suppose, support" },
  { kanji: "易", onyomi: "eki, i", kunyomi: "yasa(shii)", meaning: "easy, ready to, simple, fortune-telling, divination" },
  { kanji: "財", onyomi: "zai, sai", kunyomi: "", meaning: "property, money, wealth, assets" },
  { kanji: "技", onyomi: "gi", kunyomi: "waza", meaning: "skill, art, craft, ability, feat, performance, vocation, arts" },
  { kanji: "低", onyomi: "tei", kunyomi: "hiku(i)", meaning: "lower, short, humble" },
  { kanji: "裁", onyomi: "sai", kunyomi: "saba(ku)", meaning: "tailor, judge, decision, cut out (pattern)" },
  { kanji: "権", onyomi: "ken, gon", kunyomi: "", meaning: "authority, power, rights" },
  { kanji: "鉄", onyomi: "tetsu", kunyomi: "", meaning: "iron" },
  { kanji: "価", onyomi: "ka", kunyomi: "atai", meaning: "value, price" },
  { kanji: "判", onyomi: "han, ban", kunyomi: "", meaning: "judgement, signature, stamp, seal" },
  { kanji: "易", onyomi: "eki, i", kunyomi: "yasa(shii)", meaning: "easy, ready to, simple, fortune-telling, divination" },
  { kanji: "河", onyomi: "ka", kunyomi: "kawa", meaning: "river" },
  { kanji: "択", onyomi: "taku", kunyomi: "", meaning: "choose, select, elect, prefer" },
  { kanji: "老", onyomi: "rou", kunyomi: "o(iru), fuke(ru)", meaning: "old man, old age, grow old" },
  { kanji: "講", onyomi: "kou", kunyomi: "", meaning: "lecture, club, association" },
  { kanji: "謝", onyomi: "sha", kunyomi: "ayama(ru)", meaning: "apologize, thank, refuse" },
  { kanji: "浮", onyomi: "fu", kunyomi: "u(ku), u(karu)", meaning: "floating, float, rise to surface" },
  { kanji: "録", onyomi: "roku", kunyomi: "", meaning: "record" },
  { kanji: "城", onyomi: "jou", kunyomi: "shiro", meaning: "castle" },
  { kanji: "疑", onyomi: "gi", kunyomi: "utaga(u)", meaning: "doubt, distrust, be suspicious, question" },
  { kanji: "露", onyomi: "ro, rou", kunyomi: "tsuyu", meaning: "dew, tears, expose, Russia" },
  { kanji: "修", onyomi: "shuu", kunyomi: "osa(meru)", meaning: "discipline, conduct oneself well, study, master" },
  { kanji: "豊", onyomi: "hou", kunyomi: "yuta(ka)", meaning: "bountiful, excellent, rich" },
  { kanji: "械", onyomi: "kai", kunyomi: "", meaning: "contraption, fetter, machine, instrument" },
  { kanji: "故", onyomi: "ko", kunyomi: "yue", meaning: "happenstance, especially, intentionally, reason, cause, circumstances, the late, therefore, consequently" },
  { kanji: "科", onyomi: "ka", kunyomi: "", meaning: "department, course, section" },
  { kanji: "報", onyomi: "hou", kunyomi: "muku(iru)", meaning: "report, news, reward, retribution" },
  { kanji: "勤", onyomi: "kin, gon", kunyomi: "tsuto(meru)", meaning: "diligence, become employed, serve" },
  { kanji: "察", onyomi: "satsu", kunyomi: "", meaning: "guess, presume, surmise, judge, understand" },
  { kanji: "義", onyomi: "gi", kunyomi: "", meaning: "righteousness, justice, morality, honor, loyalty, meaning" },
  { kanji: "臣", onyomi: "shin, jin", kunyomi: "", meaning: "retainer, subject" },
  { kanji: "史", onyomi: "shi", kunyomi: "", meaning: "history, chronicle" },
  { kanji: "装", onyomi: "sou, shou", kunyomi: "yoso(u)", meaning: "attire, dress, pretend, disguise, profess" },
  { kanji: "営", onyomi: "ei", kunyomi: "itona(mu)", meaning: "camp, perform, build, conduct (business)" },
  { kanji: "視", onyomi: "shi", kunyomi: "", meaning: "inspection, regard as, see, look at" },
  { kanji: "精", onyomi: "sei, shou", kunyomi: "", meaning: "refined, ghost, fairy, energy, vitality, semen, excellence, purity, skill" },
  { kanji: "採", onyomi: "sai", kunyomi: "to(ru)", meaning: "pick, take, fetch, take up" },
  { kanji: "章", onyomi: "shou", kunyomi: "", meaning: "badge, chapter, composition, poem, design" },
  { kanji: "深", onyomi: "shin", kunyomi: "fuka(i), fuke(ru)", meaning: "deep, heighten, intensify, strengthen" },
  { kanji: "律", onyomi: "ritsu, richi", kunyomi: "", meaning: "rhythm, law, regulation, gauge, control" },
  { kanji: "告", onyomi: "koku", kunyomi: "tsu(geru)", meaning: "revelation, tell, inform, announce" },
  { kanji: "格", onyomi: "kaku, kou", kunyomi: "", meaning: "status, rank, capacity, character, case (law, grammar)" },
  { kanji: "派", onyomi: "ha", kunyomi: "", meaning: "faction, group, party, clique, sect, school" },
  { kanji: "志", onyomi: "shi", kunyomi: "kokorozashi", meaning: "intention, plan, resolve, aspire, motive, hopes, shilling" },
  { kanji: "環", onyomi: "kan", kunyomi: "wa", meaning: "ring, circle, link, wheel" },
  { kanji: "複", onyomi: "fuku", kunyomi: "", meaning: "duplicate, double, compound, multiple" },
  { kanji: "雑", onyomi: "zatsu, zou", kunyomi: "", meaning: "miscellaneous" },
  { kanji: "木", onyomi: "boku, moku", kunyomi: "ki, ko", meaning: "tree, wood" },
  { kanji: "編", onyomi: "hen", kunyomi: "a(mu)", meaning: "compilation, knit, plait, braid, twist, editing, completed poem, part of a book" },
  { kanji: "増", onyomi: "zou", kunyomi: "ma(su), fu(eru)", meaning: "increase, add, augment, gain, promote" },
  { kanji: "減", onyomi: "gen", kunyomi: "he(ru), he(rasu)", meaning: "dwindle, decrease, reduce, decline, curtail, get hungry" },
  { kanji: "師", onyomi: "shi", kunyomi: "", meaning: "expert, teacher, master, model, exemplar, army (incl. counter), war" },
  { kanji: "算", onyomi: "san", kunyomi: "", meaning: "calculate, divining, number, abacus, probability" },
  { kanji: "票", onyomi: "hyou", kunyomi: "", meaning: "ballot, label, ticket, sign" },
  { kanji: "宗", onyomi: "shuu, sou", kunyomi: "", meaning: "religion, sect, denomination, main point, origin, essence" },
  { kanji: "宙", onyomi: "chuu", kunyomi: "", meaning: "mid-air, air, space, sky, memorization, interval of time" },
  { kanji: "宇", onyomi: "u", kunyomi: "", meaning: "eaves, roof, house, heaven" },
  { kanji: "宅", onyomi: "taku", kunyomi: "", meaning: "home, house, residence, our house, my husband" },
  { kanji: "守", onyomi: "shu, su", kunyomi: "mamo(ru), mo(ri)", meaning: "guard, protect, defend, obey" },
  { kanji: "宮", onyomi: "kyuu, guu", kunyomi: "miya", meaning: "Shinto shrine, constellations, palace, princess" },
  { kanji: "密", onyomi: "mitsu", kunyomi: "", meaning: "secrecy, density (pop), minuteness, carefulness" },
  { kanji: "康", onyomi: "kou", kunyomi: "", meaning: "ease, peace" },
  { kanji: "害", onyomi: "gai", kunyomi: "", meaning: "harm, injury" },
  { kanji: "容", onyomi: "you", kunyomi: "", meaning: "contain, form, looks" },
  { kanji: "寄", onyomi: "ki", kunyomi: "yo(ru)", meaning: "draw near, stop in, bring near, gather, collect, send, forward" },
  { kanji: "富", onyomi: "fu, fuu", kunyomi: "to(mu)", meaning: "wealth, enrich, abundant" },
  { kanji: "導", onyomi: "dou", kunyomi: "michibi(ku)", meaning: "guidance, leading, conduct, usher" },
  { kanji: "居", onyomi: "kyo", kunyomi: "i(ru), o(ru)", meaning: "reside, to be, exist, live with" },
  { kanji: "届", onyomi: "kai", kunyomi: "todo(ku)", meaning: "deliver, reach, arrive, report, notify, forward" },
  { kanji: "層", onyomi: "sou", kunyomi: "", meaning: "stratum, social class, layer, story, floor" },
  { kanji: "局", onyomi: "kyoku", kunyomi: "", meaning: "bureau, board, office, affair, conclusion, court lady, lady-in-waiting, her apartment" },
  { kanji: "属", onyomi: "zoku", kunyomi: "", meaning: "belong, genus, subordinate official, affiliated" },
  { kanji: "布", onyomi: "fu", kunyomi: "nuno", meaning: "linen, cloth, spread, distribute" },
  { kanji: "座", onyomi: "za", kunyomi: "suwa(ru)", meaning: "squat, seat, cushion, gathering, sit" },
  { kanji: "量", onyomi: "ryou", kunyomi: "haka(ru)", meaning: "quantity, measure, weight, amount, consider, estimate, surmise" },
  { kanji: "捕", onyomi: "ho", kunyomi: "to(ru), tsuka(maru)", meaning: "catch, capture" },
  { kanji: "破", onyomi: "ha", kunyomi: "yabu(ru)", meaning: "rend, rip, tear, break, destroy, defeat, frustrate" },
  { kanji: "述", onyomi: "jutsu", kunyomi: "no(beru)", meaning: "mention, state, speak, relate" },
  { kanji: "標", onyomi: "hyou", kunyomi: "", meaning: "signpost, seal, mark, stamp, imprint, symbol, emblem, trademark, evidence, souvenir, target" },
  { kanji: "性", onyomi: "sei, shou", kunyomi: "", meaning: "sex, gender, nature" },
  { kanji: "処", onyomi: "sho", kunyomi: "", meaning: "dispose, manage, deal with, sentence, condemn, act, behave, place" },
  { kanji: "太", onyomi: "tai, ta", kunyomi: "futo(i)", meaning: "plump, thick, big around" },
  { kanji: "件", onyomi: "ken", kunyomi: "", meaning: "affair, case, matter, item" },
  { kanji: "再", onyomi: "sai, sa", kunyomi: "futatabi", meaning: "again, twice, second time" },
  { kanji: "販", onyomi: "han", kunyomi: "", meaning: "marketing, sell, trade" },
  { kanji: "仏", onyomi: "butsu, futsu", kunyomi: "hotoke", meaning: "Buddha, the dead, France" },
  { kanji: "否", onyomi: "hi", kunyomi: "ina", meaning: "negate, no, noes, refuse, decline, deny" },
  { kanji: "希", onyomi: "ki", kunyomi: "mare", meaning: "hope, beg, request, pray, beseech, Greece, dilute (acid), rare, few, phenomenal" },
  { kanji: "例", onyomi: "rei", kunyomi: "tameshi", meaning: "example, custom, usage, precedent" },
  { kanji: "細", onyomi: "sai", kunyomi: "hoso(i)", meaning: "dainty, get thin, taper, slender, narrow, detailed, precise" },
  { kanji: "織", onyomi: "shoku, shiki", kunyomi: "o(ru)", meaning: "weave, fabric" },
  { kanji: "約", onyomi: "yaku", kunyomi: "", meaning: "promise, approximately, shrink" },
  { kanji: "型", onyomi: "kei", kunyomi: "kata", meaning: "mould, type, model" },
  { kanji: "姿", onyomi: "shi", kunyomi: "sugata", meaning: "figure, form, shape" },
  { kanji: "余", onyomi: "yo", kunyomi: "ama(ru)", meaning: "too much, myself, surplus, other, remainder" },
  { kanji: "欠", onyomi: "ketsu", kunyomi: "ka(ku)", meaning: "lack, gap, fail, imperial storehouse" },
  { kanji: "吸", onyomi: "kyuu", kunyomi: "su(u)", meaning: "suck, imbibe, inhale, sip" },
  { kanji: "応", onyomi: "ou", kunyomi: "", meaning: "apply, answer, yes, OK, reply, accept" },
  { kanji: "快", onyomi: "kai", kunyomi: "kokoroyo(i)", meaning: "cheerful, pleasant, agreeable, comfortable" },
  { kanji: "技", onyomi: "gi", kunyomi: "waza", meaning: "skill, art, craft, ability, feat, performance, vocation, arts" },
  { kanji: "伸", onyomi: "shin", kunyomi: "no(biru), no(basu)", meaning: "expand, stretch, extend, lengthen, increase" },
  { kanji: "恋", onyomi: "ren", kunyomi: "koi, ko(u)", meaning: "romance, in love, yearn for, miss, darling" },
  { kanji: "郵", onyomi: "yuu", kunyomi: "", meaning: "mail, stagecoach stop" },
  { kanji: "幸", onyomi: "kou", kunyomi: "saiwa(i), sachi", meaning: "happiness, blessing, fortune" },
  { kanji: "決", onyomi: "ketsu", kunyomi: "ki(meru), ki(maru)", meaning: "decide, fix, agree upon, appoint" },
  { kanji: "挙", onyomi: "kyo", kunyomi: "a(geru)", meaning: "raise, plan, project, behavior, actions" },
  { kanji: "徳", onyomi: "toku", kunyomi: "", meaning: "benevolence, virtue, goodness, favor" },
  { kanji: "薬", onyomi: "yaku", kunyomi: "kusuri", meaning: "medicine, chemical, enamel, gunpowder, benefit" },
  { kanji: "額", onyomi: "gaku", kunyomi: "hitai", meaning: "forehead, tablet, plaque, framed picture, sum, amount, volume" },
  { kanji: "罪", onyomi: "zai", kunyomi: "tsumi", meaning: "guilt, sin, crime, fault, blame, offense" },
  { kanji: "賃", onyomi: "chin", kunyomi: "", meaning: "fare, fee, hire, rent, wages, charge" },
  { kanji: "類", onyomi: "rui", kunyomi: "", meaning: "sort, kind, variety, class, genus" },
  { kanji: "官", onyomi: "kan", kunyomi: "", meaning: "bureaucrat, the government, organ" },
  { kanji: "借", onyomi: "shaku", kunyomi: "ka(riru)", meaning: "borrow, rent" },
  { kanji: "緒", onyomi: "sho, cho", kunyomi: "o", meaning: "thong, beginning, inception, end, cord, strap, mental or emotional state" },
  { kanji: "縁", onyomi: "en", kunyomi: "fuchi", meaning: "affinity, relation, connection, edge, border, veranda, chance" },
  { kanji: "承", onyomi: "shou", kunyomi: "uketamawa(ru)", meaning: "acquiesce, hear, listen to, be informed, receive" },
  { kanji: "狭", onyomi: "kyou", kunyomi: "sema(i)", meaning: "cramped, narrow, contract, tight" },
  { kanji: "税", onyomi: "zei", kunyomi: "", meaning: "tax, duty" },
  { kanji: "程", onyomi: "tei", kunyomi: "hodo", meaning: "extent, degree, law, formula, distance, limits, amount" },
  { kanji: "舎", onyomi: "sha", kunyomi: "", meaning: "cottage, inn, hut, house, mansion" },
  { kanji: "奥", onyomi: "ou", kunyomi: "oku", meaning: "heart, interior" },
  { kanji: "詰", onyomi: "kitsu", kunyomi: "tsu(meru)", meaning: "packed, close, pressed, reprove, rebuke, blame" },
  { kanji: "替", onyomi: "tai", kunyomi: "ka(eru)", meaning: "exchange, spare, substitute, per-" },
  { kanji: "危", onyomi: "ki", kunyomi: "abu(nai)", meaning: "dangerous, fear, uneasy" },
  { kanji: "刻", onyomi: "koku", kunyomi: "kiza(mu)", meaning: "engrave, cut fine, chop, hash, mince, time, carving" },
  { kanji: "統", onyomi: "tou", kunyomi: "su(beru)", meaning: "overall, relationship, ruling, governing" },
  { kanji: "洗", onyomi: "sen", kunyomi: "ara(u)", meaning: "wash, inquire into, probe" },
  { kanji: "駅", onyomi: "eki", kunyomi: "", meaning: "station" },
  { kanji: "救", onyomi: "kyuu", kunyomi: "suku(u)", meaning: "salvation, save, help, rescue, reclaim" },
  { kanji: "浴", onyomi: "yoku", kunyomi: "a(biru)", meaning: "bathe, be favored with, bask in" },
  { kanji: "老", onyomi: "rou", kunyomi: "o(iru), fuke(ru)", meaning: "old man, old age, grow old" },
  { kanji: "郷", onyomi: "kyou, gou", kunyomi: "sato", meaning: "home town, village, native place, district" },
  { kanji: "針", onyomi: "shin", kunyomi: "hari", meaning: "needle, pin, staple, stinger" },
  { kanji: "獄", onyomi: "goku", kunyomi: "", meaning: "prison, jail" },
  { kanji: "鎖", onyomi: "sa", kunyomi: "kusari", meaning: "chain, irons, connection" },
  { kanji: "締", onyomi: "tei", kunyomi: "shi(meru)", meaning: "tighten, tie, shut, lock, fasten" },
  { kanji: "豆", onyomi: "tou, zu", kunyomi: "mame", meaning: "beans, pea, midget" },
  { kanji: "陛", onyomi: "hei", kunyomi: "", meaning: "highness, steps (of throne)" },
  { kanji: "峰", onyomi: "hou", kunyomi: "mine", meaning: "summit, peak" },
  { kanji: "圧", onyomi: "atsu", kunyomi: "", meaning: "pressure, push, overwhelm, oppress, dominate" },
  { kanji: "砲", onyomi: "hou", kunyomi: "", meaning: "cannon, gun" },
  { kanji: "丘", onyomi: "kyuu", kunyomi: "oka", meaning: "hill, knoll" },
  { kanji: "坑", onyomi: "kou", kunyomi: "", meaning: "pit, hole" },
  { kanji: "拡", onyomi: "kaku", kunyomi: "", meaning: "broaden, extend, expand, enlarge" },
  { kanji: "契", onyomi: "kei", kunyomi: "", meaning: "pledge, promise, vow" },
  { kanji: "捨", onyomi: "sha", kunyomi: "su(teru)", meaning: "discard, throw away, abandon, resign, reject, sacrifice" },
  { kanji: "探", onyomi: "tan", kunyomi: "saga(su)", meaning: "grope, search, look for" },
  { kanji: "揮", onyomi: "ki", kunyomi: "", meaning: "brandish, wave, wag, swing, shake" },
  { kanji: "描", onyomi: "byou", kunyomi: "ega(ku)", meaning: "sketch, compose, write, draw, paint" },
  { kanji: "操", onyomi: "sou", kunyomi: "misao, ayatsu(ru)", meaning: "maneuver, manipulate, operate, steer, chastity, virginity, fidelity" },
  { kanji: "敬", onyomi: "kei", kunyomi: "uyama(u)", meaning: "awe, respect, honor, revere" },
  { kanji: "景", onyomi: "kei", kunyomi: "", meaning: "scenery, view" },
  { kanji: "縮", onyomi: "shuku", kunyomi: "chidi(mu), chida(maru)", meaning: "shrink, contract, shrivel, wrinkle, reduce" },
  { kanji: "端", onyomi: "tan", kunyomi: "hata, hashi", meaning: "edge, origin, end, point, border, verge, cape" },
  { kanji: "維", onyomi: "i", kunyomi: "", meaning: "fiber, tie, rope" },
  { kanji: "絶", onyomi: "zetsu", kunyomi: "ta(eru)", meaning: "discontinue, beyond, sever, cut off, abstain, interrupt, suppress" },
  { kanji: "抱", onyomi: "hou", kunyomi: "da(ku), ida(ku)", meaning: "embrace, hug, hold in arms" },
  { kanji: "慎", onyomi: "shin", kunyomi: "tsutsushi(mu)", meaning: "humility, be careful, discrete, prudent" },
  { kanji: "踊", onyomi: "you", kunyomi: "odo(ru)", meaning: "jump, dance, leap, skip" },
  { kanji: "紀", onyomi: "ki", kunyomi: "", meaning: "chronicle, account, narrative, history, annals, geologic period" },
  { kanji: "策", onyomi: "saku", kunyomi: "", meaning: "scheme, plan, policy, step, means" },
  { kanji: "継", onyomi: "kei", kunyomi: "tsu(gu)", meaning: "inherit, succeed, continue, patch, graft (tree)" },
  { kanji: "腰", onyomi: "you", kunyomi: "koshi", meaning: "loins, hips, waist, low wainscoting" },
  { kanji: "塩", onyomi: "en", kunyomi: "shio", meaning: "salt" },
  { kanji: "騒", onyomi: "sou", kunyomi: "sawa(gu)", meaning: "boisterous, make noise, clamor, disturb, excite" },
  { kanji: "黄", onyomi: "ou, kou", kunyomi: "ki", meaning: "yellow" },
  { kanji: "磁", onyomi: "ji", kunyomi: "", meaning: "magnet, porcelain" },
  { kanji: "典", onyomi: "ten", kunyomi: "", meaning: "code, ceremony, law, rule" },
  { kanji: "賓", onyomi: "hin", kunyomi: "", meaning: "VIP, guest" },
  { kanji: "干", onyomi: "kan", kunyomi: "ho(su), hoshi-", meaning: "dry, parch, ebb, recede, interfere, intercede" },
  { kanji: "輩", onyomi: "hai", kunyomi: "yakara", meaning: "comrade, fellow, people, companions" },
  { kanji: "忘", onyomi: "bou", kunyomi: "wasu(reru)", meaning: "forget" },
  { kanji: "盛", onyomi: "sei, jou", kunyomi: "mo(ru), saka(ru)", meaning: "boom, prosper, copulate" },
  { kanji: "血", onyomi: "ketsu", kunyomi: "chi", meaning: "blood" },
  { kanji: "沿", onyomi: "en", kunyomi: "so(u)", meaning: "run alongside, follow along, run along, lie along" },
  { kanji: "紅", onyomi: "kou, ku", kunyomi: "beni", meaning: "crimson, deep red" },
  { kanji: "背", onyomi: "hai", kunyomi: "se, somu(ku)", meaning: "stature, height, back, behind, disobey, defy, go back on, rebel" },
  { kanji: "肺", onyomi: "hai", kunyomi: "", meaning: "lungs" },
  { kanji: "革", onyomi: "kaku", kunyomi: "kawa", meaning: "leather, become serious, hide, pelt" },
  { kanji: "獣", onyomi: "juu", kunyomi: "kemono", meaning: "animal, beast" },
  { kanji: "縄", onyomi: "jou", kunyomi: "nawa", meaning: "straw rope, cord" },
  { kanji: "汗", onyomi: "kan", kunyomi: "ase", meaning: "sweat, perspire" },
  { kanji: "銅", onyomi: "dou", kunyomi: "", meaning: "copper" },
  { kanji: "湿", onyomi: "shitsu", kunyomi: "shime(ru)", meaning: "damp, wet, moist" },
  { kanji: "瓶", onyomi: "bin", kunyomi: "", meaning: "bottle, vial, jar, jug, vat, urn" },
  { kanji: "咲", onyomi: "shou", kunyomi: "sa(ku)", meaning: "blossom, bloom" },
  { kanji: "召", onyomi: "shou", kunyomi: "me(su)", meaning: "seduce, call, send for, wear, put on, ride in, buy, eat, drink, catch (cold)" },
  { kanji: "缶", onyomi: "kan", kunyomi: "", meaning: "can, container, jar radical (no. 121)" },
  { kanji: "隻", onyomi: "seki", kunyomi: "", meaning: "vessels, counter for ships, fish, birds, arrows, one of a pair" },
  { kanji: "脈", onyomi: "myaku", kunyomi: "", meaning: "vein, pulse, hope" },
  { kanji: "滑", onyomi: "katsu, kotsu", kunyomi: "sube(ru), name(raka)", meaning: "slippery, slide, slip, flunk" },
  { kanji: "孝", onyomi: "kou", kunyomi: "", meaning: "filial piety, child's respect" },
  { kanji: "巣", onyomi: "sou", kunyomi: "su", meaning: "nest, rookery, hive, cobweb, den" },
  { kanji: "浅", onyomi: "sen", kunyomi: "asa(i)", meaning: "shallow, superficial, frivolous, wretched, shameful" },
  { kanji: "漬", onyomi: "shi", kunyomi: "tsuke", meaning: "pickling, soak, moisten" },
  { kanji: "糖", onyomi: "tou", kunyomi: "", meaning: "sugar" },
  { kanji: "康", onyomi: "kou", kunyomi: "", meaning: "ease, peace" },
  { kanji: "舞", onyomi: "bu", kunyomi: "ma(u)", meaning: "dance, flit, circle, wheel" },
  { kanji: "掃", onyomi: "sou", kunyomi: "ha(ku)", meaning: "sweep, brush" },
  { kanji: "雄", onyomi: "yuu", kunyomi: "o-, osu", meaning: "masculine, male, hero, leader, superiority, excellence" },
  { kanji: "雌", onyomi: "shi", kunyomi: "mesu, me-", meaning: "feminine, female" },
  { kanji: "寝", onyomi: "shin", kunyomi: "ne(ru)", meaning: "lie down, sleep, rest, bed, remain unsold" },
  { kanji: "暖", onyomi: "dan", kunyomi: "atata(ka)", meaning: "warmth" },
  { kanji: "机", onyomi: "ki", kunyomi: "tsukue", meaning: "desk, table" },
  { kanji: "秘", onyomi: "hi", kunyomi: "", meaning: "secret, conceal" },
  { kanji: "軸", onyomi: "jiku", kunyomi: "", meaning: "axis, pivot, stem, stalk, counter for picture scrolls" },
  { kanji: "腕", onyomi: "wan", kunyomi: "ude", meaning: "arm, ability, talent" },
  { kanji: "紙", onyomi: "shi", kunyomi: "kami", meaning: "paper" },
  { kanji: "展", onyomi: "ten", kunyomi: "", meaning: "unfold, expand" },
  { kanji: "繁", onyomi: "han", kunyomi: "shige(ru)", meaning: "luxuriant, thick, overgrown, frequency, complexity, trouble" },
  { kanji: "範", onyomi: "han", kunyomi: "", meaning: "pattern, example, model" },
  { kanji: "弾", onyomi: "dan", kunyomi: "hazu(mu), tama", meaning: "bullet, twang, flip, snap" },
  { kanji: "圏", onyomi: "ken", kunyomi: "", meaning: "sphere, circle, radius, range" },
  { kanji: "揺", onyomi: "you", kunyomi: "yu(reru)", meaning: "swing, shake, sway, rock, tremble, vibrate" },
  { kanji: "玉", onyomi: "gyoku", kunyomi: "tama", meaning: "jewel, ball" },
  { kanji: "頻", onyomi: "hin", kunyomi: "shiki(ri)", meaning: "repeatedly, recur" },
  { kanji: "狙", onyomi: "so", kunyomi: "nera(u)", meaning: "aim at, sight on, shadow, stalk" },
  { kanji: "床", onyomi: "shou", kunyomi: "toko, yuka", meaning: "bed, counter for beds, floor, padding, tatami" },
  { kanji: "亀", onyomi: "ki", kunyomi: "kame", meaning: "tortoise, turtle" },
  { kanji: "束", onyomi: "soku", kunyomi: "taba", meaning: "bundle, sheaf, ream, tie in bundles, govern, manage, control" },
  { kanji: "毒", onyomi: "doku", kunyomi: "", meaning: "poison, virus, venom, germ, harm, injury, spite" },
  { kanji: "述", onyomi: "jutsu", kunyomi: "no(beru)", meaning: "mention, state, speak, relate" },
  { kanji: "江", onyomi: "kou", kunyomi: "e", meaning: "creek, inlet, bay" },
  { kanji: "壁", onyomi: "heki", kunyomi: "kabe", meaning: "wall, lining (stomach), fence" },
  { kanji: "避", onyomi: "hi", kunyomi: "sa(keru)", meaning: "evade, avoid, avert, ward off, shirk, shun" },
  { kanji: "房", onyomi: "bou", kunyomi: "fusa", meaning: "tassel, tuft, fringe, bunch, lock (hair), segment (orange), house, room" },
  { kanji: "養", onyomi: "you", kunyomi: "yashina(u)", meaning: "foster, bring up, rear, develop, nurture" },
  { kanji: "衛", onyomi: "ei", kunyomi: "", meaning: "defense, protection" },
  { kanji: "径", onyomi: "kei", kunyomi: "", meaning: "diameter, path, method" },
  { kanji: "貨", onyomi: "ka", kunyomi: "", meaning: "freight, goods, property" },
  { kanji: "塚", onyomi: "chou", kunyomi: "tsuka", meaning: "hillock, mound" },
  { kanji: "幹", onyomi: "kan", kunyomi: "miki", meaning: "tree trunk" },
  { kanji: "湾", onyomi: "wan", kunyomi: "", meaning: "gulf, bay, inlet" },
  { kanji: "巻", onyomi: "kan", kunyomi: "ma(ku)", meaning: "scroll, volume, book, part, roll up, wind up, tie, coil, counter for texts (or book scrolls)" },
  { kanji: "頂", onyomi: "chou", kunyomi: "itadaki", meaning: "place on the head, receive, top of head, top, summit, peak" },
  { kanji: "箱", onyomi: "hako", kunyomi: "", meaning: "box, chest, case, bin, railway car" },
  { kanji: "偉", onyomi: "i", kunyomi: "era(i)", meaning: "admirable, greatness, remarkable, conceited, famous, excellent" },
  { kanji: "歴", onyomi: "reki", kunyomi: "", meaning: "curriculum, continuation, passage of time" },
  { kanji: "避", onyomi: "hi", kunyomi: "sa(keru)", meaning: "evade, avoid, avert, ward off, shirk, shun" },
  { kanji: "穴", onyomi: "ketsu", kunyomi: "ana", meaning: "hole, aperture, slit, cave, den" },
  { kanji: "忙", onyomi: "bou", kunyomi: "isoga(shii)", meaning: "busy, occupied, restless" },
  { kanji: "扱", onyomi: "atsu", kunyomi: "atsu(kau)", meaning: "handle, deal with, dispose of, treat, entertain, receive guests" },
  { kanji: "皿", onyomi: "sara", kunyomi: "", meaning: "dish, a helping, plate" },
  { kanji: "恩", onyomi: "on", kunyomi: "", meaning: "grace, kindness, goodness, favor, mercy, blessing, benefit" },
  { kanji: "純", onyomi: "jun", kunyomi: "", meaning: "genuine, purity, innocence, net (profit)" },
  { kanji: "奪", onyomi: "datsu", kunyomi: "uba(u)", meaning: "rob, take by force, snatch away, dispossess, plunder, usurp" },
  { kanji: "既", onyomi: "ki", kunyomi: "sude(ni)", meaning: "previously, already, long ago" },
  { kanji: "刺", onyomi: "shi", kunyomi: "sa(su), toge", meaning: "thorn, pierce, stab, prick, sting, calling card" },
  { kanji: "筋", onyomi: "kin", kunyomi: "suji", meaning: "muscle, sinew, tendon, fiber, plot, plan, descent" },
  { kanji: "脳", onyomi: "nou", kunyomi: "", meaning: "brain, memory" },
  { kanji: "液", onyomi: "eki", kunyomi: "", meaning: "fluid, liquid, juice, sap, secretion" },
  { kanji: "冷", onyomi: "rei", kunyomi: "tsume(tai), hi(eru)", meaning: "cool, cold (beer, person), chill" },
  { kanji: "駐", onyomi: "chuu", kunyomi: "", meaning: "stop-over, reside in, resident" },
  { kanji: "弱", onyomi: "jaku", kunyomi: "yowa(i)", meaning: "weak, frail" },
  { kanji: "紹", onyomi: "shou", kunyomi: "", meaning: "introduce, inherit, help" },
  { kanji: "雇", onyomi: "ko", kunyomi: "yato(u)", meaning: "employ, hire" },
  { kanji: "替", onyomi: "tai", kunyomi: "ka(eru)", meaning: "exchange, spare, substitute, per-" },
  { kanji: "預", onyomi: "yo", kunyomi: "azu(keru)", meaning: "deposit, custody, leave with, entrust to" },
  { kanji: "焼", onyomi: "shou", kunyomi: "ya(ku)", meaning: "bake, burning" },
  { kanji: "簡", onyomi: "kan", kunyomi: "", meaning: "simplicity, brevity" },
  { kanji: "章", onyomi: "shou", kunyomi: "", meaning: "badge, chapter, composition, poem, design" },
  { kanji: "臓", onyomi: "zou", kunyomi: "", meaning: "entrails, viscera, bowels" },
  { kanji: "律", onyomi: "ritsu, richi", kunyomi: "", meaning: "rhythm, law, regulation, gauge, control" },
  { kanji: "贈", onyomi: "zou, sou", kunyomi: "oku(ru)", meaning: "presents, send, give to, award to, confer on, presenting something" },
  { kanji: "照", onyomi: "shou", kunyomi: "te(ru)", meaning: "illuminate, shine, compare, bashful" },
  { kanji: "薄", onyomi: "haku", kunyomi: "usu(i)", meaning: "dilute, thin, weak (tea), pampas grass" },
  { kanji: "群", onyomi: "gun", kunyomi: "mu(re), mura(garu)", meaning: "flock, group, crowd, herd, swarm, cluster" },
  { kanji: "秋", onyomi: "shuu", kunyomi: "aki", meaning: "autumn" },
  { kanji: "趣", onyomi: "shu", kunyomi: "omomuki", meaning: "purport, gist, elegance, interest, proceed to, tend, become" },
  { kanji: "渡", onyomi: "to", kunyomi: "wata(ru)", meaning: "transit, ford, ferry, cross, import, deliver, diameter, migrate" },
  { kanji: "惜", onyomi: "seki", kunyomi: "o(shii)", meaning: "pity, be sparing of, frugal, stingy, regret" },
  { kanji: "索", onyomi: "saku", kunyomi: "", meaning: "cord, rope, searching, inquiring" },
  { kanji: "誘", onyomi: "yuu", kunyomi: "saso(u)", meaning: "entice, lead, tempt, invite, ask, call for, seduce, allure" },
  { kanji: "勇", onyomi: "yuu", kunyomi: "isa(mu)", meaning: "courage, cheer up, be in high spirits, bravery, heroism" },
  { kanji: "械", onyomi: "kai", kunyomi: "", meaning: "contraption, fetter, machine, instrument" },
  { kanji: "菓", onyomi: "ka", kunyomi: "", meaning: "candy, cakes, fruit" },
  { kanji: "砂", onyomi: "sa, sha", kunyomi: "suna", meaning: "sand" },
  { kanji: "漏", onyomi: "rou", kunyomi: "mo(ru)", meaning: "leak, escape, time" },
  { kanji: "災", onyomi: "sai", kunyomi: "wazawa(i)", meaning: "disaster, calamity, woe, curse, evil" },
  { kanji: "舟", onyomi: "shuu", kunyomi: "fune", meaning: "boat, ship" },
  { kanji: "礎", onyomi: "so", kunyomi: "ishizue", meaning: "cornerstone, foundation stone" },
  { kanji: "慰", onyomi: "i", kunyomi: "nagusa(meru)", meaning: "consolation, amusement, seduce, cheer, make sport of, comfort, console" },
  { kanji: "愉", onyomi: "yu", kunyomi: "tanoshi(i)", meaning: "pleasure, happy, rejoice" },
  { kanji: "掘", onyomi: "kutsu", kunyomi: "ho(ru)", meaning: "dig, delve, excavate" },
  { kanji: "珍", onyomi: "chin", kunyomi: "mezura(shii)", meaning: "rare, curious, strange" },
  { kanji: "敷", onyomi: "fu", kunyomi: "shi(ku)", meaning: "spread, pave, sit, promulgate" },
  { kanji: "析", onyomi: "seki", kunyomi: "", meaning: "chop, divide, tear, analyze" },
  { kanji: "捜", onyomi: "sou", kunyomi: "saga(su)", meaning: "search, look for, locate" },
  { kanji: "荒", onyomi: "kou", kunyomi: "ara(i), a(reru)", meaning: "laid waste, rough, rude, wild" },
  { kanji: "咽", onyomi: "in, etsu", kunyomi: "nodo", meaning: "throat, choked, smothered, stuffy" }
];