export interface KanjiData {
  kanji: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
}

export const N2_KANJI: KanjiData[] = [
  { kanji: "党", onyomi: "とう", kunyomi: "", meaning: "party, faction, clique" },
  { kanji: "協", onyomi: "きょう", kunyomi: "", meaning: "co-, cooperation" },
  { kanji: "総", onyomi: "そう", kunyomi: "すべ（て）、ふさ", meaning: "general, whole, all, full, total" },
  { kanji: "区", onyomi: "く", kunyomi: "", meaning: "ward, district" },
  { kanji: "領", onyomi: "りょう", kunyomi: "", meaning: "territory, dominion, province" },
  { kanji: "県", onyomi: "けん", kunyomi: "", meaning: "prefecture" },
  { kanji: "設", onyomi: "せつ", kunyomi: "もう（ける）", meaning: "establishment, provision, prepare" },
  { kanji: "改", onyomi: "かい", kunyomi: "あらた（める）、あらた（まる）", meaning: "reformation, change, modify, mend, renew, examine, inspect, search" },
  { kanji: "府", onyomi: "ふ", kunyomi: "", meaning: "urban prefecture, government office, representative body, storehouse" },
  { kanji: "査", onyomi: "さ", kunyomi: "", meaning: "investigate, examine" },
  { kanji: "委", onyomi: "い", kunyomi: "ゆだ（ねる）", meaning: "committee, entrust to, leave to, devote, discard" },
  { kanji: "軍", onyomi: "ぐん", kunyomi: "", meaning: "army, force, troops, war, battle" },
  { kanji: "団", onyomi: "だん", kunyomi: "", meaning: "group, association" },
  { kanji: "各", onyomi: "かく", kunyomi: "おのおの", meaning: "each, every, either" },
  { kanji: "島", onyomi: "とう", kunyomi: "しま", meaning: "island" },
  { kanji: "革", onyomi: "かく", kunyomi: "かわ", meaning: "leather, become serious, hide, pelt" },
  { kanji: "村", onyomi: "そん", kunyomi: "むら", meaning: "village, town" },
  { kanji: "勢", onyomi: "せい、ぜい", kunyomi: "いきお（い）", meaning: "forces, energy, military strength" },
  { kanji: "減", onyomi: "げん", kunyomi: "へ（る）、へ（らす）", meaning: "dwindle, decrease, reduce, decline, curtail, get hungry" },
  { kanji: "未", onyomi: "み、び", kunyomi: "ま（だ）", meaning: "not yet, hitherto, still, even now, sign of the ram" },
  { kanji: "跡", onyomi: "せき", kunyomi: "あと", meaning: "tracks, mark, print, impression" },
  { kanji: "妻", onyomi: "さい", kunyomi: "つま", meaning: "wife, spouse" },
  { kanji: "旧", onyomi: "きゅう", kunyomi: "ふる（い）", meaning: "old times, old things, old friend, former, ex-" },
  { kanji: "夫", onyomi: "ふ、ふう", kunyomi: "おっと", meaning: "husband, man" },
  { kanji: "混", onyomi: "こん", kunyomi: "ま（ざる）、こ（む）", meaning: "mix, blend, confuse" },
  { kanji: "雲", onyomi: "うん", kunyomi: "くも", meaning: "cloud" },
  { kanji: "祭", onyomi: "さい", kunyomi: "まつ（る）", meaning: "ritual, offer prayers, celebrate, deify, enshrine, worship" },
  { kanji: "司", onyomi: "し", kunyomi: "つかさ（どる）", meaning: "director, official, govt office, rule, administer" },
  { kanji: "観", onyomi: "かん", kunyomi: "み（る）", meaning: "outlook, look, appearance, condition, view" },
  { kanji: "調", onyomi: "ちょう", kunyomi: "しら（べる）、ととの（う）", meaning: "tune, tone, meter, key (music), writing style, prepare, exorcise, investigate" },
  { kanji: "都", onyomi: "と、つ", kunyomi: "みやこ", meaning: "metropolis, capital" },
  { kanji: "費", onyomi: "ひ", kunyomi: "つい（やす）", meaning: "expense, cost, spend, consume, waste" },
  { kanji: "打", onyomi: "だ", kunyomi: "う（つ）", meaning: "strike, hit, knock, pound, dozen" },
  { kanji: "職", onyomi: "しょく", kunyomi: "", meaning: "post, employment, work" },
  { kanji: "築", onyomi: "ちく", kunyomi: "きず（く）", meaning: "fabricate, build, construct" },
  { kanji: "居", onyomi: "きょ", kunyomi: "い（る）、お（る）", meaning: "reside, to be, exist, live with" },
  { kanji: "群", onyomi: "ぐん", kunyomi: "む（れ）、むら（がる）", meaning: "flock, group, crowd, herd, swarm, cluster" },
  { kanji: "録", onyomi: "ろく", kunyomi: "", meaning: "record" },
  { kanji: "導", onyomi: "どう", kunyomi: "みちび（く）", meaning: "guidance, leading, conduct, usher" },
  { kanji: "順", onyomi: "じゅん", kunyomi: "", meaning: "obey, order, turn, right, docility, occasion" },
  { kanji: "負", onyomi: "ふ", kunyomi: "ま（ける）、お（う）", meaning: "defeat, negative, minus, bear, owe, assume a responsibility" },
  { kanji: "井", onyomi: "せい、しょう", kunyomi: "い", meaning: "well, well crib, town, community" },
  { kanji: "酒", onyomi: "しゅ", kunyomi: "さけ", meaning: "sake, alcohol" },
  { kanji: "落", onyomi: "らく", kunyomi: "お（ちる）、お（とす）", meaning: "fall, drop, come down, village, hamlet" },
  { kanji: "差", onyomi: "さ", kunyomi: "さ（す）", meaning: "distinction, difference, variation, discrepancy, margin, balance" },
  { kanji: "規", onyomi: "き", kunyomi: "", meaning: "standard, measure" },
  { kanji: "秒", onyomi: "びょう", kunyomi: "", meaning: "second, moment" },
  { kanji: "笑", onyomi: "しょう", kunyomi: "わら（う）、え（む）", meaning: "laugh" },
  { kanji: "議", onyomi: "ぎ", kunyomi: "", meaning: "deliberation, consultation, debate, consideration" },
  { kanji: "席", onyomi: "せき", kunyomi: "", meaning: "seat, mat, occasion, place" },
  { kanji: "警", onyomi: "けい", kunyomi: "いまし（める）", meaning: "admonish, commandment" },
  { kanji: "護", onyomi: "ご", kunyomi: "まも（る）", meaning: "safeguard, protect" },
  { kanji: "災", onyomi: "さい", kunyomi: "わざわ（い）", meaning: "disaster, calamity, woe, curse, evil" },
  { kanji: "副", onyomi: "ふく", kunyomi: "", meaning: "vice-, assistant, aide, duplicate, copy" },
  { kanji: "唱", onyomi: "しょう", kunyomi: "とな（える）", meaning: "chant, recite, call upon, yell" },
  { kanji: "士", onyomi: "し", kunyomi: "さむらい", meaning: "gentleman, scholar, samurai, samurai radical (no. 33)" },
  { kanji: "治", onyomi: "じ、ち", kunyomi: "おさ（める）、なお（る）", meaning: "reign, be at peace, calm down, subdue, quell, govt, cure, heal, rule, conserve" },
  { kanji: "準", onyomi: "じゅん", kunyomi: "", meaning: "semi-, correspond to, proportionate to, conform, imitate" },
  { kanji: "賞", onyomi: "しょう", kunyomi: "", meaning: "prize, reward, praise" },
  { kanji: "辞", onyomi: "じ", kunyomi: "や（める）", meaning: "resign, word, term, expression" },
  { kanji: "乗", onyomi: "じょう", kunyomi: "の（る）", meaning: "ride, power, multiplication, record, counter for vehicles, board, mount, join" },
  { kanji: "満", onyomi: "まん", kunyomi: "み（ちる）、み（たす）", meaning: "full, fullness, enough, satisfy" },
  { kanji: "率", onyomi: "りつ、そつ", kunyomi: "ひき（いる）", meaning: "ratio, rate, proportion, percentage, coefficient, factor" },
  { kanji: "承", onyomi: "しょう", kunyomi: "うけたまわ（る）", meaning: "acquiesce, hear, listen to, be informed, receive" },
  { kanji: "角", onyomi: "かく", kunyomi: "かど、つの", meaning: "angle, corner, square, horn, antlers" },
  { kanji: "停", onyomi: "てい", kunyomi: "と（める）", meaning: "halt, stopping" },
  { kanji: "株", onyomi: "しゅ", kunyomi: "かぶ", meaning: "stocks, stump, shares, stock, counter for small plants" },
  { kanji: "競", onyomi: "きょう、けい", kunyomi: "きそ（う）、せ（る）", meaning: "emulate, compete with, bid, sell at auction, bout, contest, race" },
  { kanji: "推", onyomi: "すい", kunyomi: "お（す）", meaning: "conjecture, infer, guess, suppose, support" },
  { kanji: "易", onyomi: "えき、い", kunyomi: "やさ（しい）", meaning: "easy, ready to, simple, fortune-telling, divination" },
  { kanji: "財", onyomi: "ざい、さい", kunyomi: "", meaning: "property, money, wealth, assets" },
  { kanji: "技", onyomi: "ぎ", kunyomi: "わざ", meaning: "skill, art, craft, ability, feat, performance, vocation, arts" },
  { kanji: "低", onyomi: "てい", kunyomi: "ひく（い）", meaning: "lower, short, humble" },
  { kanji: "裁", onyomi: "さい", kunyomi: "さば（く）", meaning: "tailor, judge, decision, cut out (pattern)" },
  { kanji: "権", onyomi: "けん、ごん", kunyomi: "", meaning: "authority, power, rights" },
  { kanji: "鉄", onyomi: "てつ", kunyomi: "", meaning: "iron" },
  { kanji: "価", onyomi: "か", kunyomi: "あたい", meaning: "value, price" },
  { kanji: "判", onyomi: "はん、ばん", kunyomi: "", meaning: "judgement, signature, stamp, seal" },
  { kanji: "易", onyomi: "えき、い", kunyomi: "やさ（しい）", meaning: "easy, ready to, simple, fortune-telling, divination" },
  { kanji: "河", onyomi: "か", kunyomi: "かわ", meaning: "river" },
  { kanji: "択", onyomi: "たく", kunyomi: "", meaning: "choose, select, elect, prefer" },
  { kanji: "老", onyomi: "ろう", kunyomi: "お（いる）、ふ（ける）", meaning: "old man, old age, grow old" },
  { kanji: "講", onyomi: "こう", kunyomi: "", meaning: "lecture, club, association" },
  { kanji: "謝", onyomi: "しゃ", kunyomi: "あやま（る）", meaning: "apologize, thank, refuse" },
  { kanji: "浮", onyomi: "ふ", kunyomi: "う（く）、う（かる）", meaning: "floating, float, rise to surface" },
  { kanji: "録", onyomi: "ろく", kunyomi: "", meaning: "record" },
  { kanji: "城", onyomi: "じょう", kunyomi: "しろ", meaning: "castle" },
  { kanji: "疑", onyomi: "ぎ", kunyomi: "うたが（う）", meaning: "doubt, distrust, be suspicious, question" },
  { kanji: "露", onyomi: "ろ、ろう", kunyomi: "つゆ", meaning: "dew, tears, expose, Russia" },
  { kanji: "修", onyomi: "しゅう", kunyomi: "おさ（める）", meaning: "discipline, conduct oneself well, study, master" },
  { kanji: "豊", onyomi: "ほう", kunyomi: "ゆた（か）", meaning: "bountiful, excellent, rich" },
  { kanji: "械", onyomi: "かい", kunyomi: "", meaning: "contraption, fetter, machine, instrument" },
  { kanji: "故", onyomi: "こ", kunyomi: "ゆえ", meaning: "happenstance, especially, intentionally, reason, cause, circumstances, the late, therefore, consequently" },
  { kanji: "科", onyomi: "か", kunyomi: "", meaning: "department, course, section" },
  { kanji: "報", onyomi: "ほう", kunyomi: "むく（いる）", meaning: "report, news, reward, retribution" },
  { kanji: "勤", onyomi: "きん、ごん", kunyomi: "つと（める）", meaning: "diligence, become employed, serve" },
  { kanji: "察", onyomi: "さつ", kunyomi: "", meaning: "guess, presume, surmise, judge, understand" },
  { kanji: "義", onyomi: "ぎ", kunyomi: "", meaning: "righteousness, justice, morality, honor, loyalty, meaning" },
  { kanji: "臣", onyomi: "しん、じん", kunyomi: "", meaning: "retainer, subject" },
  { kanji: "史", onyomi: "し", kunyomi: "", meaning: "history, chronicle" },
  { kanji: "装", onyomi: "そう、しょう", kunyomi: "よそ（う）", meaning: "attire, dress, pretend, disguise, profess" },
  { kanji: "営", onyomi: "えい", kunyomi: "いとな（む）", meaning: "camp, perform, build, conduct (business)" },
  { kanji: "視", onyomi: "し", kunyomi: "", meaning: "inspection, regard as, see, look at" },
  { kanji: "精", onyomi: "せい、しょう", kunyomi: "", meaning: "refined, ghost, fairy, energy, vitality, semen, excellence, purity, skill" },
  { kanji: "採", onyomi: "さい", kunyomi: "と（る）", meaning: "pick, take, fetch, take up" },
  { kanji: "章", onyomi: "しょう", kunyomi: "", meaning: "badge, chapter, composition, poem, design" },
  { kanji: "深", onyomi: "しん", kunyomi: "ふか（い）、ふ（ける）", meaning: "deep, heighten, intensify, strengthen" },
  { kanji: "律", onyomi: "りつ、りち", kunyomi: "", meaning: "rhythm, law, regulation, gauge, control" },
  { kanji: "告", onyomi: "こく", kunyomi: "つ（げる）", meaning: "revelation, tell, inform, announce" },
  { kanji: "格", onyomi: "かく、こう", kunyomi: "", meaning: "status, rank, capacity, character, case (law, grammar)" },
  { kanji: "派", onyomi: "は", kunyomi: "", meaning: "faction, group, party, clique, sect, school" },
  { kanji: "志", onyomi: "し", kunyomi: "こころざし", meaning: "intention, plan, resolve, aspire, motive, hopes, shilling" },
  { kanji: "環", onyomi: "かん", kunyomi: "わ", meaning: "ring, circle, link, wheel" },
  { kanji: "複", onyomi: "ふく", kunyomi: "", meaning: "duplicate, double, compound, multiple" },
  { kanji: "雑", onyomi: "ざつ、ぞう", kunyomi: "", meaning: "miscellaneous" },
  { kanji: "木", onyomi: "ぼく、もく", kunyomi: "き、こ", meaning: "tree, wood" },
  { kanji: "編", onyomi: "へん", kunyomi: "あ（む）", meaning: "compilation, knit, plait, braid, twist, editing, completed poem, part of a book" },
  { kanji: "増", onyomi: "ぞう", kunyomi: "ま（す）、ふ（える）", meaning: "increase, add, augment, gain, promote" },
  { kanji: "減", onyomi: "げん", kunyomi: "へ（る）、へ（らす）", meaning: "dwindle, decrease, reduce, decline, curtail, get hungry" },
  { kanji: "師", onyomi: "し", kunyomi: "", meaning: "expert, teacher, master, model, exemplar, army (incl. counter), war" },
  { kanji: "算", onyomi: "さん", kunyomi: "", meaning: "calculate, divining, number, abacus, probability" },
  { kanji: "票", onyomi: "ひょう", kunyomi: "", meaning: "ballot, label, ticket, sign" },
  { kanji: "宗", onyomi: "しゅう、そう", kunyomi: "", meaning: "religion, sect, denomination, main point, origin, essence" },
  { kanji: "宙", onyomi: "ちゅう", kunyomi: "", meaning: "mid-air, air, space, sky, memorization, interval of time" },
  { kanji: "宇", onyomi: "う", kunyomi: "", meaning: "eaves, roof, house, heaven" },
  { kanji: "宅", onyomi: "たく", kunyomi: "", meaning: "home, house, residence, our house, my husband" },
  { kanji: "守", onyomi: "しゅ、す", kunyomi: "まも（る）、も（り）", meaning: "guard, protect, defend, obey" },
  { kanji: "宮", onyomi: "きゅう、ぐう", kunyomi: "みや", meaning: "Shinto shrine, constellations, palace, princess" },
  { kanji: "密", onyomi: "みつ", kunyomi: "", meaning: "secrecy, density (pop), minuteness, carefulness" },
  { kanji: "康", onyomi: "こう", kunyomi: "", meaning: "ease, peace" },
  { kanji: "害", onyomi: "がい", kunyomi: "", meaning: "harm, injury" },
  { kanji: "容", onyomi: "よう", kunyomi: "", meaning: "contain, form, looks" },
  { kanji: "寄", onyomi: "き", kunyomi: "よ（る）", meaning: "draw near, stop in, bring near, gather, collect, send, forward" },
  { kanji: "富", onyomi: "ふ、ふう", kunyomi: "と（む）", meaning: "wealth, enrich, abundant" },
  { kanji: "導", onyomi: "どう", kunyomi: "みちび（く）", meaning: "guidance, leading, conduct, usher" },
  { kanji: "居", onyomi: "きょ", kunyomi: "い（る）、お（る）", meaning: "reside, to be, exist, live with" },
  { kanji: "届", onyomi: "かい", kunyomi: "とど（く）", meaning: "deliver, reach, arrive, report, notify, forward" },
  { kanji: "層", onyomi: "そう", kunyomi: "", meaning: "stratum, social class, layer, story, floor" },
  { kanji: "局", onyomi: "きょく", kunyomi: "", meaning: "bureau, board, office, affair, conclusion, court lady, lady-in-waiting, her apartment" },
  { kanji: "属", onyomi: "ぞく", kunyomi: "", meaning: "belong, genus, subordinate official, affiliated" },
  { kanji: "布", onyomi: "ふ", kunyomi: "ぬの", meaning: "linen, cloth, spread, distribute" },
  { kanji: "座", onyomi: "ざ", kunyomi: "すわ（る）", meaning: "squat, seat, cushion, gathering, sit" },
  { kanji: "量", onyomi: "りょう", kunyomi: "はか（る）", meaning: "quantity, measure, weight, amount, consider, estimate, surmise" },
  { kanji: "捕", onyomi: "ほ", kunyomi: "と（る）、つか（まる）", meaning: "catch, capture" },
  { kanji: "破", onyomi: "は", kunyomi: "やぶ（る）", meaning: "rend, rip, tear, break, destroy, defeat, frustrate" },
  { kanji: "述", onyomi: "じゅつ", kunyomi: "の（べる）", meaning: "mention, state, speak, relate" },
  { kanji: "標", onyomi: "ひょう", kunyomi: "", meaning: "signpost, seal, mark, stamp, imprint, symbol, emblem, trademark, evidence, souvenir, target" },
  { kanji: "性", onyomi: "せい、しょう", kunyomi: "", meaning: "sex, gender, nature" },
  { kanji: "処", onyomi: "しょ", kunyomi: "", meaning: "dispose, manage, deal with, sentence, condemn, act, behave, place" },
  { kanji: "太", onyomi: "たい、た", kunyomi: "ふと（い）", meaning: "plump, thick, big around" },
  { kanji: "件", onyomi: "けん", kunyomi: "", meaning: "affair, case, matter, item" },
  { kanji: "再", onyomi: "さい、さ", kunyomi: "ふたたび", meaning: "again, twice, second time" },
  { kanji: "販", onyomi: "はん", kunyomi: "", meaning: "marketing, sell, trade" },
  { kanji: "仏", onyomi: "ぶつ、ふつ", kunyomi: "ほとけ", meaning: "Buddha, the dead, France" },
  { kanji: "否", onyomi: "ひ", kunyomi: "いな", meaning: "negate, no, noes, refuse, decline, deny" },
  { kanji: "希", onyomi: "き", kunyomi: "まれ", meaning: "hope, beg, request, pray, beseech, Greece, dilute (acid), rare, few, phenomenal" },
  { kanji: "例", onyomi: "れい", kunyomi: "ためし", meaning: "example, custom, usage, precedent" },
  { kanji: "細", onyomi: "さい", kunyomi: "ほそ（い）", meaning: "dainty, get thin, taper, slender, narrow, detailed, precise" },
  { kanji: "織", onyomi: "しょく、しき", kunyomi: "お（る）", meaning: "weave, fabric" },
  { kanji: "約", onyomi: "やく", kunyomi: "", meaning: "promise, approximately, shrink" },
  { kanji: "型", onyomi: "けい", kunyomi: "かた", meaning: "mould, type, model" },
  { kanji: "姿", onyomi: "し", kunyomi: "すがた", meaning: "figure, form, shape" },
  { kanji: "余", onyomi: "よ", kunyomi: "あま（る）", meaning: "too much, myself, surplus, other, remainder" },
  { kanji: "欠", onyomi: "けつ", kunyomi: "か（く）", meaning: "lack, gap, fail, imperial storehouse" },
  { kanji: "吸", onyomi: "きゅう", kunyomi: "す（う）", meaning: "suck, imbibe, inhale, sip" },
  { kanji: "応", onyomi: "おう", kunyomi: "", meaning: "apply, answer, yes, OK, reply, accept" },
  { kanji: "快", onyomi: "かい", kunyomi: "こころよ（い）", meaning: "cheerful, pleasant, agreeable, comfortable" },
  { kanji: "技", onyomi: "ぎ", kunyomi: "わざ", meaning: "skill, art, craft, ability, feat, performance, vocation, arts" },
  { kanji: "伸", onyomi: "しん", kunyomi: "の（びる）、の（ばす）", meaning: "expand, stretch, extend, lengthen, increase" },
  { kanji: "恋", onyomi: "れん", kunyomi: "こい、こ（う）", meaning: "romance, in love, yearn for, miss, darling" },
  { kanji: "郵", onyomi: "ゆう", kunyomi: "", meaning: "mail, stagecoach stop" },
  { kanji: "幸", onyomi: "こう", kunyomi: "さいわ（い）、さち", meaning: "happiness, blessing, fortune" },
  { kanji: "決", onyomi: "けつ", kunyomi: "き（める）、き（まる）", meaning: "decide, fix, agree upon, appoint" },
  { kanji: "挙", onyomi: "きょ", kunyomi: "あ（げる）", meaning: "raise, plan, project, behavior, actions" },
  { kanji: "徳", onyomi: "とく", kunyomi: "", meaning: "benevolence, virtue, goodness, favor" },
  { kanji: "薬", onyomi: "やく", kunyomi: "くすり", meaning: "medicine, chemical, enamel, gunpowder, benefit" },
  { kanji: "額", onyomi: "がく", kunyomi: "ひたい", meaning: "forehead, tablet, plaque, framed picture, sum, amount, volume" },
  { kanji: "罪", onyomi: "ざい", kunyomi: "つみ", meaning: "guilt, sin, crime, fault, blame, offense" },
  { kanji: "賃", onyomi: "ちん", kunyomi: "", meaning: "fare, fee, hire, rent, wages, charge" },
  { kanji: "類", onyomi: "るい", kunyomi: "", meaning: "sort, kind, variety, class, genus" },
  { kanji: "官", onyomi: "かん", kunyomi: "", meaning: "bureaucrat, the government, organ" },
  { kanji: "借", onyomi: "しゃく", kunyomi: "か（りる）", meaning: "borrow, rent" },
  { kanji: "緒", onyomi: "しょ、ちょ", kunyomi: "お", meaning: "thong, beginning, inception, end, cord, strap, mental or emotional state" },
  { kanji: "縁", onyomi: "えん", kunyomi: "ふち", meaning: "affinity, relation, connection, edge, border, veranda, chance" },
  { kanji: "承", onyomi: "しょう", kunyomi: "うけたまわ（る）", meaning: "acquiesce, hear, listen to, be informed, receive" },
  { kanji: "狭", onyomi: "きょう", kunyomi: "せま（い）", meaning: "cramped, narrow, contract, tight" },
  { kanji: "税", onyomi: "ぜい", kunyomi: "", meaning: "tax, duty" },
  { kanji: "程", onyomi: "てい", kunyomi: "ほど", meaning: "extent, degree, law, formula, distance, limits, amount" },
  { kanji: "舎", onyomi: "しゃ", kunyomi: "", meaning: "cottage, inn, hut, house, mansion" },
  { kanji: "奥", onyomi: "おう", kunyomi: "おく", meaning: "heart, interior" },
  { kanji: "詰", onyomi: "きつ", kunyomi: "つ（める）", meaning: "packed, close, pressed, reprove, rebuke, blame" },
  { kanji: "替", onyomi: "たい", kunyomi: "か（える）", meaning: "exchange, spare, substitute, per-" },
  { kanji: "危", onyomi: "き", kunyomi: "あぶ（ない）", meaning: "dangerous, fear, uneasy" },
  { kanji: "刻", onyomi: "こく", kunyomi: "きざ（む）", meaning: "engrave, cut fine, chop, hash, mince, time, carving" },
  { kanji: "統", onyomi: "とう", kunyomi: "す（べる）", meaning: "overall, relationship, ruling, governing" },
  { kanji: "洗", onyomi: "せん", kunyomi: "あら（う）", meaning: "wash, inquire into, probe" },
  { kanji: "駅", onyomi: "えき", kunyomi: "", meaning: "station" },
  { kanji: "救", onyomi: "きゅう", kunyomi: "すく（う）", meaning: "salvation, save, help, rescue, reclaim" },
  { kanji: "浴", onyomi: "よく", kunyomi: "あ（びる）", meaning: "bathe, be favored with, bask in" },
  { kanji: "老", onyomi: "ろう", kunyomi: "お（いる）、ふ（ける）", meaning: "old man, old age, grow old" },
  { kanji: "郷", onyomi: "きょう、ごう", kunyomi: "さと", meaning: "home town, village, native place, district" },
  { kanji: "針", onyomi: "しん", kunyomi: "はり", meaning: "needle, pin, staple, stinger" },
  { kanji: "獄", onyomi: "ごく", kunyomi: "", meaning: "prison, jail" },
  { kanji: "鎖", onyomi: "さ", kunyomi: "くさり", meaning: "chain, irons, connection" },
  { kanji: "締", onyomi: "てい", kunyomi: "し（める）", meaning: "tighten, tie, shut, lock, fasten" },
  { kanji: "豆", onyomi: "とう、ず", kunyomi: "まめ", meaning: "beans, pea, midget" },
  { kanji: "陛", onyomi: "へい", kunyomi: "", meaning: "highness, steps (of throne)" },
  { kanji: "峰", onyomi: "ほう", kunyomi: "みね", meaning: "summit, peak" },
  { kanji: "圧", onyomi: "あつ", kunyomi: "", meaning: "pressure, push, overwhelm, oppress, dominate" },
  { kanji: "砲", onyomi: "ほう", kunyomi: "", meaning: "cannon, gun" },
  { kanji: "丘", onyomi: "きゅう", kunyomi: "おか", meaning: "hill, knoll" },
  { kanji: "坑", onyomi: "こう", kunyomi: "", meaning: "pit, hole" },
  { kanji: "拡", onyomi: "かく", kunyomi: "", meaning: "broaden, extend, expand, enlarge" },
  { kanji: "契", onyomi: "けい", kunyomi: "", meaning: "pledge, promise, vow" },
  { kanji: "捨", onyomi: "しゃ", kunyomi: "す（てる）", meaning: "discard, throw away, abandon, resign, reject, sacrifice" },
  { kanji: "探", onyomi: "たん", kunyomi: "さが（す）", meaning: "grope, search, look for" },
  { kanji: "揮", onyomi: "き", kunyomi: "", meaning: "brandish, wave, wag, swing, shake" },
  { kanji: "描", onyomi: "びょう", kunyomi: "えが（く）", meaning: "sketch, compose, write, draw, paint" },
  { kanji: "操", onyomi: "そう", kunyomi: "みさお、あやつ（る）", meaning: "maneuver, manipulate, operate, steer, chastity, virginity, fidelity" },
  { kanji: "敬", onyomi: "けい", kunyomi: "うやま（う）", meaning: "awe, respect, honor, revere" },
  { kanji: "景", onyomi: "けい", kunyomi: "", meaning: "scenery, view" },
  { kanji: "縮", onyomi: "しゅく", kunyomi: "ちぢ（む）、ちぢ（まる）", meaning: "shrink, contract, shrivel, wrinkle, reduce" },
  { kanji: "端", onyomi: "たん", kunyomi: "はた、はし", meaning: "edge, origin, end, point, border, verge, cape" },
  { kanji: "維", onyomi: "い", kunyomi: "", meaning: "fiber, tie, rope" },
  { kanji: "絶", onyomi: "ぜつ", kunyomi: "た（える）", meaning: "discontinue, beyond, sever, cut off, abstain, interrupt, suppress" },
  { kanji: "抱", onyomi: "ほう", kunyomi: "だ（く）、いだ（く）", meaning: "embrace, hug, hold in arms" },
  { kanji: "慎", onyomi: "しん", kunyomi: "つつし（む）", meaning: "humility, be careful, discrete, prudent" },
  { kanji: "踊", onyomi: "よう", kunyomi: "おど（る）", meaning: "jump, dance, leap, skip" },
  { kanji: "紀", onyomi: "き", kunyomi: "", meaning: "chronicle, account, narrative, history, annals, geologic period" },
  { kanji: "策", onyomi: "さく", kunyomi: "", meaning: "scheme, plan, policy, step, means" },
  { kanji: "継", onyomi: "けい", kunyomi: "つ（ぐ）", meaning: "inherit, succeed, continue, patch, graft (tree)" },
  { kanji: "腰", onyomi: "よう", kunyomi: "こし", meaning: "loins, hips, waist, low wainscoting" },
  { kanji: "塩", onyomi: "えん", kunyomi: "しお", meaning: "salt" },
  { kanji: "騒", onyomi: "そう", kunyomi: "さわ（ぐ）", meaning: "boisterous, make noise, clamor, disturb, excite" },
  { kanji: "黄", onyomi: "おう、こう", kunyomi: "き", meaning: "yellow" },
  { kanji: "磁", onyomi: "じ", kunyomi: "", meaning: "magnet, porcelain" },
  { kanji: "典", onyomi: "てん", kunyomi: "", meaning: "code, ceremony, law, rule" },
  { kanji: "賓", onyomi: "ひん", kunyomi: "", meaning: "VIP, guest" },
  { kanji: "干", onyomi: "かん", kunyomi: "ほ（す）、ほし-", meaning: "dry, parch, ebb, recede, interfere, intercede" },
  { kanji: "輩", onyomi: "はい", kunyomi: "やから", meaning: "comrade, fellow, people, companions" },
  { kanji: "忘", onyomi: "ぼう", kunyomi: "わす（れる）", meaning: "forget" },
  { kanji: "盛", onyomi: "せい、じょう", kunyomi: "も（る）、さか（る）", meaning: "boom, prosper, copulate" },
  { kanji: "血", onyomi: "けつ", kunyomi: "ち", meaning: "blood" },
  { kanji: "沿", onyomi: "えん", kunyomi: "そ（う）", meaning: "run alongside, follow along, run along, lie along" },
  { kanji: "紅", onyomi: "こう、く", kunyomi: "べに", meaning: "crimson, deep red" },
  { kanji: "背", onyomi: "はい", kunyomi: "せ、そむ（く）", meaning: "stature, height, back, behind, disobey, defy, go back on, rebel" },
  { kanji: "肺", onyomi: "はい", kunyomi: "", meaning: "lungs" },
  { kanji: "革", onyomi: "かく", kunyomi: "かわ", meaning: "leather, become serious, hide, pelt" },
  { kanji: "獣", onyomi: "じゅう", kunyomi: "けもの", meaning: "animal, beast" },
  { kanji: "縄", onyomi: "じょう", kunyomi: "なわ", meaning: "straw rope, cord" },
  { kanji: "汗", onyomi: "かん", kunyomi: "あせ", meaning: "sweat, perspire" },
  { kanji: "銅", onyomi: "どう", kunyomi: "", meaning: "copper" },
  { kanji: "湿", onyomi: "しつ", kunyomi: "しめ（る）", meaning: "damp, wet, moist" },
  { kanji: "瓶", onyomi: "びん", kunyomi: "", meaning: "bottle, vial, jar, jug, vat, urn" },
  { kanji: "咲", onyomi: "しょう", kunyomi: "さ（く）", meaning: "blossom, bloom" },
  { kanji: "召", onyomi: "しょう", kunyomi: "め（す）", meaning: "seduce, call, send for, wear, put on, ride in, buy, eat, drink, catch (cold)" },
  { kanji: "缶", onyomi: "かん", kunyomi: "", meaning: "can, container, jar radical (no. 121)" },
  { kanji: "隻", onyomi: "せき", kunyomi: "", meaning: "vessels, counter for ships, fish, birds, arrows, one of a pair" },
  { kanji: "脈", onyomi: "みゃく", kunyomi: "", meaning: "vein, pulse, hope" },
  { kanji: "滑", onyomi: "かつ、こつ", kunyomi: "すべ（る）、なめ（らか）", meaning: "slippery, slide, slip, flunk" },
  { kanji: "孝", onyomi: "こう", kunyomi: "", meaning: "filial piety, child's respect" },
  { kanji: "巣", onyomi: "そう", kunyomi: "す", meaning: "nest, rookery, hive, cobweb, den" },
  { kanji: "浅", onyomi: "せん", kunyomi: "あさ（い）", meaning: "shallow, superficial, frivolous, wretched, shameful" },
  { kanji: "漬", onyomi: "し", kunyomi: "つけ", meaning: "pickling, soak, moisten" },
  { kanji: "糖", onyomi: "とう", kunyomi: "", meaning: "sugar" },
  { kanji: "康", onyomi: "こう", kunyomi: "", meaning: "ease, peace" },
  { kanji: "舞", onyomi: "ぶ", kunyomi: "ま（う）", meaning: "dance, flit, circle, wheel" },
  { kanji: "掃", onyomi: "そう", kunyomi: "は（く）", meaning: "sweep, brush" },
  { kanji: "雄", onyomi: "ゆう", kunyomi: "お-、おす", meaning: "masculine, male, hero, leader, superiority, excellence" },
  { kanji: "雌", onyomi: "し", kunyomi: "めす、め-", meaning: "feminine, female" },
  { kanji: "寝", onyomi: "しん", kunyomi: "ね（る）", meaning: "lie down, sleep, rest, bed, remain unsold" },
  { kanji: "暖", onyomi: "だん", kunyomi: "あたた（か）", meaning: "warmth" },
  { kanji: "机", onyomi: "き", kunyomi: "つくえ", meaning: "desk, table" },
  { kanji: "秘", onyomi: "ひ", kunyomi: "", meaning: "secret, conceal" },
  { kanji: "軸", onyomi: "じく", kunyomi: "", meaning: "axis, pivot, stem, stalk, counter for picture scrolls" },
  { kanji: "腕", onyomi: "わん", kunyomi: "うで", meaning: "arm, ability, talent" },
  { kanji: "紙", onyomi: "し", kunyomi: "かみ", meaning: "paper" },
  { kanji: "展", onyomi: "てん", kunyomi: "", meaning: "unfold, expand" },
  { kanji: "繁", onyomi: "はん", kunyomi: "しげ（る）", meaning: "luxuriant, thick, overgrown, frequency, complexity, trouble" },
  { kanji: "範", onyomi: "はん", kunyomi: "", meaning: "pattern, example, model" },
  { kanji: "弾", onyomi: "だん", kunyomi: "はず（む）、たま", meaning: "bullet, twang, flip, snap" },
  { kanji: "圏", onyomi: "けん", kunyomi: "", meaning: "sphere, circle, radius, range" },
  { kanji: "揺", onyomi: "よう", kunyomi: "ゆ（れる）", meaning: "swing, shake, sway, rock, tremble, vibrate" },
  { kanji: "玉", onyomi: "ぎょく", kunyomi: "たま", meaning: "jewel, ball" },
  { kanji: "頻", onyomi: "ひん", kunyomi: "しき（り）", meaning: "repeatedly, recur" },
  { kanji: "狙", onyomi: "そ", kunyomi: "ねら（う）", meaning: "aim at, sight on, shadow, stalk" },
  { kanji: "床", onyomi: "しょう", kunyomi: "とこ、ゆか", meaning: "bed, counter for beds, floor, padding, tatami" },
  { kanji: "亀", onyomi: "き", kunyomi: "かめ", meaning: "tortoise, turtle" },
  { kanji: "束", onyomi: "そく", kunyomi: "たば", meaning: "bundle, sheaf, ream, tie in bundles, govern, manage, control" },
  { kanji: "毒", onyomi: "どく", kunyomi: "", meaning: "poison, virus, venom, germ, harm, injury, spite" },
  { kanji: "述", onyomi: "じゅつ", kunyomi: "の（べる）", meaning: "mention, state, speak, relate" },
  { kanji: "江", onyomi: "こう", kunyomi: "え", meaning: "creek, inlet, bay" },
  { kanji: "壁", onyomi: "へき", kunyomi: "かべ", meaning: "wall, lining (stomach), fence" },
  { kanji: "避", onyomi: "ひ", kunyomi: "さ（ける）", meaning: "evade, avoid, avert, ward off, shirk, shun" },
  { kanji: "房", onyomi: "ぼう", kunyomi: "ふさ", meaning: "tassel, tuft, fringe, bunch, lock (hair), segment (orange), house, room" },
  { kanji: "養", onyomi: "よう", kunyomi: "やしな（う）", meaning: "foster, bring up, rear, develop, nurture" },
  { kanji: "衛", onyomi: "えい", kunyomi: "", meaning: "defense, protection" },
  { kanji: "径", onyomi: "けい", kunyomi: "", meaning: "diameter, path, method" },
  { kanji: "貨", onyomi: "か", kunyomi: "", meaning: "freight, goods, property" },
  { kanji: "塚", onyomi: "ちょう", kunyomi: "つか", meaning: "hillock, mound" },
  { kanji: "幹", onyomi: "かん", kunyomi: "みき", meaning: "tree trunk" },
  { kanji: "湾", onyomi: "わん", kunyomi: "", meaning: "gulf, bay, inlet" },
  { kanji: "巻", onyomi: "かん", kunyomi: "ま（く）", meaning: "scroll, volume, book, part, roll up, wind up, tie, coil, counter for texts (or book scrolls)" },
  { kanji: "頂", onyomi: "ちょう", kunyomi: "いただき", meaning: "place on the head, receive, top of head, top, summit, peak" },
  { kanji: "箱", onyomi: "はこ", kunyomi: "", meaning: "box, chest, case, bin, railway car" },
  { kanji: "偉", onyomi: "い", kunyomi: "えら（い）", meaning: "admirable, greatness, remarkable, conceited, famous, excellent" },
  { kanji: "歴", onyomi: "れき", kunyomi: "", meaning: "curriculum, continuation, passage of time" },
  { kanji: "避", onyomi: "ひ", kunyomi: "さ（ける）", meaning: "evade, avoid, avert, ward off, shirk, shun" },
  { kanji: "穴", onyomi: "けつ", kunyomi: "あな", meaning: "hole, aperture, slit, cave, den" },
  { kanji: "忙", onyomi: "ぼう", kunyomi: "いそが（しい）", meaning: "busy, occupied, restless" },
  { kanji: "扱", onyomi: "あつ", kunyomi: "あつ（かう）", meaning: "handle, deal with, dispose of, treat, entertain, receive guests" },
  { kanji: "皿", onyomi: "さら", kunyomi: "", meaning: "dish, a helping, plate" },
  { kanji: "恩", onyomi: "おん", kunyomi: "", meaning: "grace, kindness, goodness, favor, mercy, blessing, benefit" },
  { kanji: "純", onyomi: "じゅん", kunyomi: "", meaning: "genuine, purity, innocence, net (profit)" },
  { kanji: "奪", onyomi: "だつ", kunyomi: "うば（う）", meaning: "rob, take by force, snatch away, dispossess, plunder, usurp" },
  { kanji: "既", onyomi: "き", kunyomi: "すで（に）", meaning: "previously, already, long ago" },
  { kanji: "刺", onyomi: "し", kunyomi: "さ（す）、とげ", meaning: "thorn, pierce, stab, prick, sting, calling card" },
  { kanji: "筋", onyomi: "きん", kunyomi: "すじ", meaning: "muscle, sinew, tendon, fiber, plot, plan, descent" },
  { kanji: "脳", onyomi: "のう", kunyomi: "", meaning: "brain, memory" },
  { kanji: "液", onyomi: "えき", kunyomi: "", meaning: "fluid, liquid, juice, sap, secretion" },
  { kanji: "冷", onyomi: "れい", kunyomi: "つめ（たい）、ひ（える）", meaning: "cool, cold (beer, person), chill" },
  { kanji: "駐", onyomi: "ちゅう", kunyomi: "", meaning: "stop-over, reside in, resident" },
  { kanji: "弱", onyomi: "じゃく", kunyomi: "よわ（い）", meaning: "weak, frail" },
  { kanji: "紹", onyomi: "しょう", kunyomi: "", meaning: "introduce, inherit, help" },
  { kanji: "雇", onyomi: "こ", kunyomi: "やと（う）", meaning: "employ, hire" },
  { kanji: "替", onyomi: "たい", kunyomi: "か（える）", meaning: "exchange, spare, substitute, per-" },
  { kanji: "預", onyomi: "よ", kunyomi: "あず（ける）", meaning: "deposit, custody, leave with, entrust to" },
  { kanji: "焼", onyomi: "しょう", kunyomi: "や（く）", meaning: "bake, burning" },
  { kanji: "簡", onyomi: "かん", kunyomi: "", meaning: "simplicity, brevity" },
  { kanji: "章", onyomi: "しょう", kunyomi: "", meaning: "badge, chapter, composition, poem, design" },
  { kanji: "臓", onyomi: "ぞう", kunyomi: "", meaning: "entrails, viscera, bowels" },
  { kanji: "律", onyomi: "りつ、りち", kunyomi: "", meaning: "rhythm, law, regulation, gauge, control" },
  { kanji: "贈", onyomi: "ぞう、そう", kunyomi: "おく（る）", meaning: "presents, send, give to, award to, confer on, presenting something" },
  { kanji: "照", onyomi: "しょう", kunyomi: "て（る）", meaning: "illuminate, shine, compare, bashful" },
  { kanji: "薄", onyomi: "はく", kunyomi: "うす（い）", meaning: "dilute, thin, weak (tea), pampas grass" },
  { kanji: "群", onyomi: "ぐん", kunyomi: "む（れ）、むら（がる）", meaning: "flock, group, crowd, herd, swarm, cluster" },
  { kanji: "秋", onyomi: "しゅう", kunyomi: "あき", meaning: "autumn" },
  { kanji: "趣", onyomi: "しゅ", kunyomi: "おもむき", meaning: "purport, gist, elegance, interest, proceed to, tend, become" },
  { kanji: "渡", onyomi: "と", kunyomi: "わた（る）", meaning: "transit, ford, ferry, cross, import, deliver, diameter, migrate" },
  { kanji: "惜", onyomi: "せき", kunyomi: "お（しい）", meaning: "pity, be sparing of, frugal, stingy, regret" },
  { kanji: "索", onyomi: "さく", kunyomi: "", meaning: "cord, rope, searching, inquiring" },
  { kanji: "誘", onyomi: "ゆう", kunyomi: "さそ（う）", meaning: "entice, lead, tempt, invite, ask, call for, seduce, allure" },
  { kanji: "勇", onyomi: "ゆう", kunyomi: "いさ（む）", meaning: "courage, cheer up, be in high spirits, bravery, heroism" },
  { kanji: "械", onyomi: "かい", kunyomi: "", meaning: "contraption, fetter, machine, instrument" },
  { kanji: "菓", onyomi: "か", kunyomi: "", meaning: "candy, cakes, fruit" },
  { kanji: "砂", onyomi: "さ、しゃ", kunyomi: "すな", meaning: "sand" },
  { kanji: "漏", onyomi: "ろう", kunyomi: "も（る）", meaning: "leak, escape, time" },
  { kanji: "災", onyomi: "さい", kunyomi: "わざわ（い）", meaning: "disaster, calamity, woe, curse, evil" },
  { kanji: "舟", onyomi: "しゅう", kunyomi: "ふね", meaning: "boat, ship" },
  { kanji: "礎", onyomi: "そ", kunyomi: "いしずえ", meaning: "cornerstone, foundation stone" },
  { kanji: "慰", onyomi: "い", kunyomi: "なぐさ（める）", meaning: "consolation, amusement, seduce, cheer, make sport of, comfort, console" },
  { kanji: "愉", onyomi: "ゆ", kunyomi: "たのし（い）", meaning: "pleasure, happy, rejoice" },
  { kanji: "掘", onyomi: "くつ", kunyomi: "ほ（る）", meaning: "dig, delve, excavate" },
  { kanji: "珍", onyomi: "ちん", kunyomi: "めずら（しい）", meaning: "rare, curious, strange" },
  { kanji: "敷", onyomi: "ふ", kunyomi: "し（く）", meaning: "spread, pave, sit, promulgate" },
  { kanji: "析", onyomi: "せき", kunyomi: "", meaning: "chop, divide, tear, analyze" },
  { kanji: "捜", onyomi: "そう", kunyomi: "さが（す）", meaning: "search, look for, locate" },
  { kanji: "荒", onyomi: "こう", kunyomi: "あら（い）、あ（れる）", meaning: "laid waste, rough, rude, wild" },
  { kanji: "咽", onyomi: "いん、えつ", kunyomi: "のど", meaning: "throat, choked, smothered, stuffy" }
];