export interface KanjiData {
  kanji: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
}

export const N3_KANJI: KanjiData[] = [
  { kanji: "政", onyomi: "sei", kunyomi: "matsurigoto", meaning: "politics, government" },
  { kanji: "議", onyomi: "gi", kunyomi: "", meaning: "deliberation, consultation, debate" },
  { kanji: "民", onyomi: "min", kunyomi: "tami", meaning: "people, nation, subjects" },
  { kanji: "連", onyomi: "ren", kunyomi: "tsura(naru), tsu(reru)", meaning: "take along, lead, join, connect" },
  { kanji: "対", onyomi: "tai, tsui", kunyomi: "", meaning: "opposite, even, equal, versus, anti-, compare" },
  { kanji: "部", onyomi: "bu", kunyomi: "", meaning: "section, bureau, dept, class, copy, part, portion" },
  { kanji: "合", onyomi: "gou, ga, ka", kunyomi: "a(u), ai", meaning: "fit, suit, join, 0.1" },
  { kanji: "市", onyomi: "shi", kunyomi: "ichi", meaning: "market, city, town" },
  { kanji: "内", onyomi: "nai", kunyomi: "uchi", meaning: "inside, within, between, among, house, home" },
  { kanji: "相", onyomi: "sou, shou", kunyomi: "ai", meaning: "inter-, mutual, together, minister of state" },
  { kanji: "定", onyomi: "tei, jou", kunyomi: "sada(meru)", meaning: "determine, fix, establish, decide" },
  { kanji: "回", onyomi: "kai", kunyomi: "mawa(su)", meaning: "-times, round, revolve, counter" },
  { kanji: "選", onyomi: "sen", kunyomi: "era(bu)", meaning: "elect, select, choose, prefer" },
  { kanji: "米", onyomi: "bei, mai", kunyomi: "kome", meaning: "rice, USA, meter" },
  { kanji: "実", onyomi: "jitsu", kunyomi: "mi, mino(ru), makoto", meaning: "reality, truth" },
  { kanji: "関", onyomi: "kan", kunyomi: "seki, kaka(waru)", meaning: "connection, gateway, involve, concerning" },
  { kanji: "決", onyomi: "ketsu", kunyomi: "ki(meru)", meaning: "decide, fix, agree upon, appoint" },
  { kanji: "全", onyomi: "zen", kunyomi: "matta(ku), sube(te)", meaning: "whole, entire, all, complete, fulfill" },
  { kanji: "表", onyomi: "hyou", kunyomi: "omote, arawa(su)", meaning: "surface, table, chart, diagram" },
  { kanji: "戦", onyomi: "sen", kunyomi: "ikusa, tataka(u)", meaning: "war, battle, match" },
  { kanji: "経", onyomi: "kei", kunyomi: "he(ru), ta(tsu)", meaning: "longitude, pass thru, expire, warp" },
  { kanji: "最", onyomi: "sai", kunyomi: "motto(mo)", meaning: "utmost, most, extreme" },
  { kanji: "現", onyomi: "gen", kunyomi: "arawa(reru), utsu(tsu)", meaning: "present, existing, actual" },
  { kanji: "調", onyomi: "chou", kunyomi: "shira(beru), tono(u)", meaning: "tune, tone, meter, prepare, investigate" },
  { kanji: "化", onyomi: "ka, ke", kunyomi: "ba(keru), fu(keru)", meaning: "change, take the form of, influence, -ization" },
  { kanji: "当", onyomi: "tou", kunyomi: "a(taru)", meaning: "hit, right, appropriate" },
  { kanji: "約", onyomi: "yaku", kunyomi: "tsuzu(maru)", meaning: "promise, approximately, shrink" },
  { kanji: "首", onyomi: "shu", kunyomi: "kubi", meaning: "neck" },
  { kanji: "法", onyomi: "hou", kunyomi: "nori", meaning: "method, law, rule, principle, model, system" },
  { kanji: "性", onyomi: "sei, shou", kunyomi: "", meaning: "sex, gender, nature" },
  { kanji: "的", onyomi: "teki", kunyomi: "", meaning: "mark, target, object, adjective ending" },
  { kanji: "要", onyomi: "you", kunyomi: "i(ru), kaname", meaning: "need, main point, essence, pivot" },
  { kanji: "制", onyomi: "sei", kunyomi: "", meaning: "system, law, rule" },
  { kanji: "治", onyomi: "ji, chi", kunyomi: "osa(meru), nao(ru)", meaning: "reign, cure, heal" },
  { kanji: "務", onyomi: "mu", kunyomi: "tsuto(meru)", meaning: "task, duties" },
  { kanji: "成", onyomi: "sei, jou", kunyomi: "na(ru)", meaning: "turn into, become, get, grow, elapse" },
  { kanji: "期", onyomi: "ki, go", kunyomi: "", meaning: "period, time, date, term" },
  { kanji: "取", onyomi: "shu", kunyomi: "to(ru)", meaning: "take, fetch" },
  { kanji: "都", onyomi: "to, tsu", kunyomi: "miyako", meaning: "metropolis, capital" },
  { kanji: "和", onyomi: "wa, o", kunyomi: "yawa(ragu), nago(mu)", meaning: "harmony, Japanese style, peace" },
  { kanji: "機", onyomi: "ki", kunyomi: "", meaning: "machine, airplane, opportunity" },
  { kanji: "平", onyomi: "hei, byou", kunyomi: "tai(ra), hira", meaning: "even, flat, peace" },
  { kanji: "加", onyomi: "ka", kunyomi: "kwa(eru)", meaning: "add, addition, increase, join" },
  { kanji: "受", onyomi: "ju", kunyomi: "u(keru)", meaning: "accept, undergo, answer (phone), take" },
  { kanji: "続", onyomi: "zoku", kunyomi: "tsuzuku", meaning: "continue, series, sequel" },
  { kanji: "進", onyomi: "shin", kunyomi: "susu(mu)", meaning: "advance, proceed" },
  { kanji: "数", onyomi: "suu", kunyomi: "kazu, kazo(eru)", meaning: "number, strength, fate, law, figures" },
  { kanji: "記", onyomi: "ki", kunyomi: "shiru(su)", meaning: "scribe, account, narrative" },
  { kanji: "初", onyomi: "sho", kunyomi: "haji(me), hatsu", meaning: "first time, beginning" },
  { kanji: "指", onyomi: "shi", kunyomi: "yubi, sa(su)", meaning: "finger, point to, indicate" },
  { kanji: "権", onyomi: "ken", kunyomi: "", meaning: "authority, power, rights" },
  { kanji: "支", onyomi: "shi", kunyomi: "sasa(eru)", meaning: "branch, support, sustain" },
  { kanji: "産", onyomi: "san", kunyomi: "u(mu), mu(su)", meaning: "products, bear, give birth" },
  { kanji: "点", onyomi: "ten", kunyomi: "tsu(keru)", meaning: "spot, point, mark" },
  { kanji: "報", onyomi: "hou", kunyomi: "mukku(iru)", meaning: "report, news, reward" },
  { kanji: "済", onyomi: "sai, sei", kunyomi: "su(mu)", meaning: "settle, relieve, finish" },
  { kanji: "活", onyomi: "katsu", kunyomi: "i(kiru)", meaning: "living" },
  { kanji: "原", onyomi: "gen", kunyomi: "hara", meaning: "original, primitive, field" },
  { kanji: "共", onyomi: "kyou", kunyomi: "tomo", meaning: "together, both, neither" },
  { kanji: "得", onyomi: "toku", kunyomi: "e(ru)", meaning: "gain, get, find, earn, acquire, able to, profit" },
  { kanji: "解", onyomi: "kai, ge", kunyomi: "to(ku), hodo(ku)", meaning: "unravel, explanation" },
  { kanji: "交", onyomi: "kou", kunyomi: "maji.waru, ma.zeru, ka.wasu", meaning: "mingle, mixing, association" },
  { kanji: "資", onyomi: "shi", kunyomi: "", meaning: "assets, resources, capital, funds, data" },
  { kanji: "予", onyomi: "yo, sha", kunyomi: "arakaji(me)", meaning: "beforehand, previous, myself, I" },
  { kanji: "向", onyomi: "kou", kunyomi: "mu(ku), muka(i)", meaning: "facing, beyond" },
  { kanji: "際", onyomi: "sai", kunyomi: "kiwa", meaning: "occasion, time" },
  { kanji: "勝", onyomi: "shou", kunyomi: "ka(tsu), masa(ru)", meaning: "victory, win" },
  { kanji: "面", onyomi: "men", kunyomi: "omo, omote, tsura", meaning: "mask, face, features, surface" },
  { kanji: "告", onyomi: "koku", kunyomi: "tsu(geru)", meaning: "revelation, inform" },
  { kanji: "反", onyomi: "han, hon, tan, ho", kunyomi: "so(ru), kae(su)", meaning: "anti-" },
  { kanji: "判", onyomi: "han", kunyomi: "", meaning: "judgement, signature" },
  { kanji: "認", onyomi: "nin", kunyomi: "mito(meru), shitata(meru)", meaning: "acknowledge, witness, recognize" },
  { kanji: "参", onyomi: "san", kunyomi: "mai(ru)", meaning: "going, coming, participate" },
  { kanji: "利", onyomi: "ri", kunyomi: "ki(ku)", meaning: "profit, advantage, benefit" },
  { kanji: "組", onyomi: "so", kunyomi: "ku(mu), kumi", meaning: "association, assemble, unite" },
  { kanji: "信", onyomi: "shin", kunyomi: "", meaning: "faith, truth, trust" },
  { kanji: "在", onyomi: "zai", kunyomi: "a(ru)", meaning: "exist, outskirts" },
  { kanji: "件", onyomi: "ken", kunyomi: "kudan", meaning: "affair, case, matter" },
  { kanji: "側", onyomi: "soku", kunyomi: "gawa, soba", meaning: "side, lean, oppose" },
  { kanji: "任", onyomi: "nin", kunyomi: "maka(seru)", meaning: "responsibility, duty" },
  { kanji: "引", onyomi: "in", kunyomi: "hi(ku)", meaning: "pull, tug, jerk" },
  { kanji: "求", onyomi: "kyuu", kunyomi: "moto(meru)", meaning: "request, want, demand" },
  { kanji: "所", onyomi: "sho", kunyomi: "tokoro", meaning: "place, extent" },
  { kanji: "次", onyomi: "ji, shi", kunyomi: "tsu(gu), tsugi", meaning: "next, order" },
  { kanji: "昨", onyomi: "saku", kunyomi: "", meaning: "yesterday, previous" },
  { kanji: "論", onyomi: "ron", kunyomi: "agetsura(u)", meaning: "argument, discourse" },
  { kanji: "官", onyomi: "kan", kunyomi: "", meaning: "bureaucrat, the government, organ" },
  { kanji: "増", onyomi: "zou", kunyomi: "ma(su), fu(eru)", meaning: "increase, add" },
  { kanji: "係", onyomi: "kei", kunyomi: "kaka(ru), kakari", meaning: "person in charge, connection" },
  { kanji: "感", onyomi: "kan", kunyomi: "", meaning: "emotion, feeling, sensation" },
  { kanji: "情", onyomi: "jou, sei", kunyomi: "nasa(ke)", meaning: "feelings, emotion, passion" },
  { kanji: "投", onyomi: "tou", kunyomi: "na(geru)", meaning: "throw, discard" },
  { kanji: "示", onyomi: "ji, shi", kunyomi: "shime(su)", meaning: "show, indicate, display" },
  { kanji: "変", onyomi: "hen", kunyomi: "ka(waru)", meaning: "unusual, change, strange" },
  { kanji: "打", onyomi: "da", kunyomi: "u(tsu), bu(tsu)", meaning: "strike, hit, knock" },
  { kanji: "直", onyomi: "choku, jiki", kunyomi: "tada(chini), su(gu)", meaning: "straightaway, honesty, frankness, fix, repair" },
  { kanji: "両", onyomi: "ryou", kunyomi: "futatsu", meaning: "both" },
  { kanji: "式", onyomi: "shiki", kunyomi: "", meaning: "style, ceremony" },
  { kanji: "確", onyomi: "kaku", kunyomi: "tashi(ka)", meaning: "assurance, firm, confirm" },
  { kanji: "果", onyomi: "ka", kunyomi: "ha(tasu)", meaning: "fruit, reward, carry out, achieve, complete" },
  { kanji: "容", onyomi: "you", kunyomi: "i(reru)", meaning: "contain, form" },
  { kanji: "必", onyomi: "hitsu", kunyomi: "kanara(zu)", meaning: "invariably, certain, inevitable" },
  { kanji: "演", onyomi: "en", kunyomi: "", meaning: "performance, act, play, render, stage" },
  { kanji: "歳", onyomi: "sai, sei", kunyomi: "toshi", meaning: "age, year-end" },
  { kanji: "争", onyomi: "sou", kunyomi: "araso(u)", meaning: "contend, dispute, argue" },
  { kanji: "談", onyomi: "dan", kunyomi: "", meaning: "discuss, talk" },
  { kanji: "能", onyomi: "nou", kunyomi: "", meaning: "ability, talent, skill, capacity" },
  { kanji: "位", onyomi: "i", kunyomi: "kurai, gurai", meaning: "rank, grade, about" },
  { kanji: "置", onyomi: "chi", kunyomi: "o(ku)", meaning: "placement, put, set, deposit, leave behind" },
  { kanji: "流", onyomi: "ryuu, ru", kunyomi: "naga(reru)", meaning: "current, flow" },
  { kanji: "格", onyomi: "kaku, kou, kyaku", kunyomi: "", meaning: "status, rank, capacity" },
  { kanji: "疑", onyomi: "gi", kunyomi: "utaga(u)", meaning: "doubt, distrust" },
  { kanji: "過", onyomi: "ka", kunyomi: "su(giru), yogi(ru)", meaning: "overdo, exceed, go beyond" },
  { kanji: "局", onyomi: "kyoku", kunyomi: "", meaning: "bureau, board, office" },
  { kanji: "放", onyomi: "hou", kunyomi: "hana(su), hou(ru)", meaning: "set free, release" },
  { kanji: "常", onyomi: "jou", kunyomi: "tsune", meaning: "usual, ordinary, normal" },
  { kanji: "状", onyomi: "jou", kunyomi: "", meaning: "conditions, form, appearance" },
  { kanji: "球", onyomi: "kyuu", kunyomi: "tama", meaning: "ball, sphere" },
  { kanji: "職", onyomi: "shoku", kunyomi: "", meaning: "post, employment, work" },
  { kanji: "与", onyomi: "yo", kunyomi: "ata(eru), azuka(ru)", meaning: "give, award" },
  { kanji: "供", onyomi: "kyou, ku, kuu", kunyomi: "sona(eru), tomo", meaning: "submit, offer, present, accompany" },
  { kanji: "役", onyomi: "yaku, eki", kunyomi: "", meaning: "duty, service, role" },
  { kanji: "構", onyomi: "kou", kunyomi: "kama(u)", meaning: "posture, build, pretend" },
  { kanji: "割", onyomi: "katsu", kunyomi: "wa(ru), wari", meaning: "proportion, divide, cut, separate" },
  { kanji: "身", onyomi: "shin", kunyomi: "mi", meaning: "somebody, person" },
  { kanji: "費", onyomi: "hi", kunyomi: "tsui(yasu)", meaning: "expense, consume" },
  { kanji: "付", onyomi: "fu", kunyomi: "tsu(keru)", meaning: "adhere, attach, refer to" },
  { kanji: "由", onyomi: "yu, yuu", kunyomi: "yoshi, yo(ru)", meaning: "wherefore, a reason" },
  { kanji: "説", onyomi: "setsu, zei", kunyomi: "to(ku)", meaning: "opinion, theory, explanation" },
  { kanji: "難", onyomi: "nan", kunyomi: "kata(i), muzuka(shii), niku(i)", meaning: "difficult, trouble, accident" },
  { kanji: "優", onyomi: "yuu, u", kunyomi: "yasa(shii), sugu(reru)", meaning: "tenderness, kind, actor" },
  { kanji: "夫", onyomi: "fu", kunyomi: "otto", meaning: "husband, man" },
  { kanji: "収", onyomi: "shuu", kunyomi: "osa(meru)", meaning: "income, obtain, reap, pay, supply, store" },
  { kanji: "断", onyomi: "dan", kunyomi: "ta(tsu), kotowa(ru)", meaning: "severance, decline, refuse, apologize" },
  { kanji: "石", onyomi: "seki, shaku, koku", kunyomi: "ishi", meaning: "stone" },
  { kanji: "違", onyomi: "i", kunyomi: "chiga(u), taga(u)", meaning: "difference, differ" },
  { kanji: "消", onyomi: "shou", kunyomi: "ki(eru), ke(su)", meaning: "extinguish, turn off" },
  { kanji: "神", onyomi: "shin, jin", kunyomi: "kami", meaning: "gods, mind, soul" },
  { kanji: "番", onyomi: "ban", kunyomi: "tsugai", meaning: "turn, number in a series" },
  { kanji: "規", onyomi: "ki", kunyomi: "", meaning: "standard, measure" },
  { kanji: "術", onyomi: "jutsu", kunyomi: "sube", meaning: "art, technique, skill, means, trick" },
  { kanji: "備", onyomi: "bi", kunyomi: "sona(eru)", meaning: "equip, provision, preparation" },
  { kanji: "宅", onyomi: "taku", kunyomi: "", meaning: "home, house, residence" },
  { kanji: "害", onyomi: "gai", kunyomi: "", meaning: "harm, injury" },
  { kanji: "配", onyomi: "hai", kunyomi: "kuba(ru)", meaning: "distribute, spouse" },
  { kanji: "警", onyomi: "kei", kunyomi: "", meaning: "admonish, commandment" },
  { kanji: "育", onyomi: "iku", kunyomi: "soda(tsu), haguku(mu)", meaning: "bring up, grow up, raise" },
  { kanji: "席", onyomi: "seki", kunyomi: "mushiro", meaning: "seat" },
  { kanji: "訪", onyomi: "hou", kunyomi: "toozu(reru), tazu(neru)", meaning: "call on, visit" },
  { kanji: "乗", onyomi: "jou, shou", kunyomi: "no(ru)", meaning: "ride" },
  { kanji: "残", onyomi: "zan", kunyomi: "noko(ru)", meaning: "remainder, balance" },
  { kanji: "想", onyomi: "sou, so", kunyomi: "omo(u)", meaning: "concept, think, idea" },
  { kanji: "声", onyomi: "sei, shou", kunyomi: "koe", meaning: "voice" },
  { kanji: "助", onyomi: "jo", kunyomi: "tasu(keru)", meaning: "help, rescue, assist" },
  { kanji: "労", onyomi: "rou", kunyomi: "itawa(ru), negira(u)", meaning: "labor, thank for" },
  { kanji: "例", onyomi: "rei", kunyomi: "tato(eba)", meaning: "example" },
  { kanji: "然", onyomi: "zen, nen", kunyomi: "shika, sa", meaning: "sort of thing, if so" },
  { kanji: "限", onyomi: "gen", kunyomi: "kagi(ru)", meaning: "limit, restrict" },
  { kanji: "追", onyomi: "tsui", kunyomi: "o(u)", meaning: "chase, drive away" },
  { kanji: "商", onyomi: "shou", kunyomi: "akina(u)", meaning: "deal; selling; merchant" },
  { kanji: "葉", onyomi: "kou", kunyomi: "ha", meaning: "leaf, plane, needle, blade, counter for flat things" },
  { kanji: "伝", onyomi: "den", kunyomi: "tsuta(waru)", meaning: "transmit, follow, report, legend, tradition" },
  { kanji: "働", onyomi: "dou", kunyomi: "hatara(ku)", meaning: "work" },
  { kanji: "形", onyomi: "kei, gyou", kunyomi: "kata, katachi, nari", meaning: "shape, form, style" },
  { kanji: "景", onyomi: "kei", kunyomi: "", meaning: "scenery, view" },
  { kanji: "落", onyomi: "raku", kunyomi: "o(chiru)", meaning: "fall, drop" },
  { kanji: "好", onyomi: "kou", kunyomi: "kono(mu), su(ku)", meaning: "fond, pleasing, like something" },
  { kanji: "退", onyomi: "tai", kunyomi: "shirizo(ku), hi(ku), no(keru), do(ku)", meaning: "retreat, withdraw, retire, resign, repel, expel, reject" },
  { kanji: "頭", onyomi: "tou, zu, to", kunyomi: "atama, kashira", meaning: "head" },
  { kanji: "負", onyomi: "fu", kunyomi: "ma(keru), o(u)", meaning: "defeat, negative, minus, assume a responsibility" },
  { kanji: "渡", onyomi: "to", kunyomi: "wata(ru)", meaning: "transit, ferry, cross" },
  { kanji: "失", onyomi: "shitsu", kunyomi: "ushina(u), u(seru)", meaning: "lose, error, fault, disadvantage, loss" },
  { kanji: "差", onyomi: "sa", kunyomi: "sa(su)", meaning: "distinction, difference, variation" },
  { kanji: "末", onyomi: "matsu", kunyomi: "sue", meaning: "end, close, tip" },
  { kanji: "守", onyomi: "shu, su", kunyomi: "mamo(ru), mori", meaning: "guard, protect, obey" },
  { kanji: "若", onyomi: "jaku", kunyomi: "waka(i), mo(shi)", meaning: "young" },
  { kanji: "種", onyomi: "shu", kunyomi: "tane, -gusa", meaning: "species, kind, class, seed" },
  { kanji: "美", onyomi: "bi, mi", kunyomi: "utsukushii", meaning: "beauty, beautiful" },
  { kanji: "命", onyomi: "mei, myou", kunyomi: "inochi", meaning: "fate, command" },
  { kanji: "福", onyomi: "fuku", kunyomi: "", meaning: "blessing, fortune, luck, wealth" },
  { kanji: "望", onyomi: "bou", kunyomi: "nozo(mu), mochi", meaning: "ambition, full moon, hope, desire, aspire to, expect" },
  { kanji: "非", onyomi: "hi", kunyomi: "ara(zu)", meaning: "un-, mistake, negative" },
  { kanji: "観", onyomi: "kan", kunyomi: "mi(ru)", meaning: "outlook, appearance, condition" },
  { kanji: "察", onyomi: "satsu", kunyomi: "", meaning: "guess, presume, judge" },
  { kanji: "段", onyomi: "dan", kunyomi: "", meaning: "grade, steps, stairs" },
  { kanji: "横", onyomi: "ou", kunyomi: "yoko", meaning: "sideways, side" },
  { kanji: "深", onyomi: "shin", kunyomi: "fuka(i)", meaning: "deep, heighten" },
  { kanji: "申", onyomi: "shin", kunyomi: "mou(su), saru", meaning: "have the honor to" },
  { kanji: "様", onyomi: "you", kunyomi: "sama, san", meaning: "manner, situation, polite suffix" },
  { kanji: "財", onyomi: "zai, sai, zoku", kunyomi: "", meaning: "property, money, wealth, assets" },
  { kanji: "港", onyomi: "kou", kunyomi: "minato", meaning: "harbor, port" },
  { kanji: "識", onyomi: "shiki", kunyomi: "shi(ru)", meaning: "know" },
  { kanji: "呼", onyomi: "ko", kunyomi: "yo(bu)", meaning: "call, invite" },
  { kanji: "達", onyomi: "tatsu, da", kunyomi: "-tachi", meaning: "accomplished, reach, arrive, attain" },
  { kanji: "良", onyomi: "ryou", kunyomi: "yo(i), i(i)", meaning: "good" },
  { kanji: "阪", onyomi: "han", kunyomi: "saka", meaning: "heights, slope" },
  { kanji: "候", onyomi: "kou", kunyomi: "", meaning: "climate, season, weather" },
  { kanji: "程", onyomi: "tei", kunyomi: "hodo", meaning: "extent, degree" },
  { kanji: "満", onyomi: "man", kunyomi: "mi(chiru)", meaning: "full, fullness, enough, satisfy" },
  { kanji: "敗", onyomi: "hai", kunyomi: "yabu(reru)", meaning: "failure, defeat" },
  { kanji: "値", onyomi: "chi", kunyomi: "ne, atai", meaning: "price, cost, value" },
  { kanji: "突", onyomi: "totsu, ka", kunyomi: "tsu(ku)", meaning: "stab, protruding, thrust" },
  { kanji: "光", onyomi: "kou", kunyomi: "hika(ru), hikari", meaning: "ray, light" },
  { kanji: "路", onyomi: "ro, ru", kunyomi: "michi", meaning: "path, route, road" },
  { kanji: "科", onyomi: "ka", kunyomi: "", meaning: "department, course, section" },
  { kanji: "積", onyomi: "seki", kunyomi: "tsu(mu)", meaning: "volume, contents, pile up, stack" },
  { kanji: "他", onyomi: "ta", kunyomi: "hoka", meaning: "other, another" },
  { kanji: "処", onyomi: "sho", kunyomi: "", meaning: "dispose, manage, deal with" },
  { kanji: "太", onyomi: "tai, ta", kunyomi: "futo(i)", meaning: "plump, thick, big around" },
  { kanji: "客", onyomi: "kyaku, kaku", kunyomi: "", meaning: "guest, visitor, customer" },
  { kanji: "否", onyomi: "hi", kunyomi: "ina, iya", meaning: "negate, no, decline" },
  { kanji: "師", onyomi: "shi", kunyomi: "ikusa", meaning: "expert, teacher, master" },
  { kanji: "登", onyomi: "tou, to", kunyomi: "nobo(ru), a(garu)", meaning: "ascend, climb up" },
  { kanji: "易", onyomi: "eki, i", kunyomi: "yasa(shii), yasu(i)", meaning: "easy, ready to, simple" },
  { kanji: "速", onyomi: "soku", kunyomi: "haya(i)", meaning: "quick, fast" },
  { kanji: "存", onyomi: "son, zon", kunyomi: "", meaning: "exist, be aware of" },
  { kanji: "飛", onyomi: "hi", kunyomi: "to(bu)", meaning: "fly" },
  { kanji: "殺", onyomi: "satsu, sai", kunyomi: "koro(su)", meaning: "kill, murder" },
  { kanji: "号", onyomi: "gou", kunyomi: "", meaning: "number, item" },
  { kanji: "単", onyomi: "tan", kunyomi: "hitoe", meaning: "simple, single" },
  { kanji: "座", onyomi: "za", kunyomi: "suwa(ru)", meaning: "squat, seat, sit" },
  { kanji: "破", onyomi: "ha", kunyomi: "yabu(ru)", meaning: "rip, tear, break" },
  { kanji: "除", onyomi: "jo, ji", kunyomi: "nozo(ku)", meaning: "exclude, remove" },
  { kanji: "完", onyomi: "kan", kunyomi: "", meaning: "perfect, completion" },
  { kanji: "降", onyomi: "kou, go", kunyomi: "o(riru), fu(ru)", meaning: "descend, precipitate, fall, surrender" },
  { kanji: "責", onyomi: "seki", kunyomi: "se(meru)", meaning: "blame, condemn" },
  { kanji: "捕", onyomi: "ho", kunyomi: "to(raeru), tsuka(maeru)", meaning: "catch, capture" },
  { kanji: "危", onyomi: "ki", kunyomi: "abu(nai), aya(ui)", meaning: "dangerous, fear, uneasy" },
  { kanji: "給", onyomi: "kyuu", kunyomi: "tama(u), tamo(u)", meaning: "salary, wage, gift" },
  { kanji: "苦", onyomi: "ku", kunyomi: "kuru(shii), niga(i)", meaning: "suffering, bitter" },
  { kanji: "迎", onyomi: "gei", kunyomi: "muka(eru)", meaning: "welcome, meet, greet" },
  { kanji: "園", onyomi: "en", kunyomi: "sono", meaning: "park, garden, yard" },
  { kanji: "具", onyomi: "gu", kunyomi: "sona(eru), tsubasa(ni)", meaning: "tool, utensil" },
  { kanji: "辞", onyomi: "ji", kunyomi: "ya(meru)", meaning: "resign, word, term" },
  { kanji: "因", onyomi: "in", kunyomi: "yo(ru), china(mu)", meaning: "cause, factor, depend on" },
  { kanji: "馬", onyomi: "ba", kunyomi: "uma", meaning: "horse" },
  { kanji: "愛", onyomi: "ai", kunyomi: "ito(shii), mana", meaning: "love, affection" },
  { kanji: "富", onyomi: "fu, fuu", kunyomi: "to(mu), tomi", meaning: "wealth, enrich, abundant" },
  { kanji: "彼", onyomi: "hi", kunyomi: "kare, kano", meaning: "he, him" },
  { kanji: "未", onyomi: "mi, bi", kunyomi: "ima(da), ma(da)", meaning: "un-, not yet" },
  { kanji: "舞", onyomi: "bu", kunyomi: "ma(u), mai", meaning: "dance, circle" },
  { kanji: "亡", onyomi: "bou, mou", kunyomi: "na(kunaru)", meaning: "deceased, dying" },
  { kanji: "冷", onyomi: "rei", kunyomi: "tsume(tai), hi(eru), sa(meru)", meaning: "cool, cold, chill" },
  { kanji: "適", onyomi: "teki", kunyomi: "kana(u)", meaning: "suitable, occasional, rare" },
  { kanji: "婦", onyomi: "fu", kunyomi: "yome", meaning: "lady, woman, wife" },
  { kanji: "寄", onyomi: "ki", kunyomi: "yo(ru)", meaning: "draw near, gather" },
  { kanji: "込", onyomi: "", kunyomi: "ko(mu)", meaning: "crowded, mixture" },
  { kanji: "顔", onyomi: "gan", kunyomi: "kao", meaning: "face, expression" },
  { kanji: "類", onyomi: "rui", kunyomi: "tagu(i)", meaning: "sort, kind, variety, class, genus" },
  { kanji: "余", onyomi: "yo", kunyomi: "ama(ru)", meaning: "too much, surplus" },
  { kanji: "王", onyomi: "ou", kunyomi: "", meaning: "king, rule" },
  { kanji: "返", onyomi: "hen", kunyomi: "kae(su)", meaning: "return, answer" },
  { kanji: "妻", onyomi: "sai", kunyomi: "tsuma", meaning: "wife, spouse" },
  { kanji: "背", onyomi: "hai", kunyomi: "se, sei", meaning: "stature, height, back" },
  { kanji: "熱", onyomi: "netsu", kunyomi: "atsu(i)", meaning: "heat, fever, passion" },
  { kanji: "宿", onyomi: "shuku", kunyomi: "yado", meaning: "inn, lodging" },
  { kanji: "薬", onyomi: "yaku", kunyomi: "kusuri", meaning: "medicine, chemical" },
  { kanji: "険", onyomi: "ken", kunyomi: "kewa(shii)", meaning: "precipitous, inaccessible place" },
  { kanji: "頼", onyomi: "rai", kunyomi: "tano(mu), tayo(ru)", meaning: "trust, request" },
  { kanji: "覚", onyomi: "kaku", kunyomi: "obo(eru), sa(masu)", meaning: "memorize, learn, remember, awake" },
  { kanji: "船", onyomi: "sen", kunyomi: "fune, funa", meaning: "ship, boat" },
  { kanji: "途", onyomi: "to", kunyomi: "michi", meaning: "route, way, road" },
  { kanji: "許", onyomi: "kyo", kunyomi: "yuru(su)", meaning: "permit, approve" },
  { kanji: "抜", onyomi: "batsu", kunyomi: "nu(ku)", meaning: "slip out, extract, pull out, remove" },
  { kanji: "便", onyomi: "ben, bin", kunyomi: "tayo(ri)", meaning: "convenience, facility" },
  { kanji: "留", onyomi: "ryuu, ru", kunyomi: "to(maru), todo(meru)", meaning: "detain, fasten, halt, stop" },
  { kanji: "罪", onyomi: "zai", kunyomi: "tsumi", meaning: "guilt, sin, crime" },
  { kanji: "努", onyomi: "do", kunyomi: "tsuto(meru)", meaning: "toil, diligent, as much as possible" },
  { kanji: "精", onyomi: "sei, shou", kunyomi: "shira(geru)", meaning: "refined, ghost, fairy, energy" },
  { kanji: "散", onyomi: "san", kunyomi: "chi(ru), bara(keru)", meaning: "scatter, disperse" },
  { kanji: "静", onyomi: "sei, jou", kunyomi: "shizu(ka)", meaning: "quiet" },
  { kanji: "婚", onyomi: "kon", kunyomi: "", meaning: "marriage" },
  { kanji: "喜", onyomi: "ki", kunyomi: "yoroko(bu)", meaning: "rejoice, take pleasure in" },
  { kanji: "浮", onyomi: "fu", kunyomi: "u(kabu)", meaning: "float, rise to surface" },
  { kanji: "絶", onyomi: "zetsu", kunyomi: "ta(eru)", meaning: "discontinue, unparalleled" },
  { kanji: "幸", onyomi: "kou", kunyomi: "saiwa(i), sara, shiawa(se)", meaning: "happiness, blessing, fortune" },
  { kanji: "押", onyomi: "ou", kunyomi: "o(su)", meaning: "push" },
  { kanji: "倒", onyomi: "tou", kunyomi: "tao(reru)", meaning: "overthrow, fall, collapse" },
  { kanji: "等", onyomi: "tou", kunyomi: "hito(shii), nado", meaning: "etc., and so forth" },
  { kanji: "老", onyomi: "rou", kunyomi: "o(iru), fu(keru)", meaning: "old" },
  { kanji: "曲", onyomi: "kyoku", kunyomi: "ma(garu)", meaning: "bend, music, melody" },
  { kanji: "払", onyomi: "", kunyomi: "hara(u)", meaning: "pay" },
  { kanji: "庭", onyomi: "tei", kunyomi: "niwa", meaning: "courtyard, garden, yard" },
  { kanji: "徒", onyomi: "to", kunyomi: "", meaning: "on foot, junior" },
  { kanji: "勤", onyomi: "kin, gon", kunyomi: "tsuto(meru)", meaning: "diligence, employed, serve" },
  { kanji: "遅", onyomi: "chi", kunyomi: "oku(reru), oso(i)", meaning: "slow, late, back, later" },
  { kanji: "居", onyomi: "kyo, ko", kunyomi: "i(ru), o(ru)", meaning: "reside, to be, exist" },
  { kanji: "雑", onyomi: "zatsu, zou", kunyomi: "maji(ru)", meaning: "miscellaneous" },
  { kanji: "招", onyomi: "shou", kunyomi: "mane(ku)", meaning: "invite, summon, engage" },
  { kanji: "困", onyomi: "kon", kunyomi: "koma(ru)", meaning: "quandary, become distressed" },
  { kanji: "欠", onyomi: "ketsu, ken", kunyomi: "ka(keru)", meaning: "lack, gap" },
  { kanji: "更", onyomi: "kou", kunyomi: "sara(ni), fu(keru)", meaning: "renew, renovate, again" },
  { kanji: "刻", onyomi: "koku", kunyomi: "kiza(mu)", meaning: "engrave, cut fine, chop" },
  { kanji: "賛", onyomi: "san", kunyomi: "", meaning: "approve, praise" },
  { kanji: "抱", onyomi: "hou", kunyomi: "da(ku), ida(ku), kaka(eru)", meaning: "embrace, hug" },
  { kanji: "犯", onyomi: "han", kunyomi: "oka(su)", meaning: "crime, sin, offense" },
  { kanji: "恐", onyomi: "kyou", kunyomi: "oso(reru), kowa(i)", meaning: "fear, dread" },
  { kanji: "息", onyomi: "musu, soku", kunyomi: "iki", meaning: "breath, son, interest (on money)" },
  { kanji: "遠", onyomi: "en, on", kunyomi: "too(i)", meaning: "distant, far" },
  { kanji: "戻", onyomi: "rei", kunyomi: "modo(ru)", meaning: "re-, return, revert" },
  { kanji: "願", onyomi: "gan", kunyomi: "nega(u)", meaning: "petition, request, wish" },
  { kanji: "絵", onyomi: "kai, e", kunyomi: "", meaning: "picture, drawing" },
  { kanji: "越", onyomi: "etsu", kunyomi: "ko(su)", meaning: "surpass, cross over, move to, exceed" },
  { kanji: "欲", onyomi: "yoku", kunyomi: "ho(shii)", meaning: "longing, greed, passion" },
  { kanji: "痛", onyomi: "tsuu", kunyomi: "ita(i)", meaning: "pain, hurt, damage, bruise" },
  { kanji: "笑", onyomi: "shou", kunyomi: "wara(u), e(mu)", meaning: "laugh" },
  { kanji: "互", onyomi: "go", kunyomi: "taga(i), katami(ni)", meaning: "mutually, reciprocally, together" },
  { kanji: "束", onyomi: "soku", kunyomi: "taba, tsuka", meaning: "bundle, manage" },
  { kanji: "似", onyomi: "ji, ne", kunyomi: "ni(ru)", meaning: "becoming, resemble, imitate" },
  { kanji: "列", onyomi: "retsu, re", kunyomi: "", meaning: "file, row, column" },
  { kanji: "探", onyomi: "tan", kunyomi: "sagu(ru), saga(su)", meaning: "search, look for" },
  { kanji: "逃", onyomi: "tou", kunyomi: "ni(geru), noga(su)", meaning: "escape, flee" },
  { kanji: "遊", onyomi: "yuu", kunyomi: "aso(bu)", meaning: "play" },
  { kanji: "迷", onyomi: "mei", kunyomi: "mayo(u)", meaning: "astray, be perplexed, in doubt, lost" },
  { kanji: "夢", onyomi: "mu", kunyomi: "yume", meaning: "dream, vision" },
  { kanji: "君", onyomi: "kun", kunyomi: "kimi", meaning: "you, male name suffix" },
  { kanji: "閉", onyomi: "hei", kunyomi: "to(jiru), shi(meru)", meaning: "closed, shut" },
  { kanji: "緒", onyomi: "sho", kunyomi: "o", meaning: "beginning, end, cord, strap" },
  { kanji: "折", onyomi: "setsu, shaku", kunyomi: "o(ru), ori", meaning: "fold, break, fracture" },
  { kanji: "草", onyomi: "sou", kunyomi: "kusa", meaning: "grass, weeds, herbs" },
  { kanji: "暮", onyomi: "bo", kunyomi: "ku(rasu)", meaning: "evening, livelihood" },
  { kanji: "酒", onyomi: "shu", kunyomi: "sake", meaning: "sake, alcohol" },
  { kanji: "悲", onyomi: "hi", kunyomi: "kana(shii)", meaning: "grieve, sad" },
  { kanji: "晴", onyomi: "sei", kunyomi: "ha(reru)", meaning: "clear up" },
  { kanji: "掛", onyomi: "kei", kunyomi: "ka(karu)", meaning: "hang, suspend" },
  { kanji: "到", onyomi: "tou", kunyomi: "ita(ru)", meaning: "arrival, proceed, reach" },
  { kanji: "寝", onyomi: "shin", kunyomi: "ne(ru)", meaning: "lie down, sleep, rest" },
  { kanji: "暗", onyomi: "an", kunyomi: "kura(i)", meaning: "darkness, disappear, shade, informal" },
  { kanji: "盗", onyomi: "tou", kunyomi: "nusu(mu)", meaning: "steal, rob" },
  { kanji: "吸", onyomi: "kyuu", kunyomi: "su(u)", meaning: "suck, inhale" },
  { kanji: "陽", onyomi: "you", kunyomi: "hi", meaning: "sunshine, positive" },
  { kanji: "御", onyomi: "gyo, go", kunyomi: "on, o", meaning: "honorable" },
  { kanji: "歯", onyomi: "shi", kunyomi: "ha", meaning: "tooth, cog" },
  { kanji: "忘", onyomi: "bou", kunyomi: "wasu(reru)", meaning: "forget" },
  { kanji: "雪", onyomi: "setsu", kunyomi: "yuki", meaning: "snow" },
  { kanji: "吹", onyomi: "sui", kunyomi: "fu(ku)", meaning: "blow, breathe, puff" },
  { kanji: "娘", onyomi: "jou", kunyomi: "musume, ko", meaning: "daughter, girl" },
  { kanji: "誤", onyomi: "go", kunyomi: "ayama(ru)", meaning: "mistake" },
  { kanji: "洗", onyomi: "sen", kunyomi: "ara(u)", meaning: "wash" },
  { kanji: "慣", onyomi: "kan", kunyomi: "na(reru)", meaning: "accustomed, get used to" },
  { kanji: "礼", onyomi: "rei, rai", kunyomi: "", meaning: "salute, bow, ceremony, thanks" },
  { kanji: "窓", onyomi: "sou", kunyomi: "mado", meaning: "window, pane" },
  { kanji: "昔", onyomi: "seki, shaku", kunyomi: "mukashi", meaning: "once upon a time, old times" },
  { kanji: "貧", onyomi: "hin, bin", kunyomi: "mazu(shii)", meaning: "poverty, poor" },
  { kanji: "怒", onyomi: "do", kunyomi: "ika(ru), oko(ru)", meaning: "angry, be offended" },
  { kanji: "泳", onyomi: "ei", kunyomi: "oyo(gu)", meaning: "swim" },
  { kanji: "祖", onyomi: "so", kunyomi: "", meaning: "ancestor, pioneer, founder" },
  { kanji: "杯", onyomi: "hai", kunyomi: "sakazuki", meaning: "glass, cup" },
  { kanji: "疲", onyomi: "hi", kunyomi: "tsuka(reru)", meaning: "exhausted, tire" },
  { kanji: "皆", onyomi: "", kunyomi: "mina, minna", meaning: "all, everyone, everybody" },
  { kanji: "鳴", onyomi: "mei", kunyomi: "na(ru)", meaning: "chirp, cry, bark" },
  { kanji: "腹", onyomi: "fuku", kunyomi: "hara", meaning: "abdomen, belly, stomach" },
  { kanji: "煙", onyomi: "en", kunyomi: "kemu(ru), kemuri", meaning: "smoke" },
  { kanji: "眠", onyomi: "min", kunyomi: "nemu(ru)", meaning: "sleep" },
  { kanji: "怖", onyomi: "fu", kunyomi: "kowa(i), o(jiru)", meaning: "dreadful, fearful" },
  { kanji: "耳", onyomi: "ji", kunyomi: "mimi", meaning: "ear" },
  { kanji: "頂", onyomi: "chou", kunyomi: "itada(ku)", meaning: "receive, top, summit, peak" },
  { kanji: "箱", onyomi: "sou", kunyomi: "hako", meaning: "box, chest" },
  { kanji: "晩", onyomi: "ban", kunyomi: "", meaning: "nightfall, night" },
  { kanji: "寒", onyomi: "kan", kunyomi: "samu(i)", meaning: "cold" },
  { kanji: "髪", onyomi: "hatsu", kunyomi: "kami", meaning: "hair (on the head)" },
  { kanji: "忙", onyomi: "bou, mou", kunyomi: "isoga(shii)", meaning: "busy, occupied" },
  { kanji: "才", onyomi: "sai", kunyomi: "", meaning: "genius, years old" },
  { kanji: "靴", onyomi: "ka", kunyomi: "kutsu", meaning: "shoes" },
  { kanji: "恥", onyomi: "chi", kunyomi: "haji, ha(zukashii)", meaning: "shame, dishonor" },
  { kanji: "偶", onyomi: "guu", kunyomi: "tama", meaning: "accidentally, even number" },
  { kanji: "偉", onyomi: "i", kunyomi: "era(i)", meaning: "admirable, greatness" },
  { kanji: "猫", onyomi: "byou", kunyomi: "neko", meaning: "cat" },
  { kanji: "幾", onyomi: "ki", kunyomi: "iku(tsu)", meaning: "how many, how much, some" },
  { kanji: "誰", onyomi: "sui", kunyomi: "dare", meaning: "who, someone, somebody" }
];