export interface KanjiData {
  kanji: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
}

export const N4_KANJI: KanjiData[] = [
  { kanji: "会", onyomi: "kai", kunyomi: "a(u)", meaning: "meeting; meet" },
  { kanji: "同", onyomi: "dou", kunyomi: "onaji", meaning: "same, agree, equal" },
  { kanji: "事", onyomi: "ji", kunyomi: "koto", meaning: "matter, thing, fact, business, reason, possibly" },
  { kanji: "自", onyomi: "ji, shi", kunyomi: "mizuka(ra)", meaning: "oneself" },
  { kanji: "社", onyomi: "sha", kunyomi: "yashiro", meaning: "company, firm, office, association, shrine" },
  { kanji: "発", onyomi: "hatsu, hotsu", kunyomi: "", meaning: "departure, discharge, emit, start from" },
  { kanji: "者", onyomi: "sha", kunyomi: "mono", meaning: "someone, person" },
  { kanji: "地", onyomi: "chi, ji", kunyomi: "", meaning: "ground, earth" },
  { kanji: "業", onyomi: "gyou", kunyomi: "waza", meaning: "business, vocation, arts, performance" },
  { kanji: "方", onyomi: "hou", kunyomi: "kata", meaning: "direction, person, alternative" },
  { kanji: "新", onyomi: "shin", kunyomi: "atara(shii), ara(ta)", meaning: "new" },
  { kanji: "場", onyomi: "jou", kunyomi: "ba", meaning: "location, place" },
  { kanji: "員", onyomi: "in", kunyomi: "", meaning: "employee, member, number, the one in charge" },
  { kanji: "立", onyomi: "ritsu", kunyomi: "ta(tsu)", meaning: "stand up, rise" },
  { kanji: "開", onyomi: "kai", kunyomi: "hira(ku), a(keru)", meaning: "open, unfold, unseal" },
  { kanji: "手", onyomi: "shu", kunyomi: "te", meaning: "hand" },
  { kanji: "力", onyomi: "ryoku, riki", kunyomi: "chikara", meaning: "power, strength, strong, strain, bear up, exert" },
  { kanji: "問", onyomi: "mon", kunyomi: "to(u)", meaning: "question, ask, problem" },
  { kanji: "代", onyomi: "dai", kunyomi: "ka(wari)", meaning: "substitute, change, convert, replace, period" },
  { kanji: "明", onyomi: "mei, myou", kunyomi: "aka(rui)", meaning: "bright, light" },
  { kanji: "動", onyomi: "dou", kunyomi: "ugo(ku)", meaning: "move, motion, change" },
  { kanji: "京", onyomi: "kyou, kei, kin", kunyomi: "miyako", meaning: "capital" },
  { kanji: "目", onyomi: "moku, boku", kunyomi: "me", meaning: "eye, class, look, insight, experience" },
  { kanji: "通", onyomi: "tsuu", kunyomi: "too(ru), kayo(u)", meaning: "traffic, pass through, avenue, commute" },
  { kanji: "言", onyomi: "gen, gon", kunyomi: "i(u), koto", meaning: "say, word" },
  { kanji: "理", onyomi: "ri", kunyomi: "", meaning: "logic, arrangement, reason, justice, truth" },
  { kanji: "体", onyomi: "tai", kunyomi: "karada", meaning: "body, substance, object, reality" },
  { kanji: "田", onyomi: "den", kunyomi: "ta", meaning: "rice field, rice paddy" },
  { kanji: "主", onyomi: "shu", kunyomi: "nushi, omo", meaning: "lord, chief, master, main thing, principal" },
  { kanji: "題", onyomi: "dai", kunyomi: "", meaning: "topic, subject" },
  { kanji: "意", onyomi: "i", kunyomi: "", meaning: "idea, mind, heart, taste, thought" },
  { kanji: "不", onyomi: "fu, bu", kunyomi: "", meaning: "negative, non-, bad" },
  { kanji: "作", onyomi: "saku, sa", kunyomi: "tsuku(ru)", meaning: "make, production, prepare, build" },
  { kanji: "用", onyomi: "you", kunyomi: "mochi(iru)", meaning: "utilize, business, service, use, employ" },
  { kanji: "度", onyomi: "do, taku", kunyomi: "tabi, ta(i)", meaning: "degrees, occurrence, time, counter for occurrences" },
  { kanji: "強", onyomi: "kyou, gou", kunyomi: "tsuyo(i)", meaning: "strong" },
  { kanji: "公", onyomi: "kou", kunyomi: "", meaning: "public, prince, official, governmental" },
  { kanji: "持", onyomi: "ji", kunyomi: "mo(tsu)", meaning: "hold, have" },
  { kanji: "野", onyomi: "ya", kunyomi: "no", meaning: "plains, field, rustic, civilian life" },
  { kanji: "以", onyomi: "i", kunyomi: "mo(tte)", meaning: "by means of, because, in view of, compared with" },
  { kanji: "思", onyomi: "shi", kunyomi: "omo(u)", meaning: "think" },
  { kanji: "家", onyomi: "ka", kunyomi: "ie, ya, uchi", meaning: "house, home, family, professional, expert" },
  { kanji: "世", onyomi: "sei, se", kunyomi: "yo", meaning: "generation, world, society, public" },
  { kanji: "多", onyomi: "ta", kunyomi: "oo(i)", meaning: "many, frequent, much" },
  { kanji: "正", onyomi: "sei, shou", kunyomi: "tada(shii), masa(ni)", meaning: "correct, justice, righteous" },
  { kanji: "安", onyomi: "an", kunyomi: "yasu(i)", meaning: "safe, peaceful, cheap" },
  { kanji: "院", onyomi: "in", kunyomi: "", meaning: "institution, temple, mansion, school" },
  { kanji: "心", onyomi: "shin", kunyomi: "kokoro", meaning: "heart, mind, spirit" },
  { kanji: "界", onyomi: "kai", kunyomi: "", meaning: "world, boundary" },
  { kanji: "教", onyomi: "kyou", kunyomi: "oshi(eru), oso(waru)", meaning: "teach, faith, doctrine" },
  { kanji: "文", onyomi: "bun, mon", kunyomi: "fumi", meaning: "sentence, literature, style, art" },
  { kanji: "元", onyomi: "gen, gan", kunyomi: "moto", meaning: "beginning, former time, origin" },
  { kanji: "重", onyomi: "juu, chou", kunyomi: "omo(i), kasa(neru)", meaning: "heavy, important, esteem, respect" },
  { kanji: "近", onyomi: "kin", kunyomi: "chika(i)", meaning: "near, early, akin, tantamount" },
  { kanji: "考", onyomi: "kou", kunyomi: "kanga(eru)", meaning: "consider, think over" },
  { kanji: "画", onyomi: "ga, kaku", kunyomi: "kaku(suru)", meaning: "brush-stroke, picture" },
  { kanji: "海", onyomi: "kai", kunyomi: "umi", meaning: "sea, ocean" },
  { kanji: "売", onyomi: "bai", kunyomi: "u(ru)", meaning: "Sell" },
  { kanji: "知", onyomi: "chi", kunyomi: "shi(ru)", meaning: "know, wisdom" },
  { kanji: "道", onyomi: "dou", kunyomi: "michi", meaning: "road-way, street, district, journey, course" },
  { kanji: "集", onyomi: "shuu", kunyomi: "atsu(meru)", meaning: "gather, meet" },
  { kanji: "別", onyomi: "betsu", kunyomi: "waka(reru), wa(keru)", meaning: "separate, branch off, diverge" },
  { kanji: "物", onyomi: "butsu, motsu", kunyomi: "mono", meaning: "thing, object, matter" },
  { kanji: "使", onyomi: "shi", kunyomi: "tsuka(u)", meaning: "use, order, messenger, ambassador" },
  { kanji: "品", onyomi: "hin", kunyomi: "shina", meaning: "goods, refinement, dignity, article" },
  { kanji: "計", onyomi: "kei", kunyomi: "haka(ru)", meaning: "plot, plan, scheme, measure" },
  { kanji: "死", onyomi: "shi", kunyomi: "shi(nu)", meaning: "death, die" },
  { kanji: "特", onyomi: "toku", kunyomi: "", meaning: "special" },
  { kanji: "私", onyomi: "shi", kunyomi: "watakushi, watashi", meaning: "private, I, me" },
  { kanji: "始", onyomi: "shi", kunyomi: "haji(meru)", meaning: "commence, begin" },
  { kanji: "朝", onyomi: "chou", kunyomi: "asa", meaning: "morning" },
  { kanji: "運", onyomi: "un", kunyomi: "hako(bu)", meaning: "carry, luck, destiny, fate, transport" },
  { kanji: "終", onyomi: "shuu", kunyomi: "o(waru)", meaning: "end, finish" },
  { kanji: "台", onyomi: "dai, tai", kunyomi: "utena", meaning: "pedestal, a stand, counter for machines and vehicles" },
  { kanji: "広", onyomi: "kou", kunyomi: "hiro(i)", meaning: "wide, broad, spacious" },
  { kanji: "住", onyomi: "juu, chuu", kunyomi: "su(mu)", meaning: "dwell, reside, live, inhabit" },
  { kanji: "無", onyomi: "mu, bu", kunyomi: "na(i)", meaning: "nothingness, none, ain't, nothing, nil, not" },
  { kanji: "真", onyomi: "shin", kunyomi: "ma, makoto", meaning: "true, reality, Buddhist sect" },
  { kanji: "有", onyomi: "yuu, u", kunyomi: "a(ru)", meaning: "possess, have, exist, happen" },
  { kanji: "口", onyomi: "kou", kunyomi: "kuchi", meaning: "mouth" },
  { kanji: "少", onyomi: "shou", kunyomi: "suku(nai), suko(shi)", meaning: "few, little" },
  { kanji: "町", onyomi: "chou", kunyomi: "machi", meaning: "town, village, block, street" },
  { kanji: "料", onyomi: "ryou", kunyomi: "", meaning: "fee, materials" },
  { kanji: "工", onyomi: "kou, ku, gu", kunyomi: "", meaning: "craft, construction" },
  { kanji: "建", onyomi: "ken, kon", kunyomi: "ta(teru)", meaning: "build" },
  { kanji: "空", onyomi: "kuu", kunyomi: "sora, kara, a(ku), su(ku), muna(shii)", meaning: "empty, sky, void, vacant, vacuum" },
  { kanji: "急", onyomi: "kyuu", kunyomi: "iso(gu)", meaning: "hurry, emergency, sudden, steep" },
  { kanji: "止", onyomi: "shi", kunyomi: "to(maru), todo(maru), ya(meru), yo(su)", meaning: "stop, halt" },
  { kanji: "送", onyomi: "sou", kunyomi: "oku(ru)", meaning: "escort, send" },
  { kanji: "切", onyomi: "setsu, sai", kunyomi: "ki(ru)", meaning: "cut, cutoff, be sharp" },
  { kanji: "転", onyomi: "ten", kunyomi: "koro(garu)", meaning: "revolve, turn around, change" },
  { kanji: "研", onyomi: "ken", kunyomi: "to(gu)", meaning: "polish, study of, sharpen" },
  { kanji: "足", onyomi: "soku", kunyomi: "ashi, ta(riru)", meaning: "leg, foot, be sufficient" },
  { kanji: "究", onyomi: "kyuu", kunyomi: "", meaning: "research, study" },
  { kanji: "楽", onyomi: "gaku, raku", kunyomi: "tano(shii)", meaning: "music, comfort, ease" },
  { kanji: "起", onyomi: "ki", kunyomi: "o(kiru), oko(su)", meaning: "wake up, get up; rouse" },
  { kanji: "着", onyomi: "chaku", kunyomi: "ki(ru), tsu(ku)", meaning: "arrive, wear, counter for suits of clothing" },
  { kanji: "店", onyomi: "ten", kunyomi: "mise", meaning: "store, shop" },
  { kanji: "病", onyomi: "byou", kunyomi: "ya(mu)", meaning: "ill, sick" },
  { kanji: "質", onyomi: "shitsu, shichi", kunyomi: "tachi, tada(su)", meaning: "substance, quality, matter, temperament" },
  { kanji: "待", onyomi: "tai", kunyomi: "ma(tsu)", meaning: "wait, depend on" },
  { kanji: "試", onyomi: "shi", kunyomi: "kokoro(miru), tame(su)", meaning: "test, try, attempt, experiment" },
  { kanji: "族", onyomi: "zoku", kunyomi: "", meaning: "tribe, family" },
  { kanji: "銀", onyomi: "gin", kunyomi: "", meaning: "silver" },
  { kanji: "早", onyomi: "sou, sa", kunyomi: "haya(i)", meaning: "early, fast" },
  { kanji: "映", onyomi: "ei", kunyomi: "utsu(ru), ha(eru)", meaning: "reflect, reflection, projection" },
  { kanji: "親", onyomi: "shin", kunyomi: "oya, shita(shii)", meaning: "parent, intimacy, relative, familiarity" },
  { kanji: "験", onyomi: "ken", kunyomi: "", meaning: "verification, effect, testing" },
  { kanji: "英", onyomi: "ei", kunyomi: "", meaning: "England, English, hero, outstanding" },
  { kanji: "医", onyomi: "i", kunyomi: "", meaning: "doctor, medicine" },
  { kanji: "仕", onyomi: "shi", kunyomi: "", meaning: "attend, doing, official, serve" },
  { kanji: "去", onyomi: "kyo, ko", kunyomi: "sa(ru)", meaning: "gone, past, quit, leave, elapse, eliminate" },
  { kanji: "味", onyomi: "mi", kunyomi: "aji", meaning: "flavor, taste" },
  { kanji: "写", onyomi: "sha", kunyomi: "utsuru", meaning: "copy, be photographed, describe" },
  { kanji: "字", onyomi: "ji", kunyomi: "", meaning: "character, letter, word" },
  { kanji: "答", onyomi: "tou", kunyomi: "kota(eru)", meaning: "solution, answer" },
  { kanji: "夜", onyomi: "ya", kunyomi: "yo, yoru", meaning: "night, evening" },
  { kanji: "音", onyomi: "on", kunyomi: "oto, ne", meaning: "sound, noise" },
  { kanji: "注", onyomi: "chuu", kunyomi: "soso(gu), sa(su), tsu(gu)", meaning: "pour, irrigate, shed (tears), flow into, concentrate on" },
  { kanji: "帰", onyomi: "ki", kunyomi: "kae(ru), kae(su)", meaning: "homecoming, arrive at, lead to, result in" },
  { kanji: "古", onyomi: "ko", kunyomi: "furu(i)", meaning: "old" },
  { kanji: "歌", onyomi: "ka", kunyomi: "uta, uta(u)", meaning: "song, sing" },
  { kanji: "買", onyomi: "bai", kunyomi: "ka(u)", meaning: "buy" },
  { kanji: "悪", onyomi: "aku", kunyomi: "waru(i)", meaning: "bad, evil, wrong" },
  { kanji: "図", onyomi: "zu, to", kunyomi: "haka(ru)", meaning: "map, drawing, plan, extraordinary" },
  { kanji: "週", onyomi: "shuu", kunyomi: "", meaning: "week" },
  { kanji: "室", onyomi: "shitsu", kunyomi: "muro", meaning: "room, apartment, chamber, cellar" },
  { kanji: "歩", onyomi: "ho, bu", kunyomi: "aru(ku), ayu(mu)", meaning: "walk, counter for steps" },
  { kanji: "風", onyomi: "fuu, fu", kunyomi: "kaze, kaza-", meaning: "wind, air, style, manner" },
  { kanji: "紙", onyomi: "shi", kunyomi: "kami", meaning: "paper" },
  { kanji: "黒", onyomi: "koku", kunyomi: "kuro", meaning: "black" },
  { kanji: "花", onyomi: "ka, ke", kunyomi: "hana", meaning: "flower" },
  { kanji: "春", onyomi: "shun", kunyomi: "haru", meaning: "spring" },
  { kanji: "赤", onyomi: "seki, shaku", kunyomi: "aka(i)", meaning: "red" },
  { kanji: "青", onyomi: "sei, shou", kunyomi: "ao(i)", meaning: "blue" },
  { kanji: "館", onyomi: "kan", kunyomi: "yakata", meaning: "building, mansion, large building, palace" },
  { kanji: "屋", onyomi: "oku", kunyomi: "ya", meaning: "roof, house, shop, dealer, seller" },
  { kanji: "色", onyomi: "shoku, shiki", kunyomi: "iro", meaning: "color" },
  { kanji: "走", onyomi: "Sou", kunyomi: "hashi(ru)", meaning: "Run" },
  { kanji: "秋", onyomi: "shuu", kunyomi: "aki", meaning: "autumn, fall" },
  { kanji: "夏", onyomi: "ka, ge", kunyomi: "natsu", meaning: "summer" },
  { kanji: "習", onyomi: "shuu", kunyomi: "nara(u)", meaning: "learn" },
  { kanji: "駅", onyomi: "eki", kunyomi: "", meaning: "station" },
  { kanji: "洋", onyomi: "you", kunyomi: "", meaning: "ocean, sea, foreign, Western style" },
  { kanji: "旅", onyomi: "ryo", kunyomi: "tabi", meaning: "trip, travel" },
  { kanji: "服", onyomi: "fuku", kunyomi: "", meaning: "clothing, admit, obey" },
  { kanji: "夕", onyomi: "seki", kunyomi: "yuu", meaning: "evening" },
  { kanji: "借", onyomi: "shaku", kunyomi: "ka(riru)", meaning: "borrow, rent" },
  { kanji: "曜", onyomi: "you", kunyomi: "", meaning: "weekday" },
  { kanji: "飲", onyomi: "in", kunyomi: "no(mu)", meaning: "drink" },
  { kanji: "肉", onyomi: "niku", kunyomi: "", meaning: "meat" },
  { kanji: "貸", onyomi: "tai", kunyomi: "ka(su), kashi", meaning: "lend" },
  { kanji: "堂", onyomi: "dou", kunyomi: "", meaning: "public chamber, hall" },
  { kanji: "鳥", onyomi: "chou", kunyomi: "tori", meaning: "bird, chicken" },
  { kanji: "飯", onyomi: "han", kunyomi: "meshi", meaning: "meal, rice" },
  { kanji: "勉", onyomi: "ben", kunyomi: "tsuto(meru)", meaning: "exertion, endeavor, effort" },
  { kanji: "冬", onyomi: "tou", kunyomi: "fuyu", meaning: "winter" },
  { kanji: "昼", onyomi: "chuu", kunyomi: "hiru", meaning: "daytime, noon" },
  { kanji: "茶", onyomi: "cha, sa", kunyomi: "", meaning: "tea" },
  { kanji: "弟", onyomi: "tei, dai, de", kunyomi: "otouto", meaning: "younger brother" },
  { kanji: "牛", onyomi: "gyuu", kunyomi: "ushi", meaning: "cow" },
  { kanji: "魚", onyomi: "gyo", kunyomi: "uo, sakana", meaning: "fish" },
  { kanji: "兄", onyomi: "kyou, kei", kunyomi: "ani", meaning: "elder brother" },
  { kanji: "犬", onyomi: "ken", kunyomi: "inu", meaning: "dog" },
  { kanji: "妹", onyomi: "mai", kunyomi: "imouto", meaning: "younger sister" },
  { kanji: "姉", onyomi: "shi", kunyomi: "ane", meaning: "elder sister" },
  { kanji: "漢", onyomi: "kan", kunyomi: "", meaning: "China" }
];