export interface KanjiData {
  kanji: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
}

export const N5_KANJI: KanjiData[] = [
  { kanji: "日", onyomi: "nichi, jitsu", kunyomi: "hi, -bi, -ka", meaning: "day, sun, Japan, counter for days" },
  { kanji: "一", onyomi: "ichi", kunyomi: "hito(tsu)", meaning: "one" },
  { kanji: "国", onyomi: "koku", kunyomi: "kuni", meaning: "country" },
  { kanji: "人", onyomi: "jin, nin", kunyomi: "hito", meaning: "person" },
  { kanji: "年", onyomi: "nen", kunyomi: "toshi", meaning: "year, counter for years" },
  { kanji: "大", onyomi: "dai, tai", kunyomi: "oo(kii)", meaning: "large, big" },
  { kanji: "十", onyomi: "juu", kunyomi: "tou, to", meaning: "ten, 10" },
  { kanji: "二", onyomi: "ni, ji", kunyomi: "futa(tsu), futatabi", meaning: "two, 2" },
  { kanji: "本", onyomi: "hon", kunyomi: "moto", meaning: "book, present, true, counter for long cylindrical things" },
  { kanji: "中", onyomi: "chuu", kunyomi: "naka, uchi", meaning: "in, inside, middle, mean, center" },
  { kanji: "長", onyomi: "chou", kunyomi: "naga(i), osa", meaning: "long, leader, superior, senior" },
  { kanji: "出", onyomi: "shutsu, sui", kunyomi: "de(ru), da(su)", meaning: "exit, leave, go out" },
  { kanji: "三", onyomi: "san", kunyomi: "mi(tsu)", meaning: "three, 3" },
  { kanji: "時", onyomi: "ji", kunyomi: "toki, doki", meaning: "time, hour" },
  { kanji: "行", onyomi: "kou, gyou", kunyomi: "i(ku), yu(ku), okona(u)", meaning: "going, journey, carry out, line, row" },
  { kanji: "見", onyomi: "ken", kunyomi: "mi(ru), mi(seru)", meaning: "see, hopes, chances, idea, opinion, visible" },
  { kanji: "月", onyomi: "getsu, gatsu", kunyomi: "tsuki", meaning: "month, moon" },
  { kanji: "分", onyomi: "bun, fun, bu", kunyomi: "wa(keru)", meaning: "part, minute of time, understand" },
  { kanji: "後", onyomi: "go, kou", kunyomi: "nochi, ushi(ro), ato", meaning: "behind, back, later" },
  { kanji: "前", onyomi: "zen", kunyomi: "mae", meaning: "in front, before" },
  { kanji: "生", onyomi: "sei, shou", kunyomi: "i(kiru), u(mu), o(u), ha(eru), nama", meaning: "life, genuine, birth" },
  { kanji: "五", onyomi: "go", kunyomi: "itsu(tsu)", meaning: "five, 5" },
  { kanji: "間", onyomi: "kan, ken", kunyomi: "aida, ma, ai", meaning: "interval, space" },
  { kanji: "上", onyomi: "jou, shou, shan", kunyomi: "ue, uwa, kami, a(geru), nobo(ru)", meaning: "above, up" },
  { kanji: "東", onyomi: "tou", kunyomi: "higashi", meaning: "east" },
  { kanji: "四", onyomi: "shi", kunyomi: "yo(tsu), yon", meaning: "four, 4" },
  { kanji: "今", onyomi: "kon, kin", kunyomi: "ima", meaning: "now; the present" },
  { kanji: "金", onyomi: "kin, kon, gon", kunyomi: "kane, kana, gane", meaning: "gold" },
  { kanji: "九", onyomi: "kyuu, ku", kunyomi: "kokono(tsu)", meaning: "nine, 9" },
  { kanji: "入", onyomi: "nyuu", kunyomi: "i(ru), hai(ru)", meaning: "enter, insert" },
  { kanji: "学", onyomi: "gaku", kunyomi: "mana(bu)", meaning: "study, learning, science" },
  { kanji: "高", onyomi: "kou", kunyomi: "taka(i)", meaning: "tall, high, expensive" },
  { kanji: "円", onyomi: "en", kunyomi: "maru(i)", meaning: "circle, yen, round" },
  { kanji: "子", onyomi: "shi, su, tsu", kunyomi: "ko, ne", meaning: "child" },
  { kanji: "外", onyomi: "gai, ge", kunyomi: "soto, hoka, hazu(su)", meaning: "outside" },
  { kanji: "八", onyomi: "hachi", kunyomi: "ya(tsu), you", meaning: "eight, 8" },
  { kanji: "六", onyomi: "roku", kunyomi: "mu(tsu), mui", meaning: "six, 6" },
  { kanji: "下", onyomi: "ka, ge", kunyomi: "shita, shimo, moto, sa(geru), kuda(ru), o(rosu)", meaning: "below, down, descend, give, low, inferior" },
  { kanji: "来", onyomi: "rai, tai", kunyomi: "kuru, ki, ko", meaning: "come, due, next, cause, become" },
  { kanji: "気", onyomi: "ki, ke", kunyomi: "iki", meaning: "spirit, mind, air, atmosphere, mood" },
  { kanji: "小", onyomi: "shou", kunyomi: "chii(sai), ko", meaning: "little, small" },
  { kanji: "七", onyomi: "shichi", kunyomi: "nana(tsu), nano", meaning: "seven, 7" },
  { kanji: "山", onyomi: "san, sen", kunyomi: "yama", meaning: "mountain" },
  { kanji: "話", onyomi: "wa", kunyomi: "hana(su), hanashi", meaning: "tale, talk" },
  { kanji: "女", onyomi: "jo", kunyomi: "onnna, me", meaning: "woman, female" },
  { kanji: "北", onyomi: "hoku", kunyomi: "kita", meaning: "north" },
  { kanji: "午", onyomi: "go", kunyomi: "uma", meaning: "noon, sign of the horse" },
  { kanji: "百", onyomi: "hyaku, byaku", kunyomi: "momo", meaning: "hundred" },
  { kanji: "書", onyomi: "sho", kunyomi: "kaku", meaning: "write" },
  { kanji: "先", onyomi: "sen", kunyomi: "saki, ma(zu)", meaning: "before, ahead, previous, future, precedence" },
  { kanji: "名", onyomi: "mei, myou", kunyomi: "na", meaning: "name, noted, distinguished, reputation" },
  { kanji: "川", onyomi: "sen", kunyomi: "kawa", meaning: "river, stream" },
  { kanji: "千", onyomi: "sen", kunyomi: "chi", meaning: "thousand" },
  { kanji: "聞", onyomi: "bun, mon", kunyomi: "ki(ku)", meaning: "to hear; to listen; to ask" },
  { kanji: "水", onyomi: "sui", kunyomi: "mizu", meaning: "water" },
  { kanji: "半", onyomi: "han", kunyomi: "naka(ba)", meaning: "half, middle, odd number, semi-" },
  { kanji: "男", onyomi: "dan, nan", kunyomi: "otoko, o", meaning: "male; man" },
  { kanji: "西", onyomi: "sei, sai", kunyomi: "nishi", meaning: "west" },
  { kanji: "電", onyomi: "den", kunyomi: "", meaning: "electricity; electric powered" },
  { kanji: "語", onyomi: "go", kunyomi: "kata(ru)", meaning: "word, speech, language" },
  { kanji: "土", onyomi: "do, to", kunyomi: "tsuchi", meaning: "soil, earth, ground" },
  { kanji: "木", onyomi: "boku, moku", kunyomi: "ki, ko", meaning: "tree, wood" },
  { kanji: "食", onyomi: "shoku, jiki", kunyomi: "k(u), ta(beru)", meaning: "eat, food" },
  { kanji: "車", onyomi: "sha", kunyomi: "kuruma", meaning: "car, wheel" },
  { kanji: "何", onyomi: "ka", kunyomi: "nani, nan", meaning: "what" },
  { kanji: "南", onyomi: "nan, na", kunyomi: "minami", meaning: "south" },
  { kanji: "万", onyomi: "man, ban", kunyomi: "", meaning: "ten thousand, 10,000" },
  { kanji: "校", onyomi: "kou", kunyomi: "", meaning: "school, exam" },
  { kanji: "毎", onyomi: "mai", kunyomi: "goto(ni)", meaning: "every" },
  { kanji: "白", onyomi: "haku, byaku", kunyomi: "shiro(i)", meaning: "white" },
  { kanji: "天", onyomi: "ten", kunyomi: "amatsu", meaning: "heavens, sky, imperial" },
  { kanji: "母", onyomi: "bo", kunyomi: "haha, kaa", meaning: "mother" },
  { kanji: "火", onyomi: "ka", kunyomi: "hi, bi, ho", meaning: "fire" },
  { kanji: "右", onyomi: "u, yuu", kunyomi: "migi", meaning: "right (direction)" },
  { kanji: "読", onyomi: "doku, toku, tou", kunyomi: "yo(mu)", meaning: "to read" },
  { kanji: "友", onyomi: "yuu", kunyomi: "tomo", meaning: "friend" },
  { kanji: "左", onyomi: "sa, sha", kunyomi: "hidari", meaning: "left" },
  { kanji: "休", onyomi: "kyuu", kunyomi: "yasu(mu)", meaning: "rest, day off, retire, sleep" },
  { kanji: "父", onyomi: "fu", kunyomi: "chichi, tou", meaning: "father" },
  { kanji: "雨", onyomi: "u", kunyomi: "ame, ama", meaning: "rain" }
];