export interface KanjiData {
  kanji: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
}

export const N5_KANJI: KanjiData[] = [
  { kanji: "日", onyomi: "にち、じつ", kunyomi: "ひ、-び、-か", meaning: "day, sun, Japan, counter for days" },
  { kanji: "一", onyomi: "いち", kunyomi: "ひと（つ）", meaning: "one" },
  { kanji: "国", onyomi: "こく", kunyomi: "くに", meaning: "country" },
  { kanji: "人", onyomi: "じん、にん", kunyomi: "ひと", meaning: "person" },
  { kanji: "年", onyomi: "ねん", kunyomi: "とし", meaning: "year, counter for years" },
  { kanji: "大", onyomi: "だい、たい", kunyomi: "おお（きい）", meaning: "large, big" },
  { kanji: "十", onyomi: "じゅう", kunyomi: "とう、と", meaning: "ten, 10" },
  { kanji: "二", onyomi: "に、じ", kunyomi: "ふた（つ）、ふたたび", meaning: "two, 2" },
  { kanji: "本", onyomi: "ほん", kunyomi: "もと", meaning: "book, present, true, counter for long cylindrical things" },
  { kanji: "中", onyomi: "ちゅう", kunyomi: "なか、うち", meaning: "in, inside, middle, mean, center" },
  { kanji: "長", onyomi: "ちょう", kunyomi: "なが（い）、おさ", meaning: "long, leader, superior, senior" },
  { kanji: "出", onyomi: "しゅつ、すい", kunyomi: "で（る）、だ（す）", meaning: "exit, leave, go out" },
  { kanji: "三", onyomi: "さん", kunyomi: "み（つ）", meaning: "three, 3" },
  { kanji: "時", onyomi: "じ", kunyomi: "とき、どき", meaning: "time, hour" },
  { kanji: "行", onyomi: "こう、ぎょう", kunyomi: "い（く）、ゆ（く）、おこな（う）", meaning: "going, journey, carry out, line, row" },
  { kanji: "見", onyomi: "けん", kunyomi: "み（る）、み（せる）", meaning: "see, hopes, chances, idea, opinion, visible" },
  { kanji: "月", onyomi: "げつ、がつ", kunyomi: "つき", meaning: "month, moon" },
  { kanji: "分", onyomi: "ぶん、ふん、ぶ", kunyomi: "わ（ける）", meaning: "part, minute of time, understand" },
  { kanji: "後", onyomi: "ご、こう", kunyomi: "のち、うし（ろ）、あと", meaning: "behind, back, later" },
  { kanji: "前", onyomi: "ぜん", kunyomi: "まえ", meaning: "in front, before" },
  { kanji: "生", onyomi: "せい、しょう", kunyomi: "い（きる）、う（む）、お（う）、は（える）、なま", meaning: "life, genuine, birth" },
  { kanji: "五", onyomi: "ご", kunyomi: "いつ（つ）", meaning: "five, 5" },
  { kanji: "間", onyomi: "かん、けん", kunyomi: "あいだ、ま、あい", meaning: "interval, space" },
  { kanji: "上", onyomi: "じょう、しょう、しゃん", kunyomi: "うえ、うわ、かみ、あ（げる）、のぼ（る）", meaning: "above, up" },
  { kanji: "東", onyomi: "とう", kunyomi: "ひがし", meaning: "east" },
  { kanji: "四", onyomi: "し", kunyomi: "よ（つ）、よん", meaning: "four, 4" },
  { kanji: "今", onyomi: "こん、きん", kunyomi: "いま", meaning: "now; the present" },
  { kanji: "金", onyomi: "きん、こん、ごん", kunyomi: "かね、かな、がね", meaning: "gold" },
  { kanji: "九", onyomi: "きゅう、く", kunyomi: "ここの（つ）", meaning: "nine, 9" },
  { kanji: "入", onyomi: "にゅう", kunyomi: "い（る）、はい（る）", meaning: "enter, insert" },
  { kanji: "学", onyomi: "がく", kunyomi: "まな（ぶ）", meaning: "study, learning, science" },
  { kanji: "高", onyomi: "こう", kunyomi: "たか（い）", meaning: "tall, high, expensive" },
  { kanji: "円", onyomi: "えん", kunyomi: "まる（い）", meaning: "circle, yen, round" },
  { kanji: "子", onyomi: "し、す、つ", kunyomi: "こ、ね", meaning: "child" },
  { kanji: "外", onyomi: "がい、げ", kunyomi: "そと、ほか、はず（す）", meaning: "outside" },
  { kanji: "八", onyomi: "はち", kunyomi: "や（つ）、よう", meaning: "eight, 8" },
  { kanji: "六", onyomi: "ろく", kunyomi: "む（つ）、むい", meaning: "six, 6" },
  { kanji: "下", onyomi: "か、げ", kunyomi: "した、しも、もと、さ（げる）、くだ（る）、お（ろす）", meaning: "below, down, descend, give, low, inferior" },
  { kanji: "来", onyomi: "らい、たい", kunyomi: "くる、き、こ", meaning: "come, due, next, cause, become" },
  { kanji: "気", onyomi: "き、け", kunyomi: "いき", meaning: "spirit, mind, air, atmosphere, mood" },
  { kanji: "小", onyomi: "しょう", kunyomi: "ちい（さい）、こ", meaning: "little, small" },
  { kanji: "七", onyomi: "しち", kunyomi: "なな（つ）、なの", meaning: "seven, 7" },
  { kanji: "山", onyomi: "さん、せん", kunyomi: "やま", meaning: "mountain" },
  { kanji: "話", onyomi: "わ", kunyomi: "はな（す）、はなし", meaning: "tale, talk" },
  { kanji: "女", onyomi: "じょ", kunyomi: "おんな、め", meaning: "woman, female" },
  { kanji: "北", onyomi: "ほく", kunyomi: "きた", meaning: "north" },
  { kanji: "午", onyomi: "ご", kunyomi: "うま", meaning: "noon, sign of the horse" },
  { kanji: "百", onyomi: "ひゃく、びゃく", kunyomi: "もも", meaning: "hundred" },
  { kanji: "書", onyomi: "しょ", kunyomi: "かく", meaning: "write" },
  { kanji: "先", onyomi: "せん", kunyomi: "さき、ま（ず）", meaning: "before, ahead, previous, future, precedence" },
  { kanji: "名", onyomi: "めい、みょう", kunyomi: "な", meaning: "name, noted, distinguished, reputation" },
  { kanji: "川", onyomi: "せん", kunyomi: "かわ", meaning: "river, stream" },
  { kanji: "千", onyomi: "せん", kunyomi: "ち", meaning: "thousand" },
  { kanji: "聞", onyomi: "ぶん、もん", kunyomi: "き（く）", meaning: "to hear; to listen; to ask" },
  { kanji: "水", onyomi: "すい", kunyomi: "みず", meaning: "water" },
  { kanji: "半", onyomi: "はん", kunyomi: "なか（ば）", meaning: "half, middle, odd number, semi-" },
  { kanji: "男", onyomi: "だん、なん", kunyomi: "おとこ、お", meaning: "male; man" },
  { kanji: "西", onyomi: "せい、さい", kunyomi: "にし", meaning: "west" },
  { kanji: "電", onyomi: "でん", kunyomi: "", meaning: "electricity; electric powered" },
  { kanji: "語", onyomi: "ご", kunyomi: "かた（る）", meaning: "word, speech, language" },
  { kanji: "土", onyomi: "ど、と", kunyomi: "つち", meaning: "soil, earth, ground" },
  { kanji: "木", onyomi: "ぼく、もく", kunyomi: "き、こ", meaning: "tree, wood" },
  { kanji: "食", onyomi: "しょく、じき", kunyomi: "く（う）、た（べる）", meaning: "eat, food" },
  { kanji: "車", onyomi: "しゃ", kunyomi: "くるま", meaning: "car, wheel" },
  { kanji: "何", onyomi: "か", kunyomi: "なに、なん", meaning: "what" },
  { kanji: "南", onyomi: "なん、な", kunyomi: "みなみ", meaning: "south" },
  { kanji: "万", onyomi: "まん、ばん", kunyomi: "", meaning: "ten thousand, 10,000" },
  { kanji: "校", onyomi: "こう", kunyomi: "", meaning: "school, exam" },
  { kanji: "毎", onyomi: "まい", kunyomi: "ごと（に）", meaning: "every" },
  { kanji: "白", onyomi: "はく、びゃく", kunyomi: "しろ（い）", meaning: "white" },
  { kanji: "天", onyomi: "てん", kunyomi: "あまつ", meaning: "heavens, sky, imperial" },
  { kanji: "母", onyomi: "ぼ", kunyomi: "はは、かあ", meaning: "mother" },
  { kanji: "火", onyomi: "か", kunyomi: "ひ、び、ほ", meaning: "fire" },
  { kanji: "右", onyomi: "う、ゆう", kunyomi: "みぎ", meaning: "right (direction)" },
  { kanji: "読", onyomi: "どく、とく、とう", kunyomi: "よ（む）", meaning: "to read" },
  { kanji: "友", onyomi: "ゆう", kunyomi: "とも", meaning: "friend" },
  { kanji: "左", onyomi: "さ、しゃ", kunyomi: "ひだり", meaning: "left" },
  { kanji: "休", onyomi: "きゅう", kunyomi: "やす（む）", meaning: "rest, day off, retire, sleep" },
  { kanji: "父", onyomi: "ふ", kunyomi: "ちち、とう", meaning: "father" },
  { kanji: "雨", onyomi: "う", kunyomi: "あめ、あま", meaning: "rain" }
];