/**
 * scripts/submit-indexnow.ts
 *
 * Daily IndexNow submission, so Bing / Yandex / Naver / Seznam learn about new
 * or changed pages within minutes instead of waiting on their own crawl budget.
 * Run manually:  npx tsx --tsconfig tsconfig.json scripts/submit-indexnow.ts
 * Run in CI:     .github/workflows/indexnow-submit.yml (daily at 06:00 UTC)
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THIS EXISTS, AND WHY IT DOESN'T TOUCH GOOGLE
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Google has no public "index this URL now" API for ordinary web pages — its
 * Indexing API is restricted (by Google's own terms) to JobPosting and
 * BroadcastEvent(livestream) structured data. Calling it for a kanji page is a
 * ToS violation and Google ignores the result anyway. So for Google, the only
 * levers are the sitemap (this script doesn't help) and Search Console's
 * manual "Request Indexing" button (see scripts/check-index-status.ts, which
 * tells you WHICH urls deserve that click — it can't click it for you).
 *
 * IndexNow is different: it's an actual open protocol Bing/Yandex/Naver/Seznam
 * committed to, and a single POST really does get URLs crawled fast. This
 * script automates the one push that's real.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * HOW IT DECIDES WHAT TO SUBMIT
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * It fetches the live sitemap (the same one Google/Bing already read from
 * robots.txt's `Sitemap:` line) rather than re-deriving the URL list from
 * app/sitemap.xml/route.ts's source data. That's a deliberate choice: it means
 * this script only ever submits what's actually live and public, and it stays
 * correct even if the sitemap's URL set changes for reasons this script
 * doesn't know about.
 *
 * Each URL's `<lastmod>` is compared against `data/indexnow-state.json` (the
 * last value this script itself submitted for that URL). Only new or changed
 * URLs get submitted — most days that's zero, because
 * lib/seo/site.ts's lastmod constants are hand-bumped, not `new Date()`. That
 * makes a daily cron cheap and idempotent instead of re-submitting the same
 * ~1,900 URLs every run.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { SITE_URL } from '../lib/seo/site';
import { INDEXNOW_KEY } from '../lib/seo/indexnow';

// ─── Types ───────────────────────────────────────────────────────────────────

/** One `<url>` entry read out of the live sitemap. */
export interface SitemapEntry {
  loc: string;
  lastmod: string;
}

/** Persisted map of URL -> the lastmod value we last successfully submitted for it. */
export type IndexNowState = Record<string, string>;

export interface DiffResult {
  /** Entries that are new or whose lastmod changed since the last submission. */
  changed: SitemapEntry[];
  /** Entries whose lastmod matches what's already recorded — nothing to do. */
  unchanged: SitemapEntry[];
}

// ─── Config ──────────────────────────────────────────────────────────────────

const STATE_PATH = resolve(
  __dirname,
  '..',
  process.env.INDEXNOW_STATE_FILE ?? 'data/indexnow-state.json'
);

const INDEXNOW_ENDPOINT = 'https://api.indexnow.org/indexnow';

// ─── Sitemap parsing ─────────────────────────────────────────────────────────

/**
 * Dependency-free scan for `<url>...<loc>X</loc>...<lastmod>Y</lastmod>...</url>`
 * blocks. This sitemap is hand-generated by app/sitemap.xml/route.ts with a
 * fixed, simple shape (no namespaces, no CDATA, no nested <url> tags), so a
 * regex scan is correct and avoids pulling in an XML parser for one call site.
 */
export function parseSitemap(xml: string): SitemapEntry[] {
  const entries: SitemapEntry[] = [];
  const urlBlockRe = /<url>([\s\S]*?)<\/url>/g;
  let block: RegExpExecArray | null;
  while ((block = urlBlockRe.exec(xml)) !== null) {
    const locMatch = /<loc>([\s\S]*?)<\/loc>/.exec(block[1]);
    const lastmodMatch = /<lastmod>([\s\S]*?)<\/lastmod>/.exec(block[1]);
    if (!locMatch) continue;
    entries.push({
      loc: locMatch[1].trim(),
      // A sitemap entry missing <lastmod> is still valid, so keep it rather than
      // skip it. NOTE: an earlier comment here claimed the empty string makes such
      // an entry "always changed" — that is FALSE, and was verified false: '' is
      // recorded into state like any other value and thereafter compares equal, so
      // the URL is submitted exactly once and then never again however much it
      // changes. Currently latent — all 1,906 live sitemap entries carry a
      // <lastmod>, and app/sitemap.xml/route.ts always emits one.
      lastmod: lastmodMatch ? lastmodMatch[1].trim() : '',
    });
  }
  return entries;
}

// ─── Diffing ─────────────────────────────────────────────────────────────────

/** Pure: which entries need submitting given what was recorded last time. */
export function diffAgainstState(entries: SitemapEntry[], state: IndexNowState): DiffResult {
  const changed: SitemapEntry[] = [];
  const unchanged: SitemapEntry[] = [];
  for (const entry of entries) {
    if (state[entry.loc] === entry.lastmod) {
      unchanged.push(entry);
    } else {
      changed.push(entry);
    }
  }
  return { changed, unchanged };
}

// ─── State persistence ───────────────────────────────────────────────────────

export function loadState(path: string): IndexNowState {
  if (!existsSync(path)) return {};
  const parsed = JSON.parse(readFileSync(path, 'utf8'));
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error(`${path} is malformed: expected a flat { url: lastmod } object.`);
  }
  return parsed as IndexNowState;
}

export function saveState(path: string, state: IndexNowState): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(state, null, 2)}\n`, 'utf8');
}

// ─── IndexNow submission ─────────────────────────────────────────────────────

export interface IndexNowPayload {
  host: string;
  key: string;
  keyLocation: string;
  urlList: string[];
}

/** Pure: builds the exact request body IndexNow expects. */
export function buildIndexNowPayload(siteUrl: string, key: string, urls: string[]): IndexNowPayload {
  const host = new URL(siteUrl).hostname;
  return {
    host,
    key,
    keyLocation: `${siteUrl}/${key}.txt`,
    urlList: urls,
  };
}

/** Human-readable meaning of IndexNow's documented response codes. */
function describeStatus(status: number): string {
  switch (status) {
    case 200:
      return 'OK — URLs accepted.';
    case 202:
      return 'Accepted — key validation is pending; URLs were still queued.';
    case 400:
      return 'Bad request — malformed payload (check host/key/urlList shape).';
    case 403:
      return 'Forbidden — key not valid (e.g. key file 404s or its content does not match).';
    case 422:
      return 'Unprocessable — URLs do not belong to the host, or the key does not match the host.';
    case 429:
      return 'Too many requests — submitted too often; back off and retry later.';
    default:
      return '(undocumented status)';
  }
}

async function submitToIndexNow(payload: IndexNowPayload): Promise<{ ok: boolean; status: number }> {
  const res = await fetch(INDEXNOW_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
    body: JSON.stringify(payload),
    // Without this, a stalled endpoint blocks on undici's ~300s header +
    // ~300s body defaults and burns ten minutes of runner time.
    signal: AbortSignal.timeout(30_000),
  });
  return { ok: res.ok, status: res.status };
}

/**
 * Confirm the key file is actually reachable and correct BEFORE submitting.
 *
 * IndexNow authenticates by fetching `keyLocation` and comparing its contents to
 * `key`. If that 404s the whole batch is rejected. This is not hypothetical: the
 * key file was already absent from production once (added, reverted, re-added),
 * and during that window every run would have failed with a generic error. A
 * two-second GET converts that into an unmistakable message.
 */
async function preflightKeyFile(siteUrl: string, key: string): Promise<void> {
  const url = `${siteUrl}/${key}.txt`;
  let res: Response;
  try {
    res = await fetch(url, { signal: AbortSignal.timeout(15_000) });
  } catch (err) {
    throw new Error(`Could not fetch the IndexNow key file at ${url}: ${err instanceof Error ? err.message : err}`);
  }
  if (!res.ok) {
    throw new Error(
      `IndexNow key file ${url} returned ${res.status}, so IndexNow would reject ` +
        `this submission with 403.\nIt must be deployed and publicly reachable. ` +
        `Confirm public/${key}.txt exists on the deployed commit — a production ` +
        `deploy that predates the file will 404 here.`
    );
  }
  const body = (await res.text()).trim();
  if (body !== key) {
    throw new Error(
      `IndexNow key file ${url} is reachable but its contents do not match the key.\n` +
        `  expected: ${key}\n  actual:   ${body.slice(0, 120)}`
    );
  }
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log('\n═══ MichiKanji IndexNow Submit ═══');
  console.log(`Sitemap: ${SITE_URL}/sitemap.xml`);

  await preflightKeyFile(SITE_URL, INDEXNOW_KEY);
  console.log(`Key file: ${SITE_URL}/${INDEXNOW_KEY}.txt — 200, contents match.`);

  const res = await fetch(`${SITE_URL}/sitemap.xml`, { signal: AbortSignal.timeout(30_000) });
  if (!res.ok) {
    throw new Error(`Failed to fetch sitemap (${res.status}). Is the site up?`);
  }
  const xml = await res.text();
  const entries = parseSitemap(xml);
  if (entries.length === 0) {
    throw new Error('Parsed zero <url> entries out of the sitemap — check the sitemap route or the parser regex.');
  }

  const state = loadState(STATE_PATH);
  const { changed, unchanged } = diffAgainstState(entries, state);

  console.log(`Sitemap URLs: ${entries.length}`);
  console.log(`Unchanged (skipped): ${unchanged.length}`);
  console.log(`New or changed: ${changed.length}`);

  if (changed.length === 0) {
    console.log('\nNothing to submit — every URL matches its last-submitted lastmod.');
    console.log('═══════════════════════════════════\n');
    return;
  }

  // IndexNow 422s the ENTIRE batch if any URL is not under `host`. The sitemap's
  // base is `process.env.NEXT_PUBLIC_APP_URL || SITE_URL`, so if that env var is
  // ever set to a preview or apex host the two silently diverge and every run
  // fails. Catch it here with a precise message instead.
  const foreign = changed.filter((e) => !e.loc.startsWith(`${SITE_URL}/`) && e.loc !== SITE_URL);
  if (foreign.length > 0) {
    throw new Error(
      `${foreign.length} sitemap URL(s) are not under ${SITE_URL}, which would make ` +
        `IndexNow reject the whole batch with 422. First: ${foreign[0].loc}\n` +
        'Most likely NEXT_PUBLIC_APP_URL is set to a different host than config.domainName.'
    );
  }

  const payload = buildIndexNowPayload(SITE_URL, INDEXNOW_KEY, changed.map((e) => e.loc));
  console.log(`\nSubmitting ${payload.urlList.length} URL(s) to ${INDEXNOW_ENDPOINT}...`);
  changed.slice(0, 10).forEach((e) => console.log(`  • ${e.loc} (lastmod ${e.lastmod || '—'})`));
  if (changed.length > 10) console.log(`  ...and ${changed.length - 10} more`);

  const { ok, status } = await submitToIndexNow(payload);
  console.log(`\nResponse: ${status} — ${describeStatus(status)}`);

  if (!ok) {
    // Don't write state on failure — an unsubmitted URL should be retried next run,
    // not silently marked as done.
    throw new Error(
      `IndexNow submission failed (${status}). Verify ${SITE_URL}/${INDEXNOW_KEY}.txt ` +
        `is publicly reachable and returns exactly "${INDEXNOW_KEY}".`
    );
  }

  // Only 200 means "accepted". 202 means key validation is still PENDING, and
  // `res.ok` is true for both — so recording state on 202 would permanently mark
  // URLs as submitted that IndexNow may then silently drop when validation
  // fails. That is the mirror image of the runaway-resubmission risk and far
  // harder to notice: submissions just quietly stop happening. Retry next run.
  if (status !== 200) {
    console.warn(
      `\n⚠️  Status ${status} means the submission was queued but key validation is ` +
        'still pending, so acceptance is unconfirmed. Deliberately NOT recording ' +
        'state — these URLs will be retried on the next run. If this persists, the ' +
        `key file at ${SITE_URL}/${INDEXNOW_KEY}.txt is likely not validating.`
    );
    return;
  }

  const nextState: IndexNowState = { ...state };
  for (const entry of changed) nextState[entry.loc] = entry.lastmod;
  saveState(STATE_PATH, nextState);

  console.log(`✅ Submitted and recorded ${changed.length} URL(s) in ${STATE_PATH}`);
  console.log('═══════════════════════════════════\n');
}

if (process.argv[1] && /submit-indexnow(\.[cm]?[jt]s)?$/.test(process.argv[1])) {
  main().catch((err: unknown) => {
    console.error('submit-indexnow script failed:', err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
