/**
 * Companion YouTube videos, by episode slug.
 *
 * A separate, hand-edited file because nothing else can hold this. The
 * `data/stories/ep-NN.ts` files are generated by the importer and are not
 * editable (a hand edit is overwritten by the next re-import, or diverges from
 * the strip without anything reporting it), and the strips repo that feeds them
 * is unversioned, so a video id put there would be unrecoverable. This file is
 * tracked, small and imports nothing.
 *
 * This file is kept current by `.github/workflows/sync-story-videos.yml`
 * (`pnpm stories:sync-videos`), daily: it reads the channel's public feed and
 * ADDS a line for an upload whose title lists (before the `|`) at least three
 * kanji that all belong to exactly one episode's focusKanji. It never overwrites
 * or removes a line, so a hand edit here is final: to fix a wrong match, replace
 * the id on the line. Do not just delete it: the next run re-adds it while the
 * video's title still matches, so fix the title on YouTube too.
 *
 * To attach a video by hand: add one line keyed by the episode slug, e.g.
 *
 *   'tan-climbs-the-mountain': { youtubeId: 'dQw4w9WgXcQ', aspect: 'portrait' },
 *
 * `aspect` is optional and means the shape of the VIDEO, not the thumbnail:
 * 'portrait' for a vertical YouTube Short (1080x1920, 9:16), 'landscape' (the
 * default when omitted) for an ordinary 16:9 upload. It picks the player box and
 * the thumbnail. The sync adds `aspect: 'portrait'` itself when the feed links
 * the upload as /shorts/, but like the id it never edits an existing line, so
 * for a line already here you change the aspect by hand. Then run `pnpm validate:stories`, which checks the id's shape, that the slug
 * is a registered episode, and that no id is used twice. An episode with no
 * entry renders no video section at all, and the empty map is valid.
 *
 * Episode page only. The email deliberately never shows the video.
 *
 * The privacy policy names the thumbnail (i.ytimg.com, loaded on scroll) and the
 * player (youtube-nocookie.com, loaded only on click) under "Videos on story
 * pages" and lists Google (YouTube) as a provider. If either ever loads
 * earlier, or a second embed host appears, update `app/privacy-policy/page.tsx`
 * first (its header lists the claim to re-check).
 */
export interface EpisodeVideo {
  /** The 11-character YouTube video id (the `v=` value), nothing else. */
  youtubeId: string;
  /**
   * The video's shape. Omitted means 'landscape'. 'portrait' is a vertical
   * Short: the page draws a 9:16 box and uses a portrait thumbnail.
   */
  aspect?: VideoAspect;
}

export type VideoAspect = 'portrait' | 'landscape';

export const EPISODE_VIDEOS: Record<string, EpisodeVideo> = {
  'tan-climbs-the-mountain': { youtubeId: 'sIi1M-d-gTg', aspect: 'portrait' },
  'tan-finds-the-river': { youtubeId: '4wNQgUiBU6s', aspect: 'portrait' },
  'tan-goes-to-school': { youtubeId: 'opwFPNQom8Y', aspect: 'portrait' },
  'a-rainy-day-off': { youtubeId: 'ZMNIAOPGigg', aspect: 'portrait' },
};
