/**
 * Companion YouTube videos, by episode slug.
 *
 * A separate, hand-edited file because nothing else can hold this. The
 * `data/stories/ep-NN.ts` files are generated by the importer and are not
 * editable (a hand edit is overwritten by the next re-import, or diverges from
 * the strip without anything reporting it), and the strips repo that feeds them
 * is unversioned, so a video id put there would be unrecoverable. This file is
 * tracked, small and imports nothing.
 *
 * To attach a video: add one line keyed by the episode slug, e.g.
 *
 *   'tan-climbs-the-mountain': { youtubeId: 'dQw4w9WgXcQ' },
 *
 * then run `pnpm validate:stories`, which checks the id's shape, that the slug
 * is a registered episode, and that no id is used twice. An episode with no
 * entry renders no video section at all, and the empty map is valid.
 *
 * Episode page only. The email deliberately never shows the video.
 *
 * The privacy policy names the thumbnail (i.ytimg.com, loaded on scroll) and the
 * player (youtube-nocookie.com, loaded only on click) under "Videos on story
 * pages" and lists Google (YouTube) as a provider. If either ever loads
 * earlier, or a second embed host appears, update `app/privacy-policy/page.tsx`
 * first (its header lists the claim to re-check).
 */
export interface EpisodeVideo {
  /** The 11-character YouTube video id (the `v=` value), nothing else. */
  youtubeId: string;
}

export const EPISODE_VIDEOS: Record<string, EpisodeVideo> = {};
